### ISSUE TITLE
CPU overload after CME error

### ISSUE THREAD

**Issue by Ghostlyr** [RS485/LogisticsPipes#1018]
```
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]: Exception in thread "LogisticsPipes Packet Compressor Server" 
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]: java.util.ConcurrentModificationException
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at java.util.ArrayList$Itr.next(ArrayList.java:851)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.routing.order.LogisticsOrder.getProgresses(LogisticsOrder.java:71)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream.writeOrderInfo(LPDataOutputStream.java:179)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream$3.writeObject(LPDataOutputStream.java:205)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream$3.writeObject(LPDataOutputStream.java:201)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream.writeList(LPDataOutputStream.java:165)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream.writeLinkedLogisticsOrderList(LPDataOutputStream.java:201)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream$4.writeObject(LPDataOutputStream.java:212)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream$4.writeObject(LPDataOutputStream.java:208)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream.writeList(LPDataOutputStream.java:165)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream.writeLinkedLogisticsOrderList(LPDataOutputStream.java:208)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream$4.writeObject(LPDataOutputStream.java:212)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream$4.writeObject(LPDataOutputStream.java:208)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream.writeList(LPDataOutputStream.java:165)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream.writeLinkedLogisticsOrderList(LPDataOutputStream.java:208)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream$4.writeObject(LPDataOutputStream.java:212)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream$4.writeObject(LPDataOutputStream.java:208)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream.writeList(LPDataOutputStream.java:165)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.LPDataOutputStream.writeLinkedLogisticsOrderList(LPDataOutputStream.java:208)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.network.packets.orderer.OrdererWatchPacket.writeData(OrdererWatchPacket.java:39)
[18:07:31] [LogisticsPipes Packet Compressor Server/WARN]:  at logisticspipes.ticks.ServerPacketBufferHandlerThread$ServerCompressorThread.run(ServerPacketBufferHandlerThread.java:66)
[18:07:57] [Netty IO #4/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException
[18:12:23] [Server thread/ERROR]: Detected ongoing potential memory leak. 100 packets have leaked. Top offenders
[18:12:23] [Server thread/ERROR]:    FML : 100
[18:12:23] [Server thread/ERROR]: Detected ongoing potential memory leak. 200 packets have leaked. Top offenders
[18:12:23] [Server thread/ERROR]:    FML : 200
```

Unfortunately, I dont know how to reproduce it. Have noticed it only several times. But as I understand it, it is the same as that in issue #993. After server restart all comes back to normal.

Using on Thermos 55 on Forge 1614 ( https://github.com/CyberdyneCC/Thermos )

Mods: 

```
LogisticsPipes 0.9.3.121
Railcraft 9.12.2.0
Industrialcraft b822
CoFHCore 3.1.2-325
ThermalFoundation 1.2.3-112
ThermalExpansion 4.1.2-240
ThermalDynamics 1.2.0B2-169
RedstoneArsenal 1.1.2-92
SimplyJetpacks 1.5.3
RFDrills 1.7.3
ProjectRed Integration 4.7.0pre12.95
ProjectRed Base 4.7.0pre12.95
IC2NuclearControl 2.3.3a
Buildcraft 7.1.16
```

**Comment by HadesDurin** [comment]
latest lp build is 0.9.0.3.124

**Comment by Ghostlyr** [comment]
Yes, I know. But between these builds have been only minor fixes, that should not cause the problem mentioned above.

**Comment by AEnterprise** [comment]
this kind of crash heapens when 2 different threads iterate through the same arraylist, most likely thermos is doing some hacks that causes 2 LP components that use the same list to be on different threads

**Comment by davboecki** [comment]
That's actually just LP causing that. https://github.com/RS485/LogisticsPipes/issues/993
