### ISSUE TITLE
BC Proxy issue

### ISSUE THREAD

**Issue by HadesDurin** [RS485/LogisticsPipes#1019]
using latest LP 0.9.3.124
BC 7.1.16
BC-Compat 7.1.5

coppied directly from logfiles:
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at buildcraft.transport.TravelingItem.writeToNBT(TravelingItem.java:188)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at buildcraft.transport.PipeTransportItems.writeToNBT(PipeTransportItems.java:452)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at buildcraft.transport.Pipe.writeToNBT(Pipe.java:164)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.proxy.buildcraft.subproxies.LPBCTileGenericPipe.writeToNBT_LP(LPBCTileGenericPipe.java:73)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.asm.wrapper.generated.BCTilePartProxyWrapper.writeToNBT_LP(.LP|ASM.dynamic:152)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145841_b(LogisticsTileGenericPipe.java:337)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mcp.mobius.waila.api.impl.DataAccessorCommon.getNBTData(DataAccessorCommon.java:113)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at tterrag.wailaplugins.plugins.PluginIFluidHandler.getBody(PluginIFluidHandler.java:37)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at tterrag.wailaplugins.plugins.PluginBase.getWailaBody(PluginBase.java:148)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mcp.mobius.waila.api.impl.MetaDataProvider.handleBlockTextData(MetaDataProvider.java:158)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:87)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.common.eventhandler.ASMEventHandler_953_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.main.Main.main(SourceFile:148)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.reflect.Method.invoke(Unknown Source)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:52:05] [Client thread/FATAL] [LogisticsPipes/]: Disabled BCProxy for Mod: BuildCraft|Transport+BuildCraft|Silicon+BuildCraft|Robotics. Cause was an Exception

**Comment by HadesDurin** [comment]
so i revert back to 123 version of logistic pipes and all was fine
then noticing 125 build of lp and use that version
all was fine till moments ago

[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at buildcraft.transport.TravelingItem.writeToNBT(TravelingItem.java:188)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at buildcraft.transport.PipeTransportItems.writeToNBT(PipeTransportItems.java:452)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at buildcraft.transport.Pipe.writeToNBT(Pipe.java:164)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.proxy.buildcraft.subproxies.LPBCTileGenericPipe.writeToNBT_LP(LPBCTileGenericPipe.java:73)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.asm.wrapper.generated.BCTilePartProxyWrapper.writeToNBT_LP(.LP|ASM.dynamic:192)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145841_b(LogisticsTileGenericPipe.java:337)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mcp.mobius.waila.api.impl.DataAccessorCommon.getNBTData(DataAccessorCommon.java:113)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at tterrag.wailaplugins.plugins.PluginIFluidHandler.getBody(PluginIFluidHandler.java:37)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at tterrag.wailaplugins.plugins.PluginBase.getWailaBody(PluginBase.java:148)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mcp.mobius.waila.api.impl.MetaDataProvider.handleBlockTextData(MetaDataProvider.java:158)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:87)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.common.eventhandler.ASMEventHandler_953_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.main.Main.main(SourceFile:148)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.reflect.Method.invoke(Unknown Source)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[12:40:15] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[12:40:15] [Client thread/FATAL] [LogisticsPipes/]: Disabled BCProxy for Mod: BuildCraft|Transport+BuildCraft|Silicon+BuildCraft|Robotics. Cause was an Exception
![2016-06-19_12 43 18](https://cloud.githubusercontent.com/assets/5231067/16176889/0e554cb6-361c-11e6-90e2-a6406e5fa932.png)
