### ISSUE TITLE
NPE / Ticking Tile Entity

### ISSUE THREAD

**Issue by Flow86** [RS485/LogisticsPipes#102]
Hi,

I know I'm using a bit older Version (build 510) since otherwise its not compatible with the rest of my mods (forestry, etc)

I threw some items into a obisidan pipe connected to a routing network, which caused the crash:

```
net.minecraft.util.ReportedException: Ticking tile entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:658)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:275)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:571)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
Caused by: java.lang.NullPointerException
        at logisticspipes.routing.RoutedEntityItem.getTickToTimeOut(RoutedEntityItem.java:393)
        at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:334)
        at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:198)
        at net.minecraft.world.World.func_72939_s(World.java:2199)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:546)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:652)
        ... 4 more
```

any Ideas how to fix (and recover my server/map)

**Comment by Flow86** [comment]
I resolved it by compiling logipipes myself and recovered my map with this null check here:

206ee6ef3fd55e9794cbced23d05649a3034bd8f

perhaps something corrupted the routed entity. I got a "Leaking Map..." warning after a while, but I think some item was simply lost in space

**Comment by bziemons** [comment]
.. I think I still get thousands of leaking map warnings. Don't even know if it's Logistics Pipes tho.
That fix should be looked into, yes. Accepted.
