### ISSUE TITLE
Error with Logistics pipes/Applied Energistics.

### ISSUE THREAD

**Issue by Mokeomehit** [RS485/LogisticsPipes#109]
Running LegisticsPipes-DevMC1.5.2-0.7.3.dev.566 and AppEng rv11-b

2013-06-30 12:10:29 [INFO] Hey, don't get routers for pipes that aren't ready
2013-06-30 12:10:29 [SEVERE] java.lang.Throwable
2013-06-30 12:10:29 [SEVERE]    at logisticspipes.pipes.basic.CoreRoutedPipe.getRouter(CoreRoutedPipe.java:615)
2013-06-30 12:10:29 [SEVERE]    at logisticspipes.pipes.PipeItemsRequestLogistics.getCraftedItems(PipeItemsRequestLogistics.java:112)
2013-06-30 12:10:29 [SEVERE]    at appeng.proxy.ProxyLP.getCraftedItems(ProxyLP.java:123)
2013-06-30 12:10:29 [SEVERE]    at appeng.proxy.ProxyLP.getInv(ProxyLP.java:64)
2013-06-30 12:10:29 [SEVERE]    at appeng.me.tile.TileInterfaceBase.addRequestPipe(TileInterfaceBase.java:522)
2013-06-30 12:10:29 [SEVERE]    at appeng.me.tile.TileInterfaceBase.getLogisticsInv(TileInterfaceBase.java:530)
2013-06-30 12:10:29 [SEVERE]    at appeng.me.tile.TileController.getFullCellArray(TileController.java:863)
2013-06-30 12:10:29 [SEVERE]    at appeng.me.tile.TileController.configureController(TileController.java:1397)
2013-06-30 12:10:29 [SEVERE]    at appeng.common.grid.GridEnumeration.update(GridEnumeration.java:319)
2013-06-30 12:10:29 [SEVERE]    at appeng.common.grid.MEGridEvents.tickStart(MEGridEvents.java:218)
2013-06-30 12:10:29 [SEVERE]    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:28)
2013-06-30 12:10:29 [SEVERE]    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:122)
2013-06-30 12:10:29 [SEVERE]    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:295)
2013-06-30 12:10:29 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:804)
2013-06-30 12:10:29 [SEVERE]    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
2013-06-30 12:10:29 [SEVERE]    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:716)
2013-06-30 12:10:29 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600)
2013-06-30 12:10:29 [SEVERE]    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

Im not sure if this is a error with logistics pipes or with Applied Energistics.  Please let me know if I need to report this to him.

Thanks for the great mod!

**Comment by bziemons** [comment]
Similar to https://github.com/RS485/LogisticsPipes/issues/686

Edit: Messed the issues up ;)

**Comment by ArtForz** [comment]
We should probably just add a check there and simply return nothing while the pipe hasn't finished initing...

**Comment by bziemons** [comment]
Yes and maybe a jdoc comment that it does return null, if the pipe is not initialized. Can you just do that and mark this as fixed?

**Comment by ArtForz** [comment]
Made it return a empty list while the pipe isn't ready yet,  other mods should be able to handle that without any changes.
