### ISSUE TITLE
NullPointerException with fuzzy upgrade module

### ISSUE THREAD

**Issue by bothie** [RS485/LogisticsPipes#1094]
This was my setup: a 4x5 array of Filing Cabinets for the Armor and Weapon mob drops which I wanted to connect to my LP Network. So I made 20 chassis Mk2, ItemSink & Provider Module and the Fuzzy Upgrades, cheated in Upgrade Module Upgrades. I placed the pipes, added the two modules and the UMUs. Then, going into first pipe with the wrench, I accidentally placed 16 Fuzzy Upgrades into the slot next to the ItemSink. I didn't take long (<1s) to realize that error and I wanted to remove those Upgrades, but that moment (I'm not sure whether before or after removing that modules), the server (dedicated server locally on same system as client) crashed, now leaving me with a world that can't be reloaded (crash with same NPE on startup).

```
[13:22:01] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NullPointerException
        at logisticspipes.modules.ModuleItemSink.getSpecificInterests(ModuleItemSink.java:252) ~[ModuleItemSink.class:0.9.3.126]
        at logisticspipes.modules.ModuleItemSink.getSpecificInterests(ModuleItemSink.java:52) ~[ModuleItemSink.class:0.9.3.126]
        at logisticspipes.pipes.PipeLogisticsChassi.getSpecificInterests(PipeLogisticsChassi.java:646) ~[PipeLogisticsChassi.class:0.9.3.126]
        at logisticspipes.routing.ServerRouter.updateInterests(ServerRouter.java:1314) ~[ServerRouter.class:0.9.3.126]
        at logisticspipes.routing.ServerRouter.update(ServerRouter.java:1163) ~[ServerRouter.class:0.9.3.126]
        at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:412) ~[CoreRoutedPipe.class:0.9.3.126]
        at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145845_h(LogisticsTileGenericPipe.java:202) ~[LogisticsTileGenericPipe.class:0.9.3.126]
        at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[13:22:01] [Server thread/ERROR]: This crash report has been saved to: /home/games/mc-server/ftb/ftb-infinity-evolved-skyblock-1.7.10-1.2.0/./crash-reports/crash-2017-05-02_13.22.01-server.txt
[13:22:01] [Server thread/INFO]: Stopping server
```

**Comment by chaos234** [comment]
What ever happened but it's not the fuzzy cards fault.
The NullPointerException, which was thrown, was triggerd by the ItemSink Module.

You can use MCEdit and delete the pipe which causes this problem and then reload the world and try that again, what you have builded. Don't forgett to setup the ItemSink Module correctly if needed :)

**Comment by bziemons** [comment]
The 16 fuzzy upgrades are not the problem. I am fixing this issue right now. Will be in final 0.9.3 release.

**Comment by bziemons** [comment]
This was fixed months ago and is in the latest release. Please **ALWAYS** include the LP version in your bug reports.
