### ISSUE TITLE
A Turtle using an Sign Creator causes an NPE on the Server

### ISSUE THREAD

**Issue by davboecki** [RS485/LogisticsPipes#1099]
No idea if we can fix this in a generic way or specificly for CC, but even then it should probably be fixed.

```
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NullPointerException
        at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$4.selectNetworks(FMLOutboundHandler.java:109) ~[FMLOutboundHandler$OutboundTarget$4.class:?]
        at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:626) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:878) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:229) ~[AbstractChannel.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195) ~[EmbeddedChannel.class:?]
        at logisticspipes.proxy.MainProxy.sendPacketToPlayer(MainProxy.java:155) ~[MainProxy.class:0.9.3.local]
        at logisticspipes.pipes.basic.CoreRoutedPipe.sendSignData(CoreRoutedPipe.java:1708) ~[CoreRoutedPipe.class:0.9.3.local]
        at logisticspipes.pipes.basic.CoreRoutedPipe.addPipeSign(CoreRoutedPipe.java:1686) ~[CoreRoutedPipe.class:0.9.3.local]
        at logisticspipes.pipes.signs.CraftingPipeSign.addSignTo(CraftingPipeSign.java:53) ~[CraftingPipeSign.class:0.9.3.local]
        at logisticspipes.items.ItemPipeSignCreator.onItemUseFirst(ItemPipeSignCreator.java:83) ~[ItemPipeSignCreator.class:0.9.3.local]
        at dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.deployOnBlock(TurtlePlaceCommand.java:339) ~[TurtlePlaceCommand.class:?]
        at dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.deploy(TurtlePlaceCommand.java:122) ~[TurtlePlaceCommand.class:?]
        at dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.execute(TurtlePlaceCommand.java:71) ~[TurtlePlaceCommand.class:?]
        at dan200.computercraft.shared.turtle.core.TurtleBrain.updateCommands(TurtleBrain.java:995) ~[TurtleBrain.class:?]
        at dan200.computercraft.shared.turtle.core.TurtleBrain.update(TurtleBrain.java:183) ~[TurtleBrain.class:?]
        at dan200.computercraft.shared.turtle.blocks.TileTurtle.func_145845_h(TileTurtle.java:278) ~[TileTurtle.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
        ... 4 more

```

**Comment by davboecki** [comment]
Fixed by: https://github.com/RS485/LogisticsPipes/commit/9e9f97a9af89fd2591311e0f78e6959488221b98
