### ISSUE TITLE
Exception loading blockstate for the variant

### ISSUE THREAD

**Issue by bziemons** [RS485/LogisticsPipes#1129]
Error when starting MC

```
[15:06:20] [main/ERROR] [FML]: Exception loading blockstate for the variant logisticspipes:tile.logisticsblockgenericsubmultiblock#normal: 
java.lang.Exception: Could not load model definition for variant logisticspipes:tile.logisticsblockgenericsubmultiblock
    at net.minecraftforge.client.model.ModelLoader.getModelBlockDefinition(ModelLoader.java:266) ~[ModelLoader.class:?]
    at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:121) ~[ModelBakery.class:?]
    at net.minecraftforge.client.model.ModelLoader.loadBlocks(ModelLoader.java:221) ~[ModelLoader.class:?]
    at net.minecraftforge.client.model.ModelLoader.setupModelRegistry(ModelLoader.java:159) ~[ModelLoader.class:?]
    at net.minecraft.client.renderer.block.model.ModelManager.onResourceManagerReload(ModelManager.java:28) [ModelManager.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121) [SimpleReloadableResourceManager.class:?]
    at net.minecraft.client.Minecraft.init(Minecraft.java:559) [Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:421) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152-release]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152-release]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152-release]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152-release]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152-release]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152-release]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152-release]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152-release]
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
    at GradleStart.main(GradleStart.java:25) [start/:?]
Caused by: java.lang.RuntimeException: Encountered an exception when loading model definition of model logisticspipes:blockstates/tile.logisticsblockgenericsubmultiblock.json
    at net.minecraft.client.renderer.block.model.ModelBakery.loadMultipartMBD(ModelBakery.java:228) ~[ModelBakery.class:?]
    at net.minecraft.client.renderer.block.model.ModelBakery.getModelBlockDefinition(ModelBakery.java:208) ~[ModelBakery.class:?]
    at net.minecraftforge.client.model.ModelLoader.getModelBlockDefinition(ModelLoader.java:262) ~[ModelLoader.class:?]
    ... 20 more
Caused by: java.io.FileNotFoundException: logisticspipes:blockstates/tile.logisticsblockgenericsubmultiblock.json
    at net.minecraft.client.resources.FallbackResourceManager.getAllResources(FallbackResourceManager.java:104) ~[FallbackResourceManager.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.getAllResources(SimpleReloadableResourceManager.java:79) ~[SimpleReloadableResourceManager.class:?]
    at net.minecraft.client.renderer.block.model.ModelBakery.loadMultipartMBD(ModelBakery.java:221) ~[ModelBakery.class:?]
    at net.minecraft.client.renderer.block.model.ModelBakery.getModelBlockDefinition(ModelBakery.java:208) ~[ModelBakery.class:?]
    at net.minecraftforge.client.model.ModelLoader.getModelBlockDefinition(ModelLoader.java:262) ~[ModelLoader.class:?]
    ... 20 more
```

**Comment by ALongStringOfNumbers** [comment]
Sorry to necro an old issue, but I figured I would update this one with a few more exceptions instead of making a new issue.
This was done with Logistics Pipes: 0.10.3.88 on Forge: 14.23.5.2847

Here is the snippet of Log with the errors: [Snippet](https://gist.github.com/ALongStringOfNumbers/bff7acd58d66ee1f92a428c5959325a9)

Here is the Full Log: [Log](https://gist.github.com/ALongStringOfNumbers/c0228771d6342b347a742d04ee527224)

**Comment by bziemons** [comment]
> Sorry to necro an old issue

no worries. As long as an issue is still open it's probably not solved. So far we have been good at ignoring these errors and I am not sure if this will get fixed. I do not plan to touch the models in 1.12 since my priorities for LP are elsewhere
