### ISSUE TITLE
Strange Interaction with the Request Table and Astral Sorcery

### ISSUE THREAD

**Issue by Shortoz** [RS485/LogisticsPipes#1190]
When trying to craft items with the Logistics Request Table when Astral Sorcery is installed, the output of the craft will disappear when removed from the Table's inventory. The console also outputs this error:

```
09:47:09	game		[14:47:09] [Server thread/ERROR] [FML]: Exception caught during firing event hellfirepvp.astralsorcery.common.event.AttributeEvent$PostProcessVanilla@15e9a95d:
09:47:09	game		java.lang.IllegalStateException: Called getProgress on neither server or client - what are you?
09:47:09	game		at hellfirepvp.astralsorcery.common.data.research.ResearchManager.getProgress(ResearchManager.java:86) ~[ResearchManager.class:?]
09:47:09	game		at hellfirepvp.astralsorcery.common.integrations.mods.thaumcraft.perks.key.KeyEnergyShield.on(KeyEnergyShield.java:41) ~[KeyEnergyShield.class:?]
09:47:09	game		at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_450_KeyEnergyShield_on_PostProcessVanilla.invoke(.dynamic) ~[?:?]
09:47:09	game		at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
09:47:09	game		at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
09:47:09	game		at hellfirepvp.astralsorcery.common.event.AttributeEvent.postProcessVanilla(AttributeEvent.java:137) ~[AttributeEvent.class:?]
09:47:09	game		at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111129_g(SourceFile:200) ~[wh.class:?]
09:47:09	game		at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111126_e(SourceFile:176) ~[wh.class:?]
09:47:09	game		at net.minecraft.entity.EntityLivingBase.func_110138_aP(EntityLivingBase.java:1453) ~[vp.class:?]
09:47:09	game		at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:166) ~[vp.class:?]
09:47:09	game		at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:157) ~[aed.class:?]
09:47:09	game		at logisticspipes.blocks.crafting.FakePlayer.<init>(FakePlayer.java:14) ~[FakePlayer.class:0.10.1.109]
09:47:09	game		at logisticspipes.proxy.MainProxy.getFakePlayer(MainProxy.java:269) ~[MainProxy.class:0.10.1.109]
09:47:09	game		at logisticspipes.pipes.PipeBlockRequestTable.getOutput(PipeBlockRequestTable.java:432) ~[PipeBlockRequestTable.class:0.10.1.109]
09:47:09	game		at logisticspipes.pipes.PipeBlockRequestTable.getResultForClick(PipeBlockRequestTable.java:472) ~[PipeBlockRequestTable.class:0.10.1.109]
09:47:09	game		at logisticspipes.network.GuiHandler.lambda$getServerGuiElement$1(GuiHandler.java:238) ~[GuiHandler.class:0.10.1.109]
09:47:09	game		at logisticspipes.utils.gui.HandelableSlot.getProvidedStack(HandelableSlot.java:25) [HandelableSlot.class:0.10.1.109]
09:47:09	game		at logisticspipes.utils.gui.DummyContainer.func_184996_a(DummyContainer.java:593) [DummyContainer.class:0.10.1.109]
09:47:09	game		at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1160) [pa.class:?]
09:47:09	game		at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) [lf.class:?]
09:47:09	game		at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) [lf.class:?]
09:47:09	game		at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
09:47:09	game		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
09:47:09	game		at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
09:47:09	game		at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
09:47:09	game		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
09:47:09	game		at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
09:47:09	game		at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
09:47:09	game		at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
09:47:09	game		at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
09:47:09	game		[14:47:09] [Server thread/ERROR] [FML]: Index: 1 Listeners:
09:47:09	game		[14:47:09] [Server thread/ERROR] [FML]: 0: NORMAL
09:47:09	game		[14:47:09] [Server thread/ERROR] [FML]: 1: ASM: hellfirepvp.astralsorcery.common.integrations.mods.thaumcraft.perks.key.KeyEnergyShield@7060c3b4 on(Lhellfirepvp/astralsorcery/common/event/AttributeEvent$PostProcessVanilla;)V
09:47:09	game		[14:47:09] [Server thread/ERROR] [FML]: 2: ASM: hellfirepvp.astralsorcery.common.constellation.perk.attribute.AttributeTypeLimiter@3b6dafda onProcess(Lhellfirepvp/astralsorcery/common/event/AttributeEvent$PostProcessVanilla;)V
09:47:09	game		[14:47:09] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
09:47:09	game		java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Called getProgress on neither server or client - what are you?
09:47:09	game		at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_74]
09:47:09	game		at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_74]
09:47:09	game		at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
09:47:09	game		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
09:47:09	game		at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
09:47:09	game		at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
09:47:09	game		at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
09:47:09	game		at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
09:47:09	game		Caused by: java.lang.IllegalStateException: Called getProgress on neither server or client - what are you?
09:47:09	game		at hellfirepvp.astralsorcery.common.data.research.ResearchManager.getProgress(ResearchManager.java:86) ~[ResearchManager.class:?]
09:47:09	game		at hellfirepvp.astralsorcery.common.integrations.mods.thaumcraft.perks.key.KeyEnergyShield.on(KeyEnergyShield.java:41) ~[KeyEnergyShield.class:?]
09:47:09	game		at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_450_KeyEnergyShield_on_PostProcessVanilla.invoke(.dynamic) ~[?:?]
09:47:09	game		at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
09:47:09	game		at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
09:47:09	game		at hellfirepvp.astralsorcery.common.event.AttributeEvent.postProcessVanilla(AttributeEvent.java:137) ~[AttributeEvent.class:?]
09:47:09	game		at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111129_g(SourceFile:200) ~[wh.class:?]
09:47:09	game		at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111126_e(SourceFile:176) ~[wh.class:?]
09:47:09	game		at net.minecraft.entity.EntityLivingBase.func_110138_aP(EntityLivingBase.java:1453) ~[vp.class:?]
09:47:09	game		at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:166) ~[vp.class:?]
09:47:09	game		at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:157) ~[aed.class:?]
09:47:09	game		at logisticspipes.blocks.crafting.FakePlayer.<init>(FakePlayer.java:14) ~[FakePlayer.class:0.10.1.109]
09:47:09	game		at logisticspipes.proxy.MainProxy.getFakePlayer(MainProxy.java:269) ~[MainProxy.class:0.10.1.109]
09:47:09	game		at logisticspipes.pipes.PipeBlockRequestTable.getOutput(PipeBlockRequestTable.java:432) ~[PipeBlockRequestTable.class:0.10.1.109]
09:47:09	game		at logisticspipes.pipes.PipeBlockRequestTable.getResultForClick(PipeBlockRequestTable.java:472) ~[PipeBlockRequestTable.class:0.10.1.109]
09:47:09	game		at logisticspipes.network.GuiHandler.lambda$getServerGuiElement$1(GuiHandler.java:238) ~[GuiHandler.class:0.10.1.109]
09:47:09	game		at logisticspipes.utils.gui.HandelableSlot.getProvidedStack(HandelableSlot.java:25) ~[HandelableSlot.class:0.10.1.109]
09:47:09	game		at logisticspipes.utils.gui.DummyContainer.func_184996_a(DummyContainer.java:593) ~[DummyContainer.class:0.10.1.109]
09:47:09	game		at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1160) ~[pa.class:?]
09:47:09	game		at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
09:47:09	game		at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
09:47:09	game		at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
09:47:09	game		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_74]
09:47:09	game		at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_74]
09:47:09	game		at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
09:47:09	game		... 5 more
```

**Comment by davboecki** [comment]
Please test with the newest build.

See: #1197

**Comment by Shortoz** [comment]
The newest build seems to have fixed the issue. Thanks!
