### ISSUE TITLE
crasch client when log a serwer

### ISSUE THREAD

**Issue by villain79** [RS485/LogisticsPipes#121]
this issue too dev build :)

this is some itemk in eq, the player profile will delete all the work, Player can not determine what is in eq;/

---- Minecraft Crash Report ----
// Why did you do that?

Time: 05.07.13 19:46
Description: Exception in world tick

java.lang.NullPointerException
at logisticspipes.network.abstractpackets.CoordinatesPacket.getTile(CoordinatesPacket.java:65)
at logisticspipes.network.abstractpackets.CoordinatesPacket.getPipe(CoordinatesPacket.java:76)
at logisticspipes.network.packets.cpipe.CPipeSatelliteImportBack.processPacket(CPipeSatelliteImportBack.java:84)
at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:94)
at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:84)
at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:84)
at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1571)
at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:59)
at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:461)
at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:266)
at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:94)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1862)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:835)
at net.minecraft.client.Minecraft.run(Minecraft.java:760)
at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at logisticspipes.network.abstractpackets.CoordinatesPacket.getTile(CoordinatesPacket.java:65)
at logisticspipes.network.abstractpackets.CoordinatesPacket.getPipe(CoordinatesPacket.java:76)
at logisticspipes.network.packets.cpipe.CPipeSatelliteImportBack.processPacket(CPipeSatelliteImportBack.java:84)
at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:94)
at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:84)
at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:84)
at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1571)
at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:59)
at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:461)
at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:266)

-- Affected level --

**Comment by ArtForz** [comment]
No idea how that happened, but as far as I can tell 359487bf should've fixed it.
