### ISSUE TITLE
Logistics Pipes crash 1.12

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#1216]
```
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: java.lang.UnsupportedOperationException: This LP version isn't compatible with the installed TD version.
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at logisticspipes.asm.td.ClassTravelingItemHandler.handleTravelingItemClass(ClassTravelingItemHandler.java:40)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at logisticspipes.asm.LogisticsClassTransformer.applyLPTransforms(LogisticsClassTransformer.java:117)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at logisticspipes.asm.LogisticsClassTransformer.transform(LogisticsClassTransformer.java:80)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at java.lang.Class.forName0(Native Method)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at java.lang.Class.forName(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at logisticspipes.LogisticsPipes.forName(LogisticsPipes.java:513)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at logisticspipes.LogisticsPipes.loadClasses(LogisticsPipes.java:504)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at logisticspipes.LogisticsPipes.preInit(LogisticsPipes.java:315)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at java.lang.reflect.Method.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at java.lang.reflect.Method.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at java.lang.reflect.Method.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at java.lang.reflect.Method.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at java.lang.reflect.Method.invoke(Unknown Source)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> [22:15:13] [Client thread/INFO] [STDERR]: [logisticspipes.asm.td.ClassTravelingItemHandler:handleTravelingItemClass:40]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

I have latest version of logistics pipes and Thermal Dynamics

**Comment by DrizzitDudden** [comment]
>This LP version isn't compatible with the installed TD version.

You need to downgrade to [this version of Thermal Dynamics](https://minecraft.curseforge.com/projects/thermal-dynamics/files/2624182) if you want to use the current release of Logistics Pipes. According to their changelog, there won't be any issues in doing so:

>-Minor fixes related to config options.

**Comment by ghost** [comment]
Thank you @DrizzitDudden
