### ISSUE TITLE
List of satelite pipes empty

### ISSUE THREAD

**Issue by randknu** [RS485/LogisticsPipes#1299]
After satelite pipes can be named i noticed that if a satelite pipe becomes disconnected from the network for whatever reason then no pipes will appear in the list of satelite pipes in the crafting pipe. hook it back up and they all show up again.

**Comment by davboecki** [comment]
Yes, this is intended, so you only see the satellite pipes that you can actually use and not the pipes from other players with other systems. 

Why would you need it any differently?

(It was the same for the ID-based system by the way).

**Comment by randknu** [comment]
So if i have a satelite pipe sitting somwhere unconnected i cannot assign other crafting pipes a satelite?
one unconnected pipe screws the list entirely?

**Comment by davboecki** [comment]
Well one unconnected pipe screws up your entire LP system anyway, so if you turn this around it could even help show you that you have a problem on the way from your crafting pipe to the satellite pipe and that you need to fix that first.

**Comment by CXWRTH** [comment]
Getting this occasionally on our server. Not sure how to replicate but once it happens all users get it until we reboot. Server throws following error (does not crash):

`[07/05/2019 06:59:05 pm] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
[07/05/2019 06:59:05 pm]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[07/05/2019 06:59:05 pm]: at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
[07/05/2019 06:59:05 pm]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
[07/05/2019 06:59:05 pm]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
[07/05/2019 06:59:05 pm]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
[07/05/2019 06:59:05 pm]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
[07/05/2019 06:59:05 pm]: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[07/05/2019 06:59:05 pm]: Caused by: java.lang.NullPointerException
[07/05/2019 06:59:05 pm]: at logisticspipes.network.packets.gui.RequestSatellitePipeListPacket.lambda$processPacket$8(RequestSatellitePipeListPacket.java:56) ~[RequestSatellitePipeListPacket.class:0.10.2.183]
[07/05/2019 06:59:05 pm]: at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.WeakHashMap$KeySpliterator.forEachRemaining(WeakHashMap.java:1137) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.WeakHashMap$KeySpliterator.forEachRemaining(WeakHashMap.java:1137) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at logisticspipes.network.packets.gui.RequestSatellitePipeListPacket.processPacket(RequestSatellitePipeListPacket.java:59) ~[RequestSatellitePipeListPacket.class:0.10.2.183]
[07/05/2019 06:59:05 pm]: at logisticspipes.network.PacketInboundHandler.inThreadProcessPacket(PacketInboundHandler.java:36) ~[PacketInboundHandler.class:0.10.2.183]
[07/05/2019 06:59:05 pm]: at logisticspipes.network.PacketInboundHandler.lambda$channelRead0$0(PacketInboundHandler.java:30) ~[PacketInboundHandler.class:0.10.2.183]
[07/05/2019 06:59:05 pm]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
[07/05/2019 06:59:05 pm]: at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
[07/05/2019 06:59:05 pm]: ... 5 more`

**Comment by davboecki** [comment]
@Coxworth If you have a bug or problem please open a new issue. Don't just hijack another one.
