### ISSUE TITLE
crash server mcpc+ latest 1.5.2

### ISSUE THREAD

**Issue by fogss** [RS485/LogisticsPipes#130]
2013-07-22 19:12:03 [SEVERE] java.lang.Throwable
2013-07-22 19:12:03 [SEVERE]    at logisticspipes.pipes.basic.CoreRoutedPipe.getRouter(CoreRoutedPipe.java:616)
2013-07-22 19:12:03 [SEVERE]    at logisticspipes.pipes.basic.CoreRoutedPipe.getRouter(CoreRoutedPipe.java:631)
2013-07-22 19:12:03 [SEVERE]    at logisticspipes.routing.ServerRouter.getRouter(ServerRouter.java:813)
2013-07-22 19:12:03 [SEVERE]    at logisticspipes.routing.ServerRouter.CreateRouteTable(ServerRouter.java:478)
2013-07-22 19:12:03 [SEVERE]    at logisticspipes.routing.ServerRouter$UpdateRouterRunnable.run(ServerRouter.java:101)
2013-07-22 19:12:03 [SEVERE]    at logisticspipes.ticks.RoutingTableUpdateThread.run(RoutingTableUpdateThread.java:36)

2013-07-22 19:13:18 [SEVERE] java.lang.NullPointerException
2013-07-22 19:13:18 [SEVERE]    at logisticspipes.routing.ServerRouter.getCachedPipe(ServerRouter.java:267)
2013-07-22 19:13:18 [SEVERE]    at logisticspipes.routing.ExitRoute.hasActivePipe(ExitRoute.java:87)
2013-07-22 19:13:18 [SEVERE]    at logisticspipes.routing.ServerRouter.CreateRouteTable(ServerRouter.java:489)
2013-07-22 19:13:18 [SEVERE]    at logisticspipes.routing.ServerRouter$UpdateRouterRunnable.run(ServerRouter.java:101)
2013-07-22 19:13:18 [SEVERE]    at logisticspipes.ticks.RoutingTableUpdateThread.run(RoutingTableUpdateThread.java:36)

**Comment by davboecki** [comment]
Please tell un the exact LP version. Inside the current LP code this looks impossible.

**Comment by Nightreaver** [comment]
i'm using latest LP-dev and mcpc+-legacy and its working fine so far.
