### ISSUE TITLE
List of satelite pipes empty

### ISSUE THREAD

**Issue by CXWRTH** [RS485/LogisticsPipes#1325]
On server players will occasionally get a blank list of satellite pipes. We aren't sure what causes this but it takes a server reboot to fix the issue from what we can tell. It does not crash the server but does throw the following error into the server logs:

`[23:56:03] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_212]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at logisticspipes.network.packets.gui.RequestSatellitePipeListPacket.lambda$processPacket$8(RequestSatellitePipeListPacket.java:56) ~[RequestSatellitePipeListPacket.class:0.10.2.183]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
	at java.util.WeakHashMap$KeySpliterator.forEachRemaining(WeakHashMap.java:1137) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_212]
	at logisticspipes.network.packets.gui.RequestSatellitePipeListPacket.processPacket(RequestSatellitePipeListPacket.java:59) ~[RequestSatellitePipeListPacket.class:0.10.2.183]
	at logisticspipes.network.PacketInboundHandler.inThreadProcessPacket(PacketInboundHandler.java:36) ~[PacketInboundHandler.class:0.10.2.183]
	at logisticspipes.network.PacketInboundHandler.lambda$channelRead0$0(PacketInboundHandler.java:30) ~[PacketInboundHandler.class:0.10.2.183]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more`

**Comment by Taris36** [comment]
![2019-07-06_16 48 45](https://user-images.githubusercontent.com/12791942/60761827-2b6c1280-a00e-11e9-909a-76e195c782ba.png)
![2019-07-06_16 48 35](https://user-images.githubusercontent.com/12791942/60761828-2b6c1280-a00e-11e9-8a12-c3346224ce85.png)
one image is the satelite pipe, the other is the crafting pipe attached to it.

**Comment by Taris36** [comment]
crafting modules have the same issue.

**Comment by davboecki** [comment]
What LP version are you using?

**Comment by Taris36** [comment]
we are on Omnifactory version 1.2.1, which uses Logistics Pipes version 0.10.2.183.
