### ISSUE TITLE
Crash after world loading

### ISSUE THREAD

**Issue by CaveJohnson376** [RS485/LogisticsPipes#1379]
minecraft 1.12.2
LP 0.10.2.207
_i think this will be enough_
```java.lang.NullPointerException: Rendering item
	at net.minecraftforge.client.model.PerspectiveMapWrapper.handlePerspective(PerspectiveMapWrapper.java:96)
	at logisticspipes.renderer.newpipe.LogisticsNewPipeModel$1.handlePerspective(LogisticsNewPipeModel.java:217)
	at net.minecraftforge.client.ForgeHooksClient.handleCameraTransforms(ForgeHooksClient.java:427)
	at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.optifine.reflect.Reflector.call(Reflector.java:799)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:508)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:559)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:356)
	at net.minecraft.client.gui.GuiIngame.func_184044_a(GuiIngame.java:1248)
	at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:611)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:346)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:142)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1420)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.PerspectiveMapWrapper.handlePerspective(PerspectiveMapWrapper.java:96)
	at logisticspipes.renderer.newpipe.LogisticsNewPipeModel$1.handlePerspective(LogisticsNewPipeModel.java:217)
	at net.minecraftforge.client.ForgeHooksClient.handleCameraTransforms(ForgeHooksClient.java:427)
	at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.optifine.reflect.Reflector.call(Reflector.java:799)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:508)

-- Item being rendered --
Details:
	Item Type: logisticspipes.items.ItemLogisticsPipe@10742146
	Registry Name: logisticspipes:pipe_transport_basic
	Item Aux: 0
	Item NBT: null
	Item Foil: false

-- Item being rendered --
Details:
	Item Type: logisticspipes.items.ItemLogisticsPipe@10742146
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.handleCaughtException(CCRenderItem.java:188)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:359)
	at net.minecraft.client.gui.GuiIngame.func_184044_a(GuiIngame.java:1248)
	at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:611)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:346)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:142)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1420)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)```

**Comment by EJaxx** [comment]
From the line "Description:" including its
To "-- System Details --" and next 10
Will be more informative

and "[Client thread/INFO]: Loaded CCLProxy" or "[Client thread/INFO]: Loaded CCL DummyProxy" in latest.log

**Comment by CaveJohnson376** [comment]
```-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['CaveJohnson376'/13625, l='MpServer', x=-243.15, y=74.28, z=222.24]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-208,64,256), Chunk: (at 0,4,0 in -13,16; contains blocks -208,0,256 to -193,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 56986 game time, 56986 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
...
        Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1231638208 bytes (1174 MB) / 3915382784 bytes (3734 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xmx6144M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 73 mods loaded, 73 mods active
```
latest.log is changed multiple times after that

**Comment by dblsaiko** [comment]
Try running the game without Optifine, it breaks a lot of mods.

**Comment by CaveJohnson376** [comment]
Okey, thanks :D

**Comment by xJon** [comment]
Reported to https://github.com/xJon/Tekkit-2/issues/32, reproduceable without Optifine: https://mclo.gs/doxwCCa

> when placing pipes, occasionally it crashes, im unable to reliably repeat it, but according to the crash logs basic pipes cause a ticking issue now and then when placing new pipes and causes a crash, sometimes even corrupting the chunk

**Comment by bziemons** [comment]
@xJon I will push a fix for this error shortly, but in general this error seems to be caused by some rendering foo (possibly another mod involved) with code chicken lib. Will need a complete client log for issues where code chicken lib is involved.

**Comment by xJon** [comment]
@bziemons Seems so indeed, later over https://github.com/xJon/Tekkit-2/issues/32 you can see how it seems other mods are involved. If someone can reproduce it I will ask them for a full log.
