### ISSUE TITLE
[crash] trying to use remote orderer on mp server

### ISSUE THREAD

**Issue by ricko1** [RS485/LogisticsPipes#144]
when i go into a mystcraft dimension and right-click my remote linked to a remote pipe in the overworld i crash this is the crash when logging in to my server at home (in the mystcraft dimension) and right clicking:

2013-08-03 20:00:17 [INFO] [Minecraft-Client] Connecting to marcslaptop, 25565
2013-08-03 20:00:19 [FINE] [ForgeModLoader] The server has compatibility level 2
2013-08-03 20:00:19 [FINE] [fml.ItemTracker] The difference set is equal
2013-08-03 20:00:19 [INFO] [STDOUT] Unable to find spawn biome
2013-08-03 20:00:20 [INFO] [Minecraft-Client] [CHAT] §0§0§1§2§3§4§5§6§7§e§fWelcome ricko1, to a server running ForgeEssentials.
2013-08-03 20:00:20 [INFO] [Minecraft-Client] [CHAT] There are 1 players online, and we have had 2 unique players.
2013-08-03 20:00:20 [INFO] [Minecraft-Client] [CHAT] Server time: 20:0. Uptime: 13 min 02 sec.
2013-08-03 20:00:20 [INFO] [GraviGun] [1.5.1] Sending client info to server
2013-08-03 20:00:20 [INFO] [PortalGun] [1.5.2] Sending client info to server
2013-08-03 20:00:20 [INFO] [STDOUT] Loading World: remote/192.168.2.3~25565/world
2013-08-03 20:00:21 [INFO] [Minecraft-Client] [CHAT] §E[Rei's Minimap] 8 Waypoints loaded for marcslaptop
2013-08-03 20:00:21 [INFO] [Minecraft-Client] [CHAT] §E[Rei's Minimap] enabled: cavemapping.
2013-08-03 20:00:21 [INFO] [Minecraft-Client] [CHAT] §E[Rei's Minimap] enabled: entities radar (Player, Animal, Mob, Slime, Squid, Living)
2013-08-03 20:00:22 [INFO] [GraviGun] [1.5.1] Received world props from server.
2013-08-03 20:00:22 [INFO] [PortalGun] [1.5.2] Received world props from server.
2013-08-03 20:00:27 [INFO] [Minecraft-Client] [CHAT] Establishing connection to destination at a cost of 5885 energy
2013-08-03 20:00:30 [INFO] [STDERR] java.lang.NullPointerException
2013-08-03 20:00:30 [INFO] [STDERR]     at logisticspipes.items.RemoteOrderer.func_77659_a(RemoteOrderer.java:84)
2013-08-03 20:00:30 [INFO] [STDERR]     at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:173)
2013-08-03 20:00:30 [INFO] [STDERR]     at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:423)
2013-08-03 20:00:30 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71402_c(Minecraft.java:1343)
2013-08-03 20:00:30 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1800)
2013-08-03 20:00:30 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:835)
2013-08-03 20:00:30 [INFO] [STDERR]     at net.minecraft.client.Minecraft.run(Minecraft.java:760)
2013-08-03 20:00:30 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2013-08-03 20:00:40 [INFO] [Minecraft-Client] Stopping!
2013-08-03 20:00:41 [INFO] [STDOUT] 
2013-08-03 20:00:41 [INFO] [STDOUT] SoundSystem shutting down...
2013-08-03 20:00:41 [INFO] [STDOUT]     Author: Paul Lamb, www.paulscode.com
2013-08-03 20:00:41 [INFO] [STDOUT] 

the server does not crash it gives a disconnect error but it keeps running 
the log of that moment:

2013-08-03 20:00:23 [INFO] [ForgeModLoader] User ricko1 connecting with mods [factorization.misc, BiblioCraft, OmniTools, TwilightForest, BuildCraft|Transport, ICBM|Contraption, ElectricExpansion, NEIAddons|MiscPeripherals, ICBM|Sentry, factorization.dimensionalSlice, Forestry, CoFHWorld, EnderStorage, GraviGun, AdvancedMachines, BinnieCore, IronChest, AtomicScience, BuildCraft|Energy, GregTech_Addon, Railcraft, ImmibisCore, MiscPeripherals, LogisticsPipes|Main, NEIAddons, PortalGun, ChickenChunks, CoFHCore, factorization, ThermalExpansion, TorchLevers, BuildCraft|Silicon, GraviSuite, Mekanism, BuildCraft|Core, IC2NuclearControl, CompactSolars, IC2, MekanismGenerators, ExtrabiomesXL, MekanismTools, ExtraBees, StevesCarts, Mystcraft, ComputerCraft, BuildCraft|Factory, Forge, MFFS, ICBM|Explosion, CCTurtle, ExtraTrees, BuildCraft|Builders]
2013-08-03 20:00:23 [INFO] [Minecraft-Server] ricko1[/192.168.2.1:53155] logged in with entity id 2075 at (253.6149959712426, 70.0, 601.6429721265209)
2013-08-03 20:00:23 [INFO] [STDOUT] Loading Player: ricko1
2013-08-03 20:00:23 [INFO] [STDOUT] Sending serverside check to: ricko1
2013-08-03 20:00:24 [INFO] [GraviGun] [1.5.1] Recieved client info from ricko1
2013-08-03 20:00:24 [INFO] [PortalGun] [1.5.2] Recieved client info from ricko1
2013-08-03 20:00:36 [FINE] [ForgeModLoader] The world 1132d94 (world) may have leaked: seen 70 times.

2013-08-03 20:00:46 [FINE] [ForgeModLoader] Saved ModFlags NBT data file successfully.
2013-08-03 20:00:46 [FINE] [ForgeModLoader] Saved ModFlags NBT data file successfully.
2013-08-03 20:00:46 [FINE] [ForgeModLoader] Saved ModFlags NBT data file successfully.
2013-08-03 20:00:46 [FINE] [ForgeModLoader] Saved ModFlags NBT data file successfully.
2013-08-03 20:00:46 [FINE] [ForgeModLoader] Saved ModFlags NBT data file successfully.
2013-08-03 20:00:46 [FINE] [ForgeModLoader] Saved ModFlags NBT data file successfully.
2013-08-03 20:00:46 [FINE] [ForgeModLoader] Saved ModFlags NBT data file successfully.
2013-08-03 20:00:46 [FINE] [ForgeModLoader] Saved ModFlags NBT data file successfully.
2013-08-03 20:00:46 [FINE] [ForgeModLoader] Saved ModFlags NBT data file successfully.
2013-08-03 20:01:01 [INFO] [STDERR] java.net.SocketException: Connection reset
2013-08-03 20:01:01 [INFO] [STDERR]     at java.net.SocketInputStream.read(Unknown Source)
2013-08-03 20:01:01 [INFO] [STDERR]     at java.net.SocketInputStream.read(Unknown Source)
2013-08-03 20:01:01 [INFO] [STDERR]     at java.io.FilterInputStream.read(Unknown Source)
2013-08-03 20:01:01 [INFO] [STDERR]     at org.bouncycastle.crypto.io.CipherInputStream.nextChunk(Unknown Source)
2013-08-03 20:01:01 [INFO] [STDERR]     at org.bouncycastle.crypto.io.CipherInputStream.read(Unknown Source)
2013-08-03 20:01:01 [INFO] [STDERR]     at java.io.FilterInputStream.read(Unknown Source)
2013-08-03 20:01:01 [INFO] [STDERR]     at net.minecraft.network.packet.Packet.func_73272_a(Packet.java:144)
2013-08-03 20:01:01 [INFO] [STDERR]     at net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:327)
2013-08-03 20:01:01 [INFO] [STDERR]     at net.minecraft.network.TcpConnection.func_74450_c(TcpConnection.java:547)
2013-08-03 20:01:01 [INFO] [STDERR]     at net.minecraft.network.TcpReaderThread.run(SourceFile:94)
2013-08-03 20:01:01 [INFO] [Minecraft-Server] ricko1 lost connection: disconnect.genericReason
2013-08-03 20:01:01 [INFO] [STDOUT] Unloading Player: ricko1
2013-08-03 20:01:26 [FINE] [ForgeModLoader] The world 1132d94 (world) may have leaked: seen 75 times.

some extra info 
forge 1.5.2-7.8.1.738
buildcraft 3.7.2 
logipipes MC1.5.2-0.7.3.dev.626
mystcraft 1.5.2-0.10.5.00
optifine is also installed
the remote pipe is connected to a enderchest and a big network
also the crash doesn't happen in singleplayer
i haven't tested it in the nether or the end because it takes 3-5 minutes to load my client

i hope this is enough info to resolve the issue thanks for maintaining and adding new stuff to this awesome mod

**Comment by bziemons** [comment]
Fixed in build 628
