### ISSUE TITLE
Unable to reload world after exception "Couldn't extract the items already sent from the inventory"

### ISSUE THREAD

**Issue by yves-chevallier** [RS485/LogisticsPipes#1463]
I made some tests and built this setup : 

![image](https://user-images.githubusercontent.com/52489316/82665020-35e9c780-9c33-11ea-8f77-7c1bacc1ad2b.png)

The idea is to process ore automatically when they are put on a dump chest. 

- The chest has a QuickSort module. It will dispatch any routable item to a valid destination
- The hopper has a Passive Supplier Module which requests ore (Iron Ore for instance)
- Then when I put a QuickSort module on the furnace MC crashes. 

It seems logical that this is not an acceptable setup since the Iron ore will circulate indefinitely from the furnace to the hopper. But the issue is that Minecraft crashes with the following exception and it is then not possible to reload the World. 

```
java.lang.UnsupportedOperationException: Couldn't extract the items already sent from the inventory
	at logisticspipes.modules.ModuleQuickSort.tick(ModuleQuickSort.java:230)
	at logisticspipes.modules.ChassiModule.tick(ChassiModule.java:137)
	at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:447)
	at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_73660_a(LogisticsTileGenericPipe.java:213)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bziemons** [comment]
Fixed in 86015c19e41781cd92c80b0a5b72946ca344a450
