### ISSUE TITLE
reported NPE

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#1488]
java.lang.NullPointerException
at logisticspipes.request.RequestManager$workWeightedSorter.compare(RequestManager.java:67)
at logisticspipes.request.RequestManager$workWeightedSorter.compare(RequestManager.java:37)
at java.util.TimSort.countRunAndMakeAscending(TimSort.java:324)
## 

line 67 is          c = o1.destination.getCachedPipe().getLoadFactor() - o2.destination.getCachedPipe().getLoadFactor();

**Comment by bziemons** [comment]
Is this still an issue?

**Comment by AartBluestoke** [comment]
i havnt seen this recently, but i also havn't been playing with a large network.

If no changes have been made to the pipe handling code, then the chunk/pipe can still fall out of cache while the check is going on and NPE.

**Comment by bziemons** [comment]
Okay, so definitely something to check.
