### ISSUE TITLE
Game crash: IllegalStateException

### ISSUE THREAD

**Issue by Water-Moon** [RS485/LogisticsPipes#1541]
With LP version 0.10.3.66 and forge 14.23.5.2854 , this happened while launching Minecraft.

**_This looks really awkward, because in the [source ](https://github.com/RS485/LogisticsPipes/blob/3394b58956b183436cfa51f9050d6249d9e682d6/src/main/kotlin/network/rs485/logisticspipes/module/AsyncModule.kt#L64)there is nullable marker, but... why did this happen anyway?_**

```
java.lang.IllegalStateException: _service must not be null
    at network.rs485.logisticspipes.module.AsyncModule.<init>(AsyncModule.kt:64)
    at network.rs485.logisticspipes.module.AsyncExtractorModule.<init>(AsyncExtractorModule.kt:81)
    at network.rs485.logisticspipes.module.AsyncExtractorModule.<init>(AsyncExtractorModule.kt:81)
    at network.rs485.logisticspipes.module.AsyncExtractorModule.<init>(AsyncExtractorModule.kt)
    at logisticspipes.items.ItemModule$$Lambda$3602/0000000000000000.get(Unknown Source)
    at logisticspipes.items.ItemModule$Module.<init>(ItemModule.java:68)
    at logisticspipes.items.ItemModule$Module.<init>(ItemModule.java:61)
    at logisticspipes.items.ItemModule.registerModule(ItemModule.java:117)
    at logisticspipes.items.ItemModule.registerModule(ItemModule.java:113)
    at logisticspipes.items.ItemModule.loadModules(ItemModule.java:95)
    at logisticspipes.LogisticsPipes.initItems(LogisticsPipes.java:483)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1112_LogisticsPipes_initItems_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Water-Moon** [comment]
oh, wait.... maybe that should be this instead?
__`_service?.pointedItemHandler?.tileEntity`__

**Comment by bziemons** [comment]
> oh, wait.... maybe that should be this instead?
> **`_service?.pointedItemHandler?.tileEntity`**

not exactly, but I should null-check `_service` anyway.

**Comment by Water-Moon** [comment]
Thanks for the speedy fix!!!
