### ISSUE TITLE
Lp to Ae connection makes server crash

### ISSUE THREAD

**Issue by tezzel** [RS485/LogisticsPipes#157]
Getting this when connecting provider pipe on AE interface.

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 8/11/13 12:10 PM
Description: Ticking tile entity

java.lang.NullPointerException
    at logisticspipes.proxy.specialinventoryhandler.SpecialInventoryHandler.getMultipleItems(SpecialInventoryHandler.java:37)
    at logisticspipes.pipes.PipeItemsProviderLogistics.sendStack(PipeItemsProviderLogistics.java:170)
    at logisticspipes.pipes.PipeItemsProviderLogistics.enabledUpdateEntity(PipeItemsProviderLogistics.java:247)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:388)
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:189)
    at net.minecraft.world.World.func_72939_s(World.java:2202)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:546)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:654)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:275)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:573)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:470)
    at net.minecraft.server.ThreadMinecraftServer.run(gp.java:35)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at logisticspipes.proxy.specialinventoryhandler.SpecialInventoryHandler.getMultipleItems(SpecialInventoryHandler.java:37)
    at logisticspipes.pipes.PipeItemsProviderLogistics.sendStack(PipeItemsProviderLogistics.java:170)
    at logisticspipes.pipes.PipeItemsProviderLogistics.enabledUpdateEntity(PipeItemsProviderLogistics.java:247)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:388)
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:189)

-- Tile entity being ticked --
Details:
    Name: logisticspipes.pipes.basic.LogisticsTileGenericPipe // logisticspipes.pipes.basic.LogisticsTileGenericPipe
    Block type: ID #1513 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-293,63,457), Chunk: (at 11,3,9 in -19,28; contains blocks -304,0,448 to -289,255,463), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #1513 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
    Actual block data value: 0 / 0x0 / 0b0000
    LP-Version: 0.7.3.dev.614:false
    Pipe: logisticspipes.pipes.PipeItemsProviderLogisticsMk2
    Transport: logisticspipes.transport.PipeTransportLogistics
    Logic: logisticspipes.logic.LogicProvider
    Router: ServerRouter: {ID: 50, UUID: 4920f0b7-8581-45f5-bd5b-6878c88892aa, AT: (0, -293, 63, 457), Version: 1), Destroied: false}
    stillNeedReplace: false
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2202)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:546)

-- Affected level --
Details:
    Level name: NewBeggining
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 334 Drop: 0
    Level seed: 106613092
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-261,64,356), Chunk: (at 11,4,4 in -17,22; contains blocks -272,0,352 to -257,255,367), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 14209257 game time, 14697522 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 90754 (now: false), thunder time: 42605 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:654)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:275)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:573)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:470)
    at net.minecraft.server.ThreadMinecraftServer.run(gp.java:35)

**Comment by tezzel** [comment]
If i remove providerpipe from Ae interface there is no crash

**Comment by davboecki** [comment]
should be fixed in newer dev versions.
