### ISSUE TITLE
TheOneProbeIntegration Client Crash on Servers [dev branch]

### ISSUE THREAD

**Issue by 123FLO321** [RS485/LogisticsPipes#1613]
When holding shift while looking at an mk 1 chassie (with an Item sink module inside) the client will crash on deticated servers.
Version: master branch: (logisticspipes-0.10.4.2.jar)

```
java.lang.NullPointerException: Unexpected error
	at network.rs485.logisticspipes.compat.TheOneProbeIntegration$LPText.getTranslated(TheOneProbeIntegration.kt:569)
	at network.rs485.logisticspipes.compat.TheOneProbeIntegration$LPText.getWidth(TheOneProbeIntegration.kt:620)
	at mcjty.theoneprobe.apiimpl.elements.ElementVertical.getWidth(ElementVertical.java:63)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderElements(OverlayRenderer.java:393)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDBlock(OverlayRenderer.java:277)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:117)
	at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:123)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1726_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:717)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:173)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1426)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by 123FLO321** [comment]
Seems to be some sort of race condition frequently happening, when using a dedicated servers on the same network

**Comment by EShezzerA** [comment]
I'm new to this crashing stuff but I think I got something similar?:
at the time I was using a supplier pipe into a Coke oven to supply it with Coal and then instantly crashed and had to disable TheOneProbe & (TopAddons which is a OneProbe addon I believe)

[crash-2021-07-19_22.13.15-client.txt](https://github.com/RS485/LogisticsPipes/files/6849768/crash-2021-07-19_22.13.15-client.txt)

**Comment by Creysys** [comment]
I am getting this crash frequently when playing Omnifactory on the dev branch with logisticspipes-0.10.4.5.jar
If you could hotfix the NPE and make a new jenkins build that would be sweet :)

(It even crashes with 0.10.3.114)

**Comment by sbenedict** [comment]
Experience this exact same error message on single player when you sneak-look at a Supplier Logistics Pipe with only an Immersive Engineering Uranium Ingot assigned.

Forge: 1.12.2-14.23.5.2860
LP: 0.10.3.114
TOP: 1.12-1.4.28
IE: 0.12-98
