### ISSUE TITLE
LPTravelingItemServer cast to LPTravelingItemClient Crash [dev branch]

### ISSUE THREAD

**Issue by 123FLO321** [RS485/LogisticsPipes#1616]
Unsure what exactly caused this, but I was testing Fluid Terminus Modules a minute prior to the crash.

```
java.lang.ClassCastException: logisticspipes.transport.LPTravelingItem$LPTravelingItemServer cannot be cast to logisticspipes.transport.LPTravelingItem$LPTravelingItemClient
	at logisticspipes.transport.PipeTransportLogistics.reachedEnd(PipeTransportLogistics.java:647)
	at logisticspipes.transport.PipeTransportLogistics.moveSolids(PipeTransportLogistics.java:670)
	at logisticspipes.transport.PipeTransportLogistics.updateEntity(PipeTransportLogistics.java:133)
	at logisticspipes.transport.PipeFluidTransportLogistics.updateEntity(PipeFluidTransportLogistics.java:176)
	at logisticspipes.pipes.basic.CoreUnroutedPipe.updateEntity(CoreUnroutedPipe.java:119)
	at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:413)
	at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_73660_a(LogisticsTileGenericPipe.java:214)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by 123FLO321** [comment]
potentially related to #1604
