### ISSUE TITLE
Incompatible with Logistics Bridge

### ISSUE THREAD

**Issue by KorewaLidesu** [RS485/LogisticsPipes#1627]
**Repository:** [Logistics Bridge (fork)](https://github.com/KorewaLidesu/LogisticsBridge)
What should I do to resolve this?
[debug.log](https://github.com/RS485/LogisticsPipes/files/6767335/debug.log)
[latest.log](https://github.com/RS485/LogisticsPipes/files/6767336/latest.log)
```
java.util.concurrent.ExecutionException: java.lang.ClassCastException: com.tom.logisticsbridge.part.PartSatelliteBus incompatible with network.rs485.logisticspipes.SatellitePipe
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_292]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_292]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassCastException: com.tom.logisticsbridge.part.PartSatelliteBus incompatible with network.rs485.logisticspipes.SatellitePipe
	at com.tom.logisticsbridge.GuiHandler.getClientGuiElement(GuiHandler.java:97) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:276) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:111) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:50) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.lambda$channelRead0$0(OpenGuiHandler.java:43) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler$$Lambda$583/0x0000000000000000.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 17 more
```

**Comment by bziemons** [comment]
Does your code even compile? Try running `./gradlew build` and look at the output

**Comment by KorewaLidesu** [comment]
Yes, [Github Action](https://github.com/Domaman202/LogisticsBridge/actions/runs/998592612).

**Comment by bziemons** [comment]
https://github.com/KorewaLidesu/LogisticsBridge/runs/2995951863 ?

**Comment by KorewaLidesu** [comment]
Oh, that is wrong branch. `master` branch

**Comment by bziemons** [comment]
oh, but this is the right change: https://github.com/KorewaLidesu/LogisticsBridge/commit/eafdea3de24073320de8b8e7a7b0247a7953f014#diff-67ca2a9e3ebee07ff3b2d4dea49caaf23b715f9d9b210278ad67efb33cf22f4cR46 (not in master branch)

**Comment by KorewaLidesu** [comment]
Yes, I try it but compile fail.

**Comment by KorewaLidesu** [comment]
Rework on code seems to be required. I just gonna take brain out and try to solve this sh*t.
![705569748091404309.gif](https://cdn.discordapp.com/emojis/705569748091404309.gif)

**Comment by KorewaLidesu** [comment]
Faq [5a7e11c](https://github.com/KorewaLidesu/LogisticsBridge/commit/5a7e11c6dd5ec594151e66c7d5a6d12beaad065f)
