### ISSUE TITLE
crash using firewall pipe

### ISSUE THREAD

**Issue by Flow86** [RS485/LogisticsPipes#163]
Version is build 656

tried a getAvailableItems on a request-pipe - got "took to long", then server was completly stuck, after a few sec came this:

```

java.lang.RuntimeException: Why is the router null? (FilteringRouter: {ID: 860, UUID: a8a339a2-ae92-4203-b8b8-c9a9c2ff9110, AT: (0, 119, 37, 128), Version: 206), Destroied: true, EAST})
    at logisticspipes.routing.FilteringRouter.act(FilteringRouter.java:95)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.updateAdjacentAndLsa(ServerRouter.java:728)
    at logisticspipes.routing.ServerRouter.update(ServerRouter.java:738)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:355)
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:198)
    at net.minecraft.world.World.func_72939_s(World.java:2199)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:546)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:652)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:275)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:571)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at logisticspipes.routing.FilteringRouter.act(FilteringRouter.java:95)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:636)
    at logisticspipes.routing.ServerRouter.updateAdjacentAndLsa(ServerRouter.java:728)
    at logisticspipes.routing.ServerRouter.update(ServerRouter.java:738)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:355)
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:198)
```

**Comment by ArtForz** [comment]
I can reproduce this (or something very similar) by quickly breaking and replacing a firewall pipe.

**Comment by Flow86** [comment]
I also get problems with routing updates through firewall pipes, 

routing table size left of firewall pipe: 1989
routing table size right of firewall pipe: 1744

why did it loose approx 200 entries?

**Comment by ruifung** [comment]
Wasn't a similar issue fixed a while back?

**Comment by Flow86** [comment]
yes I thought so, but perhaps this has a different reason

**Comment by davboecki** [comment]
Firewall pipe divides the network.

**Comment by Flow86** [comment]
yes, but the "right" side are only approx 10 logi pipes. a click on a request pipe on either side takes ~ 1min (in that time the complete server hangs)

If i remove the firewall pipe and simply use an some basic pipes and diamond pipe as filter, it works to for me, but not generally

**Comment by ArtForz** [comment]
"RoutingTableSize" shown in the network manager is not the actual # of pipes visible from that pipe, it's the highest router ID of pipes visible from that pipe + 1 ... (new bug ?)

**Comment by davboecki** [comment]
Firewall code has been reworked. Should be fixed by that.
