### ISSUE TITLE
crash 1.12.2 about active suplier and fuzzy crafting

### ISSUE THREAD

**Issue by redfoxrommy** [RS485/LogisticsPipes#1658]
> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_22.6.0_Forge_1.12.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  LogisticsPipesCoreLoader (logisticspipes-0.10.3.114.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.20.6_Forge_1.12.jar)
  Fermion ASM Service (Fermion-1.0.2+hotfix.testless.jar)
  UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 4/24/22 7:46 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: wrong item
	at logisticspipes.request.RequestTreeNode.addPromise(RequestTreeNode.java:188)
	at logisticspipes.request.RequestTreeNode$CraftingSorterNode.addWorkPromisesToTree(RequestTreeNode.java:686)
	at logisticspipes.request.RequestTreeNode.checkCrafting(RequestTreeNode.java:513)
	at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:82)
	at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:57)
	at logisticspipes.request.RequestTree.<init>(RequestTree.java:44)
	at logisticspipes.request.RequestTree.request(RequestTree.java:178)
	at logisticspipes.request.RequestTree.requestPartial(RequestTree.java:207)
	at logisticspipes.modules.ModuleActiveSupplier.createSupplyRequest(ModuleActiveSupplier.java:376)
	at logisticspipes.modules.ModuleActiveSupplier.lambda$tick$3(ModuleActiveSupplier.java:215)
	at logisticspipes.modules.ModuleActiveSupplier$$Lambda$2637/521067095.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at logisticspipes.modules.ModuleActiveSupplier.tick(ModuleActiveSupplier.java:211)
	at logisticspipes.modules.ChassisModule.tick(ChassisModule.java:144)
	at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:467)
	at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_73660_a(LogisticsTileGenericPipe.java:214)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at logisticspipes.request.RequestTreeNode.addPromise(RequestTreeNode.java:188)
	at logisticspipes.request.RequestTreeNode$CraftingSorterNode.addWorkPromisesToTree(RequestTreeNode.java:686)
	at logisticspipes.request.RequestTreeNode.checkCrafting(RequestTreeNode.java:513)
	at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:82)
	at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:57)
	at logisticspipes.request.RequestTree.<init>(RequestTree.java:44)
	at logisticspipes.request.RequestTree.request(RequestTree.java:178)
	at logisticspipes.request.RequestTree.requestPartial(RequestTree.java:207)
	at logisticspipes.modules.ModuleActiveSupplier.createSupplyRequest(ModuleActiveSupplier.java:376)
	at logisticspipes.modules.ModuleActiveSupplier.lambda$tick$3(ModuleActiveSupplier.java:215)
	at logisticspipes.modules.ModuleActiveSupplier$$Lambda$2637/521067095.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at logisticspipes.modules.ModuleActiveSupplier.tick(ModuleActiveSupplier.java:211)
	at logisticspipes.modules.ChassisModule.tick(ChassisModule.java:144)
	at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:467)
	at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_73660_a(LogisticsTileGenericPipe.java:214)

-- Block entity being ticked --
Details:
	Name: logisticspipes:pipe // logisticspipes.pipes.basic.LogisticsTileGenericPipe
	Block type: ID #941 (tile.logisticspipes.pipe // logisticspipes.pipes.basic.LogisticsBlockGenericPipe // logisticspipes:pipe)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-246,69,274), Chunk: (at 10,4,2 in -16,17; contains blocks -256,0,272 to -241,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #941 (tile.logisticspipes.pipe // logisticspipes.pipes.basic.LogisticsBlockGenericPipe // logisticspipes:pipe)
	Actual block data value: 0 / 0x0 / 0b0000
	LP-Version: Logistics Pipes 0.10.3.114, target Forge 1.12.2-14.23.5.2854, vendor https://ci.rs485.network/
	Pipe: logisticspipes.pipes.PipeLogisticsChassisMk2
	Transport: logisticspipes.transport.PipeTransportLogistics
	Router: ServerRouter: {ID: 161, UUID: 0b4c1069-633b-4070-81af-032a6e80ef34, AT: (0, -246, 69, 274), Version: 17), Destroyed: false}
	stillNeedReplace: false
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Angel2646'/180, l='New World', x=-249.14, y=62.00, z=280.99]]
	Chunk stats: ServerChunkCache: 673 Drop: 0
	Level seed: -4983630057876510191
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-232,64,256), Chunk: (at 8,4,0 in -15,16; contains blocks -240,0,256 to -225,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 9343787 game time, 10240419 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 98372 (now: false), thunder time: 24869 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 708926296 bytes (676 MB) / 2829582336 bytes (2698 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                  | Source                                        | Signature                                |
	|:------ |:------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                 | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2859             | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core   | 1.12.2-1.0               | minecraft.jar                                 | None                                     |
	| LCHIJA | xaeroworldmap_core  | 1.12.2-1.0               | minecraft.jar                                 | None                                     |
	| LCHIJA | fermion.asm.service | 1.0.2+hotfix             | minecraft.jar                                 | None                                     |
	| LCHIJA | fermion.asm         | 1.0.2+hotfix             | minecraft.jar                                 | None                                     |
	| LCHIJA | bcrf.asm            | 1.0.0                    | minecraft.jar                                 | None                                     |
	| LCHIJA | bspkrscore          | 7.6.0.1                  | [1.12]bspkrsCore-universal-7.6.0.1.jar        | None                                     |
	| LCHIJA | treecapitator       | 1.43.0                   | [1.12]TreeCapitator-client-1.43.0.jar         | None                                     |
	| LCHIJA | buildcraftlib       | 7.99.24.8                | buildcraft-core-7.99.24.8.jar                 | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.24.8                | buildcraft-core-7.99.24.8.jar                 | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.24.8                | buildcraft-factory-7.99.24.8.jar              | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.24.8                | buildcraft-transport-7.99.24.8.jar            | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.24.8                | buildcraft-silicon-7.99.24.8.jar              | None                                     |
	| LCHIJA | additionalpipes     | 6.0.0.8                  | additionalpipes-6.0.0.8.jar                   | None                                     |
	| LCHIJA | ic2                 | 2.8.170-ex112            | industrialcraft-2-2.8.170-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | advanced_machines   | 61.0.1                   | Advanced Machines-61.0.1.jar                  | None                                     |
	| LCHIJA | forgelin            | 1.8.4                    | Forgelin-1.8.4.jar                            | None                                     |
	| LCHIJA | bcextrapipes        | 1                        | bc-extra-pipes-1.12.2-1.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bdlib               | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                  | None                                     |
	| LCHIJA | bluepower           | 0.3.152                  | BluePower-1.12.2-0.3.152-universal.jar        | None                                     |
	| LCHIJA | bookshelf           | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | buildcraftbuilders  | 7.99.24.8                | buildcraft-builders-7.99.24.8.jar             | None                                     |
	| LCHIJA | crafttweaker        | 4.1.20                   | CraftTweaker2-1.12-4.1.20.674.jar             | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.24.8                | buildcraft-energy-7.99.24.8.jar               | None                                     |
	| LCHIJA | mtlib               | 3.0.7                    | MTLib-3.0.7.jar                               | None                                     |
	| LCHIJA | modtweaker          | 4.0.19                   | modtweaker-4.0.20.5.jar                       | None                                     |
	| LCHIJA | jei                 | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCHIJA | forestry            | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                 | None                                     |
	| LCHIJA | buildcraftcompat    | 7.99.24.8                | buildcraft-compat-7.99.24.8.jar               | None                                     |
	| LCHIJA | fermion             | 1.0.2+hotfix.testless    | Fermion-1.0.2+hotfix.testless.jar             | cc2bf3016f756771230cdc4fac0ec50efdf8d212 |
	| LCHIJA | bcrf                | 1.5.4                    | buildcraft-rf-1.5.4.jar                       | None                                     |
	| LCHIJA | bcfe                | 1.1                      | buildcraftfluxified-1.0.0.jar                 | None                                     |
	| LCHIJA | buildinggadgets     | 2.8.4                    | BuildingGadgets-2.8.4.jar                     | None                                     |
	| LCHIJA | chameleon           | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| LCHIJA | codechickenlib      | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chickenchunks       | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | compactsolars       | 1.12.2-5.0.18.341        | CompactSolars-1.12.2-5.0.18.341-universal.jar | None                                     |
	| LCHIJA | ctgui               | 1.0.0                    | CraftTweaker2-1.12-4.1.20.674.jar             | None                                     |
	| LCHIJA | crafttweakerjei     | 2.0.3                    | CraftTweaker2-1.12-4.1.20.674.jar             | None                                     |
	| LCHIJA | enderstorage        | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ftblib              | 5.4.7.2                  | FTBLib-5.4.7.2.jar                            | None                                     |
	| LCHIJA | shetiphiancore      | 3.5.9                    | shetiphiancore-1.12.0-3.5.9.jar               | None                                     |
	| LCHIJA | endertanks          | 1.6.8                    | endertanks-1.12.0-1.6.8.jar                   | None                                     |
	| LCHIJA | energycontrol       | 1.12.2-0.1.16            | EnergyControl-1.12.2-0.1.16.jar               | None                                     |
	| LCHIJA | energyconverters    | 1.3.7.30                 | energyconverters_1.12.2-1.3.7.30.jar          | None                                     |
	| LCHIJA | zerocore            | 1.12.2-0.1.2.9           | zerocore-1.12.2-0.1.2.9.jar                   | None                                     |
	| LCHIJA | bigreactors         | 1.12.2-0.4.5.68          | ExtremeReactors-1.12.2-0.4.5.68.jar           | None                                     |
	| LCHIJA | gendustry           | 1.6.5.8                  | gendustry-1.6.5.8-mc1.12.2.jar                | None                                     |
	| LCHIJA | giacomosfoundry     | 1.3.13                   | GiacomosFoundry-1.12.2-1.3.13.jar             | None                                     |
	| LCHIJA | gravestone          | 1.3.1                    | GraveStone-1.12.2-Graves-1.3.1.jar            | None                                     |
	| LCHIJA | waila               | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCHIJA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest           | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCHIJA | logisticspipes      | 0.10.3.114               | logisticspipes-0.10.3.114.jar                 | e0c86912b2f7cc0cc646ad57799574aea43dbd45 |
	| LCHIJA | numina              | 1.12.2-1.0.38            | Numina-1.12.2-1.0.38.jar                      | None                                     |
	| LCHIJA | railcraft           | 12.0.0                   | railcraft-12.0.0.jar                          | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | powersuits          | 1.12.2-1.0.46            | ModularPowersuits-1.12.2-1.0.46.jar           | None                                     |
	| LCHIJA | nei                 | 2.4.3                    | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | projecte            | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                   | None                                     |
	| LCHIJA | recipemanipulator   | 1.0                      | RecipeManipulator-1.12-0.3.1.13.jar           | None                                     |
	| LCHIJA | solarflux           | 12.4.11                  | SolarFluxReborn-1.12.2-12.4.11.jar            | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | speedyhoppers       | 1.1.19                   | speedyhoppers-1.1.19.jar                      | None                                     |
	| LCHIJA | storagedrawers      | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar               | None                                     |
	| LCHIJA | wailaharvestability | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar         | None                                     |
	| LCHIJA | wanionlib           | 1.12.2-2.9               | WanionLib-1.12.2-2.9.jar                      | None                                     |
	| LCHIJA | waterstrainer       | 3.3.0                    | WaterStrainer-1.12-3.3.0.jar                  | None                                     |
	| LCHIJA | wopper              | 1.12-r5                  | Wopper-1.12-r5.jar                            | None                                     |
	| LCHIJA | xaerominimap        | 22.6.0                   | Xaeros_Minimap_22.6.0_Forge_1.12.jar          | None                                     |
	| LCHIJA | xaeroworldmap       | 1.20.6                   | XaerosWorldMap_1.20.6_Forge_1.12.jar          | None                                     |
	| LCHIJA | yabba               | 1.1.2.54                 | YABBA-1.1.2.54.jar                            | None                                     |
	| LCHIJA | zettaindustries     | 1.3                      | zettaindustries-1.3-1.12.2-161.jar            | None                                     |
	| LCHIJA | unidict             | 1.12.2-3.0.10            | UniDict-1.12.2-3.0.10.jar                     | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
XaeroMinimapPlugin (Xaeros_Minimap_22.6.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.SaveFormatTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
LogisticsPipesCoreLoader (logisticspipes-0.10.3.114.jar)
  logisticspipes.asm.LogisticsClassTransformer
XaeroWorldMapPlugin (XaerosWorldMap_1.20.6_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
  xaero.map.core.transformer.SaveFormatTransformer
  xaero.map.core.transformer.BiomeColorHelperTransformer
Fermion ASM Service (Fermion-1.0.2+hotfix.testless.jar)
  net.thesilkminer.mc.fermion.asm.common.FermionTransformer
UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
  wanion.unidict.core.UniDictCoreModTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	List of loaded APIs: 
		* apAPI (3) from additionalpipes-6.0.0.8.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.68.jar
		* bluepowerAPI (1.0) from BluePower-1.12.2-0.3.152-universal.jar
		* buildcraftapi_blocks (1.0) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_boards (2.0) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_core (2.2) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_crops (1.1) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_enums (1.0) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_events (2.0) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_facades (1.1) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_filler (5.0) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_fuels (2.0) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_gates (4.1) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_items (1.1) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_library (2.0) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_lists (1.0) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_power (1.3) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_recipes (3.0) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_robotics (3.0) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_statements (1.1) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_tiles (1.2) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_tools (1.0) from buildcraft-core-7.99.24.8.jar
		* buildcraftapi_transport (5.0) from buildcraft-core-7.99.24.8.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.2.387.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.8-mc1.12.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.16.1.301.jar
		* projecteapi (1.12.2-1.2.0) from ProjectE-1.12.2-PE1.4.1.jar
		* railcraft:api_carts (3.0.0) from railcraft-12.0.0.jar
		* railcraft:api_charge (4.0.0) from railcraft-12.0.0.jar
		* railcraft:api_core (3.2.0) from railcraft-12.0.0.jar
		* railcraft:api_crafting (4.0.0) from railcraft-12.0.0.jar
		* railcraft:api_events (2.0.0) from railcraft-12.0.0.jar
		* railcraft:api_fuel (2.0.0) from railcraft-12.0.0.jar
		* railcraft:api_helpers (2.0.0) from railcraft-12.0.0.jar
		* railcraft:api_items (2.4.0) from railcraft-12.0.0.jar
		* railcraft:api_signals (4.0.0) from railcraft-12.0.0.jar
		* railcraft:api_tracks (5.1.1) from railcraft-12.0.0.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.4.2.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.4.2.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.4.2.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.4.2.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.4.2.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.4.2.jar
		* Thaumcraft|API (6.0.2) from railcraft-12.0.0.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.9.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.9.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.9.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.9.jar
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Angel2646'/180, l='New World', x=-249.14, y=62.00, z=280.99]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by redfoxrommy** [comment]
first i set active suplier then i add recipe to fuzzy karafting table. game crash after. every time i try to play game crash after few sec .
any help to rescue my save ?

**Comment by redfoxrommy** [comment]
İ recoverd my world but every time i try to set supling  for ic2 nuclear fuels like quad mox fuel its crash again . 1.12.2
