### ISSUE TITLE
1.6 NPE on Startup with latest buildcraft

### ISSUE THREAD

**Issue by Flow86** [RS485/LogisticsPipes#182]
```
[SEVERE] Encountered an unexpected exception ReportedException
net.minecraft.util.ReportedException: Ticking tile entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:672)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:275)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:585)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:582)
Caused by: java.lang.NullPointerException
    at buildcraft.transport.Pipe.canPipeConnect(Pipe.java:89)
    at logisticspipes.pipes.basic.CoreRoutedPipe.canPipeConnect(CoreRoutedPipe.java:963)
    at logisticspipes.proxy.buildcraft.BuildCraftProxy.checkPipesConnections(BuildCraftProxy.java:112)
    at logisticspipes.routing.PathFinder.getConnectedRoutingPipes(PathFinder.java:204)
at logisticspipes.routing.PathFinder.<init>(PathFinder.java:66)
    at logisticspipes.routing.ServerRouter.recheckAdjacent(ServerRouter.java:310)
    at logisticspipes.routing.ServerRouter.checkAdjacentUpdate(ServerRouter.java:679)
    at logisticspipes.routing.ServerRouter$floodCheckAdjacent.isInteresting(ServerRouter.java:668)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:624)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:629)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:629)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:629)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:629)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:629)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:629)
    at logisticspipes.routing.ServerRouter.act(ServerRouter.java:629)
    at logisticspipes.routing.ServerRouter.updateAdjacentAndLsa(ServerRouter.java:716)
    at logisticspipes.routing.ServerRouter.update(ServerRouter.java:730)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:362)
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:166)
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:552)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666)
```

don't know if its a bc problem or logipipes (since other pipe mods work and only logi not, I think thats a logi problem?)

**Comment by davboecki** [comment]
Is this fixed by the buildcraft commit or are changes on LPs side needed?

**Comment by Flow86** [comment]
I only fixed the "problem" on bc's side (so it doesnt generate a NPE)

the question is: why is the pipe null/invalid at that situation

**Comment by davboecki** [comment]
I suspect, that we try to access a pipe to early in game. The TileGenericPipe was created but the pipe hasn't ticked yet. Your network was probably so big, that LP loaded the chunk with that pipe when it tryed to check that pipe so there was no pime for the pipe to tick.

**Comment by Flow86** [comment]
yes that could be - the network's very large

**Comment by davboecki** [comment]
Maybe we should add an isChunkLoaded check? Opinions on that?

**Comment by Flow86** [comment]
I don't know much about the chunk stuff (yet) - so lets try it?
