### ISSUE TITLE
1.6 another NPE

### ISSUE THREAD

**Issue by Flow86** [RS485/LogisticsPipes#184]
```
2013-09-17 09:42:12 [SEVERE] [ForgeModLoader] A TileEntity logisticspipes.pipes.basic.LogisticsTileGenericPipe(logisticspipes.pipes.basic.LogisticsTileGenericPipe) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
    at logisticspipes.utils.ItemIdentifier.get(ItemIdentifier.java:150)
    at logisticspipes.utils.ItemIdentifierStack.getFromStack(ItemIdentifierStack.java:65)
    at logisticspipes.utils.SimpleInventory.readFromNBT(SimpleInventory.java:172)
    at logisticspipes.pipes.PipeItemsCraftingLogistics.readFromNBT(PipeItemsCraftingLogistics.java:912)
    at logisticspipes.pipes.PipeItemsCraftingLogisticsMk3.readFromNBT(PipeItemsCraftingLogisticsMk3.java:140)
    at buildcraft.transport.TileGenericPipe.func_70307_a(TileGenericPipe.java:118)
    at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_70307_a(LogisticsTileGenericPipe.java:456)
    at net.minecraft.tileentity.TileEntity.func_70317_c(TileEntity.java:152)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:440)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75822_a(AnvilChunkLoader.java:103)
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75815_a(AnvilChunkLoader.java:83)
    at net.minecraft.world.gen.ChunkProviderServer.func_73239_e(ChunkProviderServer.java:182)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:118)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:166)
    at net.minecraft.world.World.func_72964_e(World.java:529)
    at net.minecraft.world.World.func_72796_p(World.java:2861)
    at mods.railcraft.common.util.misc.ChunkManager.ticketsLoaded(ChunkManager.java:191)
    at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:513)
    at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:64)
    at net.minecraftforge.event.ASMEventHandler_1_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
    at net.minecraftforge.event.EventBus.post(EventBus.java:108)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:85)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:107)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:443)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:582)
```

**Comment by davboecki** [comment]
Was that an old world or a new one?

**Comment by Flow86** [comment]
an old world, but loaded the second time

**Comment by davboecki** [comment]
Was the first load completed or the errored one ?

**Comment by Flow86** [comment]
the first load completed (had some other errors like #183) but not that type of error

Ah - could it be that in the crafting pipe an item is set which does not exist anymore? (since ItemIdenfitier seems to fail?)

**Comment by davboecki** [comment]
That's probably what happend.

**Comment by Flow86** [comment]
then a check on null would be sufficient - otherwise it will reset the whole chunk :/

**Comment by davboecki** [comment]
Yea should probably be added. Or we allow the ItemIdentifierStack to return null if the passed ItemStack is null.
