### ISSUE TITLE
1.6 another NPE(2)

### ISSUE THREAD

**Issue by Flow86** [RS485/LogisticsPipes#185]
```
2013-09-18 08:52:13 [SEVERE] [Minecraft-Server] Encountered an unexpected exception ReportedException
net.minecraft.util.ReportedException: Ticking tile entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:672)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:585)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:582)
Caused by: java.lang.NullPointerException
    at logisticspipes.request.RequestTreeNode.checkProvider(RequestTreeNode.java:289)
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:59)
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:42)
    at logisticspipes.request.RequestTree.<init>(RequestTree.java:40)
    at logisticspipes.request.RequestTree.request(RequestTree.java:202)
    at logisticspipes.request.RequestTree.requestPartial(RequestTree.java:228)
    at logisticspipes.pipes.PipeItemsSupplierLogistics.createSupplyRequest(PipeItemsSupplierLogistics.java:276)
    at logisticspipes.pipes.PipeItemsSupplierLogistics.throttledUpdateEntity(PipeItemsSupplierLogistics.java:153)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:368)
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:168)
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:552)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666)
    ... 4 more
```

```
2013-09-18 08:52:13 [INFO] [STDOUT] Details:
2013-09-18 08:52:13 [INFO] [STDOUT]     Name: logisticspipes.pipes.basic.LogisticsTileGenericPipe // logisticspipes.pipes.basic.LogisticsTileGenericPipe
2013-09-18 08:52:13 [INFO] [STDOUT]     Block type: ID #1513 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
2013-09-18 08:52:13 [INFO] [STDOUT]     Block data value: 0 / 0x0 / 0b0000
2013-09-18 08:52:13 [INFO] [STDOUT]     Block location: World: (223,63,505), Chunk: (at 15,3,9 in 13,31; contains blocks 208,0,496 to 223,255,511), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
2013-09-18 08:52:13 [INFO] [STDOUT]     Actual block type: ID #1513 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
2013-09-18 08:52:13 [INFO] [STDOUT]     Actual block data value: 0 / 0x0 / 0b0000
2013-09-18 08:52:13 [INFO] [STDOUT]     LP-Version: 0.7.4.dev.17:false
2013-09-18 08:52:13 [INFO] [STDOUT]     Pipe: logisticspipes.pipes.PipeItemsSupplierLogistics
2013-09-18 08:52:13 [INFO] [STDOUT]     Transport: logisticspipes.transport.PipeTransportLogistics
2013-09-18 08:52:13 [INFO] [STDOUT]     Router: ServerRouter: {ID: 1397, UUID: 50e79ec3-06a1-45d2-a0b5-b1b631801330, AT: (0, 223, 63, 505), Version: 49), Destroied: false}
2013-09-18 08:52:13 [INFO] [STDOUT]     stillNeedReplace: false
2013-09-18 08:52:13 [INFO] [STDOUT] Stacktrace:
2013-09-18 08:52:13 [INFO] [STDOUT]     at net.minecraft.world.World.func_72939_s(World.java:2209)
2013-09-18 08:52:13 [INFO] [STDOUT]     at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:552)
```

**Comment by davboecki** [comment]
Is that bug reproduceable?

**Comment by Flow86** [comment]
yes, got it twice as I died far away, respawned and moved a bit
