### ISSUE TITLE
1.5.2 mac

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#186]
2013-09-20 20:28:07 [INFO] [STDERR] Exception in thread "Immibis Core background task" java.lang.OutOfMemoryError: PermGen space
2013-09-20 20:28:07 [INFO] [STDERR]     at java.util.WeakHashMap$EntrySet.iterator(WeakHashMap.java:911)
2013-09-20 20:28:09 [INFO] [STDERR]     at mods.immibis.core.net.FragmentSequence$1.run(FragmentSequence.java:63)
2013-09-20 20:28:09 [INFO] [STDERR]     at java.util.TimerThread.mainLoop(Timer.java:512)
2013-09-20 20:28:09 [INFO] [STDERR]     at java.util.TimerThread.run(Timer.java:462)
2013-09-20 20:28:09 [INFO] [STDERR] Exception in thread "Minecraft main thread" java.lang.OutOfMemoryError: PermGen space
2013-09-20 20:28:09 [INFO] [STDERR]     at java.lang.ClassLoader.defineClass1(Native Method)
2013-09-20 20:28:09 [INFO] [STDERR]     at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
2013-09-20 20:28:09 [INFO] [STDERR]     at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
2013-09-20 20:28:09 [INFO] [STDERR]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
2013-09-20 20:28:09 [INFO] [STDERR]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
2013-09-20 20:28:09 [INFO] [STDERR]     at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
2013-09-20 20:28:09 [INFO] [STDERR]     at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
2013-09-20 20:28:09 [INFO] [STDERR]     at java.security.AccessController.doPrivileged(Native Method)
2013-09-20 20:28:09 [INFO] [STDERR]     at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
2013-09-20 20:28:09 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:160)
2013-09-20 20:28:09 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
2013-09-20 20:28:09 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
2013-09-20 20:28:09 [INFO] [STDERR]     at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:500)
2013-09-20 20:28:09 [INFO] [STDERR]     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
2013-09-20 20:28:09 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
2013-09-20 20:28:09 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Method.java:597)
2013-09-20 20:28:09 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2013-09-20 20:28:09 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-09-20 20:28:09 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
2013-09-20 20:28:09 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2013-09-20 20:28:09 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2013-09-20 20:28:09 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:192)
2013-09-20 20:28:09 [INFO] [STDERR]     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:172)
2013-09-20 20:28:09 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-09-20 20:28:09 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
2013-09-20 20:28:09 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
2013-09-20 20:28:09 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Method.java:597)
2013-09-20 20:28:09 [INFO] [STDERR]     at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2013-09-20 20:28:09 [INFO] [STDERR]     at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2013-09-20 20:28:09 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
2013-09-20 20:28:09 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2013-09-20 20:28:09 [INFO] [STDERR]     at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2013-09-20 20:29:33 [INFO] [STDERR] Exception in thread "Thread-3" java.lang.OutOfMemoryError: PermGen space
2013-09-20 20:29:34 [INFO] [STDERR] Exception in thread "Thread-1" java.lang.OutOfMemoryError: PermGen space

**Comment by davboecki** [comment]
`Exception in thread "Immibis Core background task" java.lang.OutOfMemoryError: PermGen space`
I don't know why this is here...
But to solve your problem you need more pernGen size. 
Add

```
-XX:PermSize=256m
```

to your java arguments.

**Comment by ghost** [comment]
ohh thanx! :)
realy thanx :D
