### ISSUE TITLE
Server-only startup crash

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#187]
I believe this is an issue with LP, not EasyCrafting. I think you may need some sided-only annotations?  My code is here:

https://github.com/sadris/EasyCrafting/blob/logisticpipes/src/main/java/net/lepko/easycrafting/recipe/handler/LogisticsPipesRecipeHandler.java

```
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/IconRegister
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2521)
    at java.lang.Class.getDeclaredMethod(Class.java:1992)
    at net.lepko.easycrafting.recipe.handler.LogisticsPipesRecipeHandler.<clinit>(LogisticsPipesRecipeHandler.java:26)
    at net.lepko.easycrafting.recipe.RecipeManager.<clinit>(RecipeManager.java:26)
    at net.lepko.easycrafting.ModEasyCrafting.postInit(ModEasyCrafting.java:79)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:540)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:194)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:174)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:105)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:701)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:355)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:141)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:443)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:582)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.IconRegister
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:179)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 37 more
Caused by: java.lang.NullPointerException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at powercrystals.core.asm.PCCASMTransformer.transform(PCCASMTransformer.java:29)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:267)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:165)
    ... 39 more

```

**Comment by ghost** [comment]
The build binary is here: http://sadris.s3.amazonaws.com/EasyCrafting-1.6.2-001.jar

**Comment by davboecki** [comment]
Does that help? https://github.com/RS485/LogisticsPipes-Dev/commit/f5457bc9d804dbd297d81500bb244e7fd9bb8549

**Comment by ghost** [comment]
Now this:

```
cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: moduleIcon
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:149)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:702)
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:355)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:141)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:443)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:582)
Caused by: java.lang.NoSuchFieldError: moduleIcon
        at logisticspipes.items.ItemModule$Module.<init>(ItemModule.java:101)
        at logisticspipes.items.ItemModule$Module.<init>(ItemModule.java:97)
        at logisticspipes.items.ItemModule.registerModule(ItemModule.java:202)
        at logisticspipes.items.ItemModule.loadModules(ItemModule.java:169)
        at logisticspipes.LogisticsPipes.postInit(LogisticsPipes.java:352)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:540)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
        at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)

```

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes-Dev/commit/af7e3c673c60bc95ede51f3d8f11a823058fa825 should fix that.

**Comment by ghost** [comment]
Fixed.
