### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by liamsaliba** [RS485/LogisticsPipes#188]
Running latest version of LP, Buildcraft 4.0.2, CodeChickenCore and Not Enough Items

Running on 1.6, just tested; this happens with just Buildcraft and LP as well.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 24/09/13 3:20 PM
Description: Initializing game

java.lang.RuntimeException: LogisticsPipes could not find its classtransformer. If you are running MC from an IDE make sure to copy the 'LogisticsPipes_dummy.jar' to your mods folder. If you are running MC normal please report this as a bug at 'https://github.com/RS485/LogisticsPipes-Dev/issues'.
    at logisticspipes.LogisticsPipes.<init>(LogisticsPipes.java:138)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:174)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:514)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:194)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:174)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:105)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:509)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:181)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:471)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:806)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at logisticspipes.LogisticsPipes.<init>(LogisticsPipes.java:138)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:174)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:514)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:194)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:174)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:105)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:509)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:181)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:471)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:806)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_17, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 117929392 bytes (112 MB) / 512032768 bytes (488 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.6.884 Minecraft Forge 9.11.0.884 13 mods loaded, 13 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{6.4.6.884} [Forge Mod Loader](minecraftforge-9.11.0.884.jar) Unloaded->Constructed
    Forge{9.11.0.884} [Minecraft Forge](minecraftforge-9.11.0.884.jar) Unloaded->Constructed
    CodeChickenCore{0.9.0.6} [CodeChicken Core](minecraft.jar) Unloaded->Constructed
    NotEnoughItems{1.6.1.5} [Not Enough Items](NotEnoughItems 1.6.1.5.jar) Unloaded->Constructed
    BuildCraft|Core{4.0.2} [BuildCraft](buildcraft-A-4.0.2.jar) Unloaded->Constructed
    BuildCraft|Builders{4.0.2} [BC Builders](buildcraft-A-4.0.2.jar) Unloaded->Constructed
    BuildCraft|Energy{4.0.2} [BC Energy](buildcraft-A-4.0.2.jar) Unloaded->Constructed
    BuildCraft|Factory{4.0.2} [BC Factory](buildcraft-A-4.0.2.jar) Unloaded->Constructed
    BuildCraft|Transport{4.0.2} [BC Transport](buildcraft-A-4.0.2.jar) Unloaded->Constructed
    BuildCraft|Silicon{4.0.2} [BC Silicon](buildcraft-A-4.0.2.jar) Unloaded->Constructed
    IronChest{5.4.1.585} [Iron Chest](ironchest-universal-1.6.4-5.4.1.585.zip) Unloaded->Constructed
    LogisticsPipes|Main{0.7.4.dev.31} [Logistics Pipes](LogisticsPipes-MC1.6.2-0.7.4.dev.31.jar) Unloaded->Errored
    Launched Version: 1.6.4-Forge9.11.0.884
    LWJGL: 2.9.0
    OpenGL: GeForce GTX 670/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by davboecki** [comment]
We need the full fml log please.

**Comment by liamsaliba** [comment]
Just had to remake an instance, if you want as much details as you can.

Running from a folder - not .minecraft with Minecraft Profile Manager

Minecraft Forge 1.6.4 - 884
Buildcraft 4.0.2
Logistics Pipes 1.6.2 dev 31 - 0.7.4   <--- Problem being 1.6.2?  I thought this would be fine because most other mods for 1.6.2 work perfectly fine with 1.6.4

Pastebin - http://pastebin.com/ByVwN9wj

Also, question:  May I put this mod in a private server modpack? Private being key

**Comment by davboecki** [comment]
Just to show what the problem is 
`2013-09-24 16:30:59 [SEVERE] [ForgeModLoader] The coremod logisticspipes.asm.LogisticsPipesCoreLoader is requesting minecraft version 1.6.2 and minecraft is 1.6.4. It will be ignored.`
LP detects the missing coremod parts and stops minecraft.
Need to test the accesstransformer with mc 1.6.4 .
And yes you are allowed to use this mod in a private modpack.

**Comment by liamsaliba** [comment]
Nice, I understand :)

**Comment by liamsaliba** [comment]
Any fix yet?  I've been wanting to put this on my 1.6.4 server for a while :+1:

**Comment by davboecki** [comment]
Currently not. Time is a rare thing currently.

**Comment by AartBluestoke** [comment]
i've got a new full time job, and my main computer is currently back at the
shop under warrenty, so i haven't had any time for lp recently.

On Wed, Sep 25, 2013 at 4:58 PM, davboecki notifications@github.com wrote:

> Currently not. Time is a rare thing currently.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RS485/LogisticsPipes-Dev/issues/188#issuecomment-25065561
> .

## 

“Getting information off the Internet is like taking a drink from a fire
hydrant.”
_– Mitchell Kapor_

**Comment by AartBluestoke** [comment]
that mcversion annotation is there because in the majority of cases mods
die a horrible, horrible death when used against the wrong MC version.

On Wed, Sep 25, 2013 at 5:11 PM, Andrew Hill andy.t.roo@gmail.com wrote:

> i've got a new full time job, and my main computer is currently back at
> the shop under warrenty, so i haven't had any time for lp recently.
> 
> On Wed, Sep 25, 2013 at 4:58 PM, davboecki notifications@github.comwrote:
> 
> > Currently not. Time is a rare thing currently.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/RS485/LogisticsPipes-Dev/issues/188#issuecomment-25065561
> > .
> 
> ## 
> 
> “Getting information off the Internet is like taking a drink from a fire
> hydrant.”
> _– Mitchell Kapor_

## 

“Getting information off the Internet is like taking a drink from a fire
hydrant.”
_– Mitchell Kapor_

**Comment by davboecki** [comment]
And to extend the mc version annotation for mc1.6.4 we need to check the accesstransformer mappings. And by the way fml complains about the missing annotation. So we better just tell it tu run with mc versions from 1.6.2 - 1.6.4 IF the mappings match.

**Comment by liamsaliba** [comment]
Cool, will test on my server with the modpack.  Will post if any issues.
