### ISSUE TITLE
1.6.2 server crash when hooking up industrialcraft power

### ISSUE THREAD

**Issue by alexswan10k** [RS485/LogisticsPipes#191]
I noticed a consistent crash occurring when I tried to hook up an IC2 power source (bat box I believe) to the power junction (copper wires). Server would crash until I deleted the power junction using MCEdit.

IC2 version is industrialcraft-2_1.118.401-lf

Let me know if you need any more info.

---- Minecraft Crash Report ----
// There are four lights!

Time: 29/09/13 20:18
Description: Ticking tile entity

java.lang.AbstractMethodError
    at ic2.core.EnergyNet.getValidReceivers(EnergyNet.java:814)
    at ic2.core.EnergyNet.discover(EnergyNet.java:694)
    at ic2.core.EnergyNet.addTileEntity(EnergyNet.java:222)
    at ic2.core.EnergyNet$EventHandler.onEnergyTileLoad(EnergyNet.java:53)
    at net.minecraftforge.event.ASMEventHandler_21_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
    at net.minecraftforge.event.EventBus.post(EventBus.java:108)
    at logisticspipes.proxy.ic2.IC2Proxy.registerToEneryNet(IC2Proxy.java:206)
    at logisticspipes.blocks.powertile.LogisticsPowerJunctionTileEntity.func_70316_g(LogisticsPowerJunctionTileEntity.java:167)
    at net.minecraft.world.World.func_72939_s(World.java:2208)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:552)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:275)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:585)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:582)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at ic2.core.EnergyNet.getValidReceivers(EnergyNet.java:814)
    at ic2.core.EnergyNet.discover(EnergyNet.java:694)
    at ic2.core.EnergyNet.addTileEntity(EnergyNet.java:222)
    at ic2.core.EnergyNet$EventHandler.onEnergyTileLoad(EnergyNet.java:53)
    at net.minecraftforge.event.ASMEventHandler_21_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
    at net.minecraftforge.event.EventBus.post(EventBus.java:108)
    at logisticspipes.proxy.ic2.IC2Proxy.registerToEneryNet(IC2Proxy.java:206)
    at logisticspipes.blocks.powertile.LogisticsPowerJunctionTileEntity.func_70316_g(LogisticsPowerJunctionTileEntity.java:167)

-- Tile entity being ticked --
Details:
    Name: logisticspipes.blocks.powertile.LogisticsPowerJuntionTileEntity // logisticspipes.blocks.powertile.LogisticsPowerJunctionTileEntity
    Block type: ID #1101 (tile.logisticsSolidBlock // logisticspipes.blocks.LogisticsSolidBlock)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (191,59,281), Chunk: (at 15,3,9 in 11,17; contains blocks 176,0,272 to 191,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #1101 (tile.logisticsSolidBlock // logisticspipes.blocks.LogisticsSolidBlock)
    Actual block data value: 1 / 0x1 / 0b0001
    LP-Version: 0.7.4.dev.34:false
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2208)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:552)

-- Affected level --
Details:
    Level name: world
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 625 Drop: 0
    Level seed: -6722636966366795070
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (152,64,236), Chunk: (at 8,4,12 in 9,14; contains blocks 144,0,224 to 159,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 6915801 game time, 6755851 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 39200 (now: false), thunder time: 149689 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:666)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:275)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:585)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:582)

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_17, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 520566936 bytes (496 MB) / 717684736 bytes (684 MB) up to 3799121920 bytes (3623 MB)
    JVM Flags: 0 total; 
    AABB Pool Size: 4829 (270424 bytes; 0 MB) allocated, 4829 (270424 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 6, tallocated: 62
    FML: MCP v8.04 FML v6.2.60.859 Minecraft Forge 9.10.1.859 18 mods loaded, 18 mods active
    mcp{8.04} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.2.60.859} [Forge Mod Loader](minecraftforge-universal-1.6.2-9.10.1.859.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.10.1.859} [Minecraft Forge](minecraftforge-universal-1.6.2-9.10.1.859.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.9.0.5} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{4.0.1} [BuildCraft](buildcraft-A-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{4.0.1} [BC Builders](buildcraft-A-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{4.0.1} [BC Energy](buildcraft-A-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{4.0.1} [BC Factory](buildcraft-A-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{4.0.1} [BC Transport](buildcraft-A-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{4.0.1} [BC Silicon](buildcraft-A-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft{1.55} [ComputerCraft](ComputerCraft1.55.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CCTurtle{1.55} [ComputerCraft Turtles](ComputerCraft1.55.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{1.118.401-lf} [IndustrialCraft 2](industrialcraft-2_1.118.401-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{2.3.0.0} [Forestry for Minecraft](forestry-A-2.3.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LogisticsPipes|Main{0.7.4.dev.34} [Logistics Pipes](LogisticsPipes-MC1.6.2-0.7.4.dev.34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mystcraft{0.10.6.00} [Mystcraft](mystcraft-uni-1.6.2-0.10.6.00.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Railcraft{8.0.0.0} [Railcraft](Railcraft_1.6.2-8.0.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    StevesCarts{2.0.0.a132} [Steve's Carts 2](StevesCarts2.0.0.a132.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1168 (65408 bytes; 0 MB) allocated, 1168 (65408 bytes; 0 MB) used
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by davboecki** [comment]
LP 1.6.2 is build for the IC2 experimental builds.
