### ISSUE TITLE
Crash when placing Crafting Sign with Crafting Sign Creator

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#209]
Right clicked on a Crafting Pipe with a Crafting Sign Creator. Game crashed with:

```

java.lang.NoSuchFieldError: field_78165_b
    at logisticspipes.renderer.LogisticsRenderPipe.renderSign(LogisticsRenderPipe.java:172)
    at logisticspipes.renderer.LogisticsRenderPipe.renderCraftingPipe(LogisticsRenderPipe.java:156)
    at logisticspipes.renderer.LogisticsRenderPipe.func_76894_a(LogisticsRenderPipe.java:79)
    at net.minecraft.client.renderer.tileentity.TileEntityRenderer.func_76949_a(SourceFile:106)
    at net.minecraft.client.renderer.tileentity.TileEntityRenderer.func_76950_a(SourceFile:98)
    at net.minecraft.client.renderer.RenderGlobal.func_72713_a(RenderGlobal.java:536)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1160)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1006)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:944)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:836)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at logisticspipes.renderer.LogisticsRenderPipe.renderSign(LogisticsRenderPipe.java:172)
    at logisticspipes.renderer.LogisticsRenderPipe.renderCraftingPipe(LogisticsRenderPipe.java:156)
    at logisticspipes.renderer.LogisticsRenderPipe.func_76894_a(LogisticsRenderPipe.java:79)

-- Tile Entity Details --
Details:
    Name: logisticspipes.pipes.basic.LogisticsTileGenericPipe // logisticspipes.pipes.basic.LogisticsTileGenericPipe
    Block type: ID #1513 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-76,58,326), Chunk: (at 4,3,6 in -5,20; contains blocks -80,0,320 to -65,255,335), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #1513 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
    Actual block data value: 0 / 0x0 / 0b0000
    LP-Version: 0.7.4.dev.65:false
    Pipe: logisticspipes.pipes.PipeItemsCraftingLogistics
    Transport: logisticspipes.transport.PipeTransportLogistics
    Router: logisticspipes.routing.ClientRouter@54dd6d93
    stillNeedReplace: false

```

**Comment by ghost** [comment]
Also game is currently unloadable as this exception is thrown immediately upon logging in. More info:

```


[17:49:09 INFO]: Client> 2013-10-31 17:49:09 [INFO] [ForgeModLoader] Forge Mod Loader version 6.4.3.883 for Minecraft 1.6.4 loading
[17:49:09 INFO]: Client> 2013-10-31 17:49:09 [INFO] [ForgeModLoader] Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_40, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre7
[17:49:09 INFO]: Client> 2013-10-31 17:49:09 [INFO] [STDOUT] Loaded 40 rules from AccessTransformer config file fml_at.cfg
[17:49:09 INFO]: Client> 2013-10-31 17:49:09 [INFO] [STDOUT] Loaded 109 rules from AccessTransformer config file forge_at.cfg
[17:49:10 INFO]: Client> 2013-10-31 17:49:10 [INFO] [ForgeModLoader] Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[17:49:10 INFO]: Client> 2013-10-31 17:49:10 [INFO] [ForgeModLoader] Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[17:49:10 INFO]: Client> 2013-10-31 17:49:10 [INFO] [ForgeModLoader] Launching wrapped minecraft {net.minecraft.client.main.Main}
[17:49:11 INFO]: Client> 2013-10-31 17:49:11 [INFO] [Minecraft-Client] Setting user: sadris
[17:49:11 INFO]: Client> 2013-10-31 17:49:11 [INFO] [Minecraft-Client] (Session ID is token:0bd76a7f3cdf47a6a4e741b36fa39a79:e216097b9f3f4683a347a3fb1ca63da1)
[17:49:12 INFO]: Client> 2013-10-31 17:49:12 [INFO] [Minecraft-Client] LWJGL Version: 2.9.0
[17:49:13 INFO]: Client> 2013-10-31 17:49:13 [INFO] [Minecraft-Client] Reloading ResourceManager: Default
[17:49:13 INFO]: Client> 2013-10-31 17:49:13 [INFO] [STDOUT] 
[17:49:13 INFO]: Client> 2013-10-31 17:49:13 [INFO] [STDOUT] Starting up SoundSystem...
[17:49:13 INFO]: Client> 2013-10-31 17:49:13 [INFO] [MinecraftForge] Attempting early MinecraftForge initialization
[17:49:13 INFO]: Client> 2013-10-31 17:49:13 [INFO] [STDOUT] MinecraftForge v9.11.0.883 Initialized
[17:49:13 INFO]: Client> 2013-10-31 17:49:13 [INFO] [ForgeModLoader] MinecraftForge v9.11.0.883 Initialized

```

**Comment by davboecki** [comment]
What BC version do you use?

**Comment by ghost** [comment]
4.1.2

**Comment by ghost** [comment]
Also crashes with Forge 9.11.1.916

**Comment by ghost** [comment]
Still crashes on LP 0.7.4.dev.75 and Forge 6.4.40.945

**Comment by davboecki** [comment]
That is realy strange, do you have any other mod installed, maybe one that changes something with how signs are rendered ?

**Comment by ghost** [comment]
Could be BetterSigns mod, I'll check when I get home.

**Comment by davboecki** [comment]
If it is let us know, maybe there is a way we can fix that incompatibility.

**Comment by ghost** [comment]
The issue is indeed Better Signs Mod: http://www.minecraftforum.net/topic/1837653-164-forge-better-signs-mod-v164b/

**Comment by davboecki** [comment]
Could you retest with build 80. That should add compatibility for BetterSigns Mod. https://github.com/RS485/LogisticsPipes-Dev/commit/e692885b7a4f1d1b0d23829876c1d9a43a30947a

**Comment by ghost** [comment]
Thanks. Works fine now!
