### ISSUE TITLE
Server crash with NPE on QuickSort Module

### ISSUE THREAD

**Issue by Distorti0n** [RS485/LogisticsPipes#215]
Minecraft 1.6.4
Forge - 9.11.1.942
LP - 0.7.4.dev.70
Buildcraft - 4.1.2
AE - rv14-alpha5

When adding new items to sink modules, supplier pipes, etc the server will crash with the below error. The chassis with the QuickSort module is attached to an AE interface. Sometimes all that is required to fix is to restart the server other times the ID of the module item has to be changed to remove it from the world.

I'm not sure if AE rv14 is even supported, would it be better to revert to rv13?

Full Log: http://pastebin.com/ykmffe9U

2013-11-11 19:27:32 [INFO] [STDERR] net.minecraft.util.ReportedException: Ticking tile entity
2013-11-11 19:27:32 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:674)
2013-11-11 19:27:32 [INFO] [STDERR]     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:276)
2013-11-11 19:27:32 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
2013-11-11 19:27:32 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2013-11-11 19:27:32 [INFO] [STDERR]     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
2013-11-11 19:27:32 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2013-11-11 19:27:32 [INFO] [STDERR]     at logisticspipes.modules.ModuleQuickSort.tick(ModuleQuickSort.java:128)
2013-11-11 19:27:32 [INFO] [STDERR]     at logisticspipes.logisticspipes.ChassiModule.tick(ChassiModule.java:115)
2013-11-11 19:27:32 [INFO] [STDERR]     at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:405)
2013-11-11 19:27:32 [INFO] [STDERR]     at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:172)
2013-11-11 19:27:32 [INFO] [STDERR]     at net.minecraft.world.World.func_72939_s(World.java:2209)
2013-11-11 19:27:32 [INFO] [STDERR]     at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
2013-11-11 19:27:32 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)

**Comment by davboecki** [comment]
Not sure what's happening here, but i would say that this is probably a bug in AE. Because when we ask the AE system what it has, and than try to extract that from the AE system we should get a result and not just null.

**Comment by Distorti0n** [comment]
Was just writing to say that reverting to AE rv13c appeared to fix the problem when the test server went down. It appears to be a slightly different error so not sure if its related.

Log: https://www.dropbox.com/s/1u6qibgbvs0bnv9/ForgeModLoader-server-0.log

**Comment by davboecki** [comment]
That's a completey different bug. (https://github.com/RS485/LogisticsPipes-Dev/issues/226) It's a BC 4.2 Incompatibility.

**Comment by Distorti0n** [comment]
Ah OK. I've reverted BC to 4.1.2 and have left everything running for a couple of hours while making a number of changes and additions to the network. I have so far not been able to reproduce the crash so it would appear to indeed  be a AE rv14 issue. As rv14 has essentially been discontinued and rv13 works perfectly well i see no need to keep this issue open unless you wish to do so.

**Comment by davboecki** [comment]
If it works, you can close this because this is definitly not an LP bug then.
