### ISSUE TITLE
I break during installation.

### ISSUE THREAD

**Issue by yghtdnt** [RS485/LogisticsPipes#224]
Version is LogisticsPipes-MC1.6.4-0.7.4.dev.80
When I install this MOD, Minecraft has crashes.

ErrorCode

File name is "LogisticsPipes-MC1.6.4-0.7.4.dev.80.jar"

java.lang.IllegalArgumentException: MALFORMED
    at java.util.zip.ZipCoder.toString(Unknown Source)
    at java.util.zip.ZipFile.getZipEntry(Unknown Source)
    at java.util.zip.ZipFile.access$900(Unknown Source)
    at java.util.zip.ZipFile$1.nextElement(Unknown Source)
    at java.util.zip.ZipFile$1.nextElement(Unknown Source)
    at java.util.jar.JarFile$1.nextElement(Unknown Source)
    at java.util.jar.JarFile$1.nextElement(Unknown Source)
    at logisticspipes.com.google.common.reflect.ClassPath$Scanner.scanJar(ClassPath.java:331)
    at logisticspipes.com.google.common.reflect.ClassPath$Scanner.scanFrom(ClassPath.java:288)
    at logisticspipes.com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:276)
    at logisticspipes.com.google.common.reflect.ClassPath.from(ClassPath.java:85)
    at logisticspipes.network.PacketHandler.intialize(PacketHandler.java:43)
    at logisticspipes.LogisticsPipes.<init>(LogisticsPipes.java:142)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:174)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:518)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:509)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

File name is "LogisticsPipes-MC1.6.4-0.7.4.dev.80.zip"

java.lang.RuntimeException: LogisticsPipes could not find its classtransformer. If you are running MC from an IDE make sure to copy the 'LogisticsPipes_dummy.jar' to your mods folder. If you are running MC normal please report this as a bug at 'https://github.com/RS485/LogisticsPipes-Dev/issues'.
    at logisticspipes.LogisticsPipes.<init>(LogisticsPipes.java:140)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance0(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:174)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:518)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:509)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

Built environment of Minecraft is...
OptifineHD U C6
Forge9.11.1.938
133 install mod
(AppliedEnergistics-Core{rv13.c} [AppliedEnergistics Core](minecraft.jar) Unloaded->Constructed
    CodeChickenCore{0.9.0.6} [CodeChicken Core](minecraft.jar) Unloaded->Constructed
    denLib{3.1.35} [denLib](minecraft.jar) Unloaded->Constructed
    NotEnoughItems{1.6.1.5} [Not Enough Items](NotEnoughItems 1.6.1.5.jar) Unloaded->Constructed
    PowerCrystalsCore{1.1.8} [PowerCrystals Core](PowerCrystalsCore-1.1.8-9.jar) Unloaded->Constructed
    SomniaCore{1.0.3} [SomniaCore](minecraft.jar) Unloaded->Constructed
    bspkrsCore{v4.1(1.6.4)} [bspkrsCore]([1.6.4]bspkrsCorev4.1.zip) Unloaded->Constructed
    suntoglowstone{1.0.0a} [SunToGlowstone](%5B1.6.2%5DSunToGlowstone_Forge v1.0.0a.zip) Unloaded->Constructed
    AdvancedTools{2.0o-Unofficial} [AdvancedTools](%5B1.6.2srg%5DAdvancedTools-Unofficial2.0o.zip) Unloaded->Constructed
    EnchantChanger{1.6j-universal} [EnchantChanger](%5B1.6.2srg-Universal%5DEnchantChanger1.6j.zip) Unloaded->Constructed
    ReverseCraft{3.0.6} [ReverseCraft](%5B1.6.x%5DReverseCraft_v3.0.6.zip.zip) Unloaded->Constructed
    Booster{1.6.2v3} [Booster MOD](%5B1.6srg%5DBooster162v3.zip) Unloaded->Constructed
    DamageIndicatorsMod{2.9.0.9} [Damage Indicators](1.6.4 DamageIndicators v2.9.0.9.zip) Unloaded->Constructed
    ArmorStatusHUD{v1.14(1.6.4)} [ArmorStatusHUD]([1.6.4]ArmorStatusHUDv1.14.zip) Unloaded->Constructed
    mod_bspkrsCore{v4.1(1.6.4)} [bspkrsCore]([1.6.4]bspkrsCorev4.1.zip) Unloaded->Constructed
    mod_ReiMinimap{v3.4_01 [1.6.2]} [mod_ReiMinimap]([1.6.4]ReiMinimap_v3.4_01.zip) Unloaded->Constructed
    StatusEffectHUD{v1.18(1.6.4)} [StatusEffectHUD]([1.6.4]StatusEffectHUDv1.18.zip) Unloaded->Constructed
    BuildCraft|Core{4.1.2} [BuildCraft](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed
    BuildCraft|Factory{4.1.2} [BC Factory](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed
    BuildCraft|Transport{4.1.2} [BC Transport](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed
    BuildCraft|Silicon{4.1.2} [BC Silicon](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed
    APUnofficial{2.5.0} [Additional Pipes](AdditionalPipes2.5.0-BC4.1.2.jar) Unloaded->Constructed
    IC2{2.0.274-experimental} [IndustrialCraft 2](industrialcraft-2_2.0.274-experimental.jar) Unloaded->Constructed
    AdvancedMachines{5.2.3} [IC2 Advanced Machines Addon](AdvancedMachines_1.6.4.zip) Unloaded->Constructed
    AppliedEnergistics{rv13.c} [Applied Energistics](appeng-rv13-c-mc162.jar) Unloaded->Constructed
    ComputerCraft{1.57} [ComputerCraft](ComputerCraft1.57.zip) Unloaded->Constructed
    AEPeripheral{1.0.1.1} [AE Peripheral](aeperipheral-universal-1.6.2-1.0.1.1.zip) Unloaded->Constructed
    arsmagica2{1.0.1} [Ars Magica 2](ArsMagica_1.0.1.zip) Unloaded->Constructed
    AtomicScience{1.0.0} [Atomic Science](Atomic_Science_v1.0.0.145.jar) Unloaded->Constructed
    Backpack{1.18.17} [Backpack](backpack-1.18.17-1.6.2.zip) Unloaded->Constructed
    BuildCraft|Builders{4.1.2} [BC Builders](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed
    BuildCraft|Energy{4.1.2} [BC Energy](buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed
    Additional-Buildcraft-Objects{1.0.6.182} [Additional Buildcraft Objects](buildcraft-Z-additional-buildcraft-objects-1.0.6.182.jar) Unloaded->Constructed
    mod_CameraStudio_VideoRecorder{V1.0} [mod_CameraStudio_VideoRecorder](CameraStudio-VR-Dependencies.zip) Unloaded->Constructed
    mod_CameraStudio{V2.164 (for Minecraft 1.6.4)} [mod_CameraStudio](CameraStudioV2.164%28mc1.6.4%29.zip) Unloaded->Constructed
    kegare.caveworld{1.0.9} [Caveworld](Caveworld_1.6.2-v1.0.9.zip) Unloaded->Constructed
    CoFHCore{2.0.0.b5} [CoFH Core](CoFHCore-2.0.0.b5.jar) Unloaded->Constructed
    CoFHLoot{2.0.0.b5} [CoFH Loot](CoFHCore-2.0.0.b5.jar) Unloaded->Constructed
    CoFHMasquerade{2.0.0.b5} [CoFH Masquerade](CoFHCore-2.0.0.b5.jar) Unloaded->Constructed
    CoFHSocial{2.0.0.b5} [CoFH Social](CoFHCore-2.0.0.b5.jar) Unloaded->Constructed
    CoFHWorld{2.0.0.b5} [CoFH World](CoFHCore-2.0.0.b5.jar) Unloaded->Constructed
    CCTurtle{1.57} [ComputerCraft Turtles](ComputerCraft1.57.zip) Unloaded->Constructed
    DenPipes{2.1.18} [DenPipes](DenPipes-1.6.4-2.1.18.jar) Unloaded->Constructed
    enderhunter{1.0} [Ender Hunter](EnderHunter-universal-1.6.4-1.0.1.1.zip) Unloaded->Constructed
    EnderIO{0.3.3} [Ender IO](EnderIO-1.6.4-0.3.3.18.jar) Unloaded->Constructed
    EnderStorage{1.4.3.4} [EnderStorage](EnderStorage 1.4.3.4.jar) Unloaded->Constructed
    MineFactoryReloaded{1.6.2R2.7.2} [MineFactory Reloaded](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatForestryPre{1.6.2R2.7.2} [MFR Compat: Forestry (part 2)](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    Forestry{2.3.0.6} [Forestry for Minecraft](forestry-A-2.3.0.6.jar) Unloaded->Constructed
    GateCopy{3.1.4} [GateCopy](GateCopy-1.6.4-3.1.4.jar) Unloaded->Constructed
    Mekanism{5.5.7} [Mekanism](Mekanism-v5.5.7.254.jar) Unloaded->Constructed
    MekanismGenerators{5.5.7} [MekanismGenerators](MekanismGenerators-v5.5.7.254.jar) Unloaded->Constructed
    MekanismTools{5.5.7} [MekanismTools](MekanismTools-v5.5.7.254.jar) Unloaded->Constructed
    MFFS{3.4.0} [Modular Force Field System](MFFS_v3.4.0.231.jar) Unloaded->Constructed
    Railcraft{8.1.0.0} [Railcraft](Railcraft_1.6.2-8.1.0.0.jar) Unloaded->Constructed
    gregtech_addon{MC162} [GregTech-Addon](gregtechmod.zip) Unloaded->Constructed
    mod.ymt.cmn.YMTLib{164v1} [YMTLib](YMTLib_164v1.zip) Unloaded->Constructed
    mod.ymt.air.HariboteAirCraft{164v2 cassini} [HariboteAirCraft](HariboteAirCraft_164v2.zip) Unloaded->Constructed
    HopperDuctMod{1.1} [Hopper Ducts](HopperDuctsMod1.1.zip) Unloaded->Constructed
    IC2BackpackHUD{2.83} [IC2 Backpack HUD](IC2 Backpack HUD - v2.83 - MC 1.6.2+ - IC2 1.115.301+.zip) Unloaded->Constructed
    iChunUtil{2.3.0} [iChunUtil](iChunUtil2.3.0.zip) Unloaded->Constructed
    inventorytweaks{1.56} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed
    IronChest{5.4.1.629} [Iron Chest](ironchest-universal-1.6.4-5.4.1.629.zip) Unloaded->Constructed
    Thaumcraft{4.0.2a} [Thaumcraft](Thaumcraft4.0.2a.zip) Unloaded->Constructed
    LogisticsPipes|Main{0.7.4.dev.80} [Logistics Pipes](LogisticsPipes-MC1.6.4-0.7.4.dev.80.jar) Unloaded->Errored
    MCCapesExtra{1.6.4a} [MCCapes Extra](MCCapesExtra_1.6.4a.zip) Unloaded->Constructed
    MFR Compat Forestry Trees{1.0} [MFR Compat Forestry Trees](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MFR Compat Extra Trees{1.0} [MFR Compat Extra Trees](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatAppliedEnergistics{1.6.2R2.7.2} [MFR Compat: Applied Energistics](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatAtum{1.6.2R2.7.2} [MFR Compat: Atum](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatBackTools{1.6.2R2.7.2} [MFR Compat: BackTools](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatBuildCraft{1.6.2R2.7.2} [MFR Compat: BuildCraft](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatChococraft{1.6.2R2.7.2} [MFR Compat: Chococraft](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatExtraBiomes{1.6.2R2.7.2} [MFR Compat: ExtraBiomes](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatForestry{1.6.2R2.7.2} [MFR Compat: Forestry](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatIC2{1.6.2R2.7.2} [MFR Compat: IC2](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatMagicalCrops{1.6.2R2.7.2} [MFR Compat: Magical Crops](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatMystcraft{1.6.2R2.7.2} [MFR Compat: Mystcraft](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatPams{1.6.2R2.7.2} [MFR Compat: Pam's Mods](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatRailcraft{1.6.2R2.7.2} [MFR Compat: Railcraft](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatRP2{1.6.2R2.7.2} [MFR Compat: RP2](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatSufficientBiomes{1.6.2R2.7.2} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatThaumcraft{1.6.2R2.7.2} [MFR Compat: Thaumcraft](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatThermalExpansion{1.6.2R2.7.2} [MFR Compat: Thermal Expansion](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatTwilightForest{1.6.2R2.7.2} [MFR Compat: TwilightForest](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatVanilla{1.6.2R2.7.2} [MFR Compat: Vanilla](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatXyCraft{1.6.2R2.7.2} [MFR Compat: XyCraft](MineFactoryReloaded-2.7.2-143.jar) Unloaded->Constructed
    MiscPeripherals{3.3} [MiscPeripherals](miscperipherals-3.4b2.zip) Unloaded->Constructed
    numina{0.0.1-20} [Numina](Numina-1.6.2-0.0.1-20.jar) Unloaded->Constructed
    powersuits{0.8.0-22} [MachineMuse's Modular Powersuits](ModularPowersuits-1.6.2-0.8.0-22.jar) Unloaded->Constructed
    MoreFurnaces{1.3.5} [More Furnaces](moreFurnaces-1.3.5-universal.zip) Unloaded->Constructed
    MoreInventoryMod{2.0.4} [MoreInventoryMod](MoreInventoryMod - v2.0.4 for 1.6.x.zip) Unloaded->Constructed
    MovableSpawner{1.6.2} [MovableSpawner](MovableSpawner162.zip) Unloaded->Constructed
    MultiPageChest{1.2.4b} [Multi Page Chest](multiPageChest-1.2.4b-universal.zip) Unloaded->Constructed
    NBTRecipeAPI{V1.0.1_Minecraft1.6.2} [NBTRecipeAPI](NBTRecipe_V1.0.1%28MC1.6.4%29.zip) Unloaded->Constructed
    NEIAddons{1.9.3.r47} [NEI Addons](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed
    NEIAddons|AE{1.9.3.r47} [NEI Addons: Applied Energistics](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed
    NEIAddons|CraftingTables{1.9.3.r47} [NEI Addons: Crafting Tables](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed
    NEIAddons|ExtraBees{1.9.3.r47} [NEI Addons: Extra Bees](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed
    NEIAddons|Forestry{1.9.3.r47} [NEI Addons: Forestry](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed
    NEIAddons|MiscPeripherals{1.9.3.r47} [NEI Addons: Misc Peripherals](neiaddons-1.6.2-1.9.3.r47.jar) Unloaded->Constructed
    NEIPlugins{1.1.0.4} [NEI Plugins](NEIPlugins-1.1.0.4.jar) Unloaded->Constructed
    nhwrench{1.0.5} [nhwrench](nhwrench-1.0.5.jar) Unloaded->Constructed
    OpenPeripheral{0.2.1} [OpenPeripheral](OpenPeripheral-0.2.1-preview8.jar) Unloaded->Constructed
    wuppy29_peacefulpack{1.1.6.1} [Peacefulpack](PeacefulPack 1.1.6.2.zip) Unloaded->Constructed
    peatcraft{1.0.2} [Peat Craft](PeatCraft%5B1.6.2_1.0.4%5D.zip) Unloaded->Constructed
    PortalGun{2.0.1} [PortalGun](PortalGun2.0.1.zip) Unloaded->Constructed
    PowerConverters{1.6.4R2.3.2B1} [Power Converters](PowerConverters-1.6.4-23.zip) Unloaded->Constructed
    bau5_ProjectBench{1.8.0} [Project Bench](ProjectBench-1.6.2-v1.8.0.jar) Unloaded->Constructed
    ForgeMultipart{1.0.0.191} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.0.191.jar) Unloaded->Constructed
    ProjRed|Core{4.0.5.12} [Project: Red-Core](ProjectRedBase-1.6.4-4.0.5.12.jar) Unloaded->Constructed
    ProjRed|Compatability{4.0.5.12} [ProjectRed-Compatability](ProjectRedCompat-1.6.4-4.0.5.12.jar) Unloaded->Constructed
    ProjRed|Integration{4.0.5.12} [ProjectRed-Integration](ProjectRedIntegration-1.6.4-4.0.5.12.jar) Unloaded->Constructed
    ProjRed|Transmission{4.0.5.12} [ProjectRed-Transmission](ProjectRedIntegration-1.6.4-4.0.5.12.jar) Unloaded->Constructed
    ProjRed|Exploration{4.0.5.12} [ProjectRed-Exploration](ProjectRedWorld-1.6.4-4.0.5.12.jar) Unloaded->Constructed
    ProjRed|Illumination{4.0.5.12} [ProjectRed-Illumination](ProjectRedWorld-1.6.4-4.0.5.12.jar) Unloaded->Constructed
    resonantinduction{0.2.2} [Resonant Induction](Resonant_Induction_v0.2.2.206.jar) Unloaded->Constructed
    SmlSugarCane{1.0.0} [SmlSugarCane](smlSugarcaneMOD%281.0.0 for 1.6.4%29.zip) Unloaded->Constructed
    solidMatter{1.0.2} [Solid Matter+](SolidMatterPlus%5B1.6.2_1.0.2%5D.zip) Unloaded->Constructed
    Somnia{1.0.1} [Somnia](Somnia-Pre2b.jar) Unloaded->Constructed
    TcrsCore{1.6} [TcrsCore](TcrsCore_1_6.jar) Unloaded->Constructed
    TC{4.1.3_001} [Traincraft](traincraft-4.1.3_001.jar) Unloaded->Constructed
    UsefulMillet{V4.0.0Beta2_Minecraft1.6.2 Universal} [UsefulMillet](UsefulMillet_V4.0.0Beta2%28MC1.6.4%29.zip) Unloaded->Constructed
    Waila{1.3.10} [Waila](Waila_1.3.10_1.6.x.zip) Unloaded->Constructed
    WR-CBE|Core{1.4.0.6} [WR-CBE Core](WR-CBE 1.4.0.6.jar) Unloaded->Constructed
    WR-CBE|Addons{1.4.0.6} [WR-CBE Addons](WR-CBE 1.4.0.6.jar) Unloaded->Constructed
    WR-CBE|Logic{1.4.0.6} [WR-CBE Logic](WR-CBE 1.4.0.6.jar) Unloaded->Constructed
    Yami's BB MOD{1.0 for 1.6.4} [Yami's BB MOD](yami BB mod.zip) Unloaded->Constructed
    McMultipart{1.0.0.191} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.0.191.jar) Unloaded->Constructed
    BasicComponents{1.0.0} [Basic Components](Basic_Components_v1.0.0.18.jar) Unloaded->Constructed
    ForgeMicroblock{1.0.0.191} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.0.191.jar) Unloaded->Constructed)

**Comment by AEnterprise** [comment]
it is a error in build 80, downgrade to 79

**Comment by GUIpsp** [comment]
corrupted download
