### ISSUE TITLE
got a NPE on FluidIdentifier.toString

### ISSUE THREAD

**Issue by cybcaoyibo** [RS485/LogisticsPipes#238]
```
java.lang.NullPointerException
    at logisticspipes.utils.FluidIdentifier.toString(FluidIdentifier.java:207)
    at logisticspipes.pipes.PipeFluidSupplierMk2.decreaseRequested(PipeFluidSupplierMk2.java:209)
    at logisticspipes.pipes.PipeFluidSupplierMk2.liquidArrived(PipeFluidSupplierMk2.java:219)
    at logisticspipes.pipes.basic.CoreRoutedPipe.notifyOfItemArival(CoreRoutedPipe.java:1166)
    at logisticspipes.pipes.basic.fluid.FluidRoutedPipe.endReached(FluidRoutedPipe.java:203)
    at buildcraft.transport.PipeTransportItems.moveSolids(PipeTransportItems.java:374)
    at buildcraft.transport.PipeTransportItems.updateEntity(PipeTransportItems.java:326)
    at logisticspipes.transport.PipeTransportLogistics.updateEntity(PipeTransportLogistics.java:95)
    at logisticspipes.transport.PipeFluidTransportLogistics.updateEntity(PipeFluidTransportLogistics.java:153)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:178)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:360)
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:178)
    at net.minecraft.world.World.func_72939_s(World.java:2209)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
```

probably because tag is null

I was supplying a buildcraft tank with lava (8000mb, partial request)

**Comment by GUIpsp** [comment]
Should be fixed by https://github.com/RS485/LogisticsPipes-Dev/commit/b4d8c161a670ae604dd7cb01600b2cd9e0085500.
