### ISSUE TITLE
FZ integration crash (0.90 & 0.91)

### ISSUE THREAD

**Issue by Vic3Dexe** [RS485/LogisticsPipes#239]
Crash on game start, 0.89 working fine except provider modules not providing FZ barrel content (worked in 0.88 !).

2013-12-30 16:08:51 [INFO] [STDOUT] java.lang.RuntimeException: java.lang.ClassNotFoundException: factorization.weird.TileEntityDayBarrel
2013-12-30 16:08:51 [INFO] [STDOUT]     at logisticspipes.proxy.factorization.FactorizationProxy.<init>(FactorizationProxy.java:15)
2013-12-30 16:08:51 [INFO] [STDOUT]     at logisticspipes.proxy.ProxyManager.load(ProxyManager.java:206)
2013-12-30 16:08:51 [INFO] [STDOUT]     at logisticspipes.LogisticsPipes.postInit(LogisticsPipes.java:321)
2013-12-30 16:08:51 [INFO] [STDOUT]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-12-30 16:08:51 [INFO] [STDOUT]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-12-30 16:08:51 [INFO] [STDOUT]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-12-30 16:08:51 [INFO] [STDOUT]     at java.lang.reflect.Method.invoke(Unknown Source)
2013-12-30 16:08:51 [INFO] [STDOUT]     at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
<... skipped...>
2013-12-30 16:08:51 [INFO] [STDOUT] Caused by: java.lang.ClassNotFoundException: factorization.weird.TileEntityDayBarrel
2013-12-30 16:08:51 [INFO] [STDOUT]     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
2013-12-30 16:08:51 [INFO] [STDOUT]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-12-30 16:08:51 [INFO] [STDOUT]     at java.lang.ClassLoader.loadClass(Unknown Source)
2013-12-30 16:08:51 [INFO] [STDOUT]     at java.lang.Class.forName0(Native Method)
2013-12-30 16:08:51 [INFO] [STDOUT]     at java.lang.Class.forName(Unknown Source)
2013-12-30 16:08:51 [INFO] [STDOUT]     at logisticspipes.proxy.factorization.FactorizationProxy.<init>(FactorizationProxy.java:13)
2013-12-30 16:08:51 [INFO] [STDOUT]     ... 38 more

If you need full log - tell it.
Sorry for my english.

**Comment by Vic3Dexe** [comment]
ps FZ 0.8.23

**Comment by davboecki** [comment]
Could you test with FZ 0.8.25

**Comment by Vic3Dexe** [comment]
Seems ok. I'll open a new issue if find something.
