### ISSUE TITLE
Continues spamming of SEVERE entity tracking error

### ISSUE THREAD

**Issue by CowboyJet** [RS485/LogisticsPipes#240]
Accidently created this bug in the old logistics project, recreated it here.
After updating to LogisticsPipes-MC1.6.4-0.7.4.dev.91.jar yesterday, my server log is now being spammed with this error.
I am running latest Buildcraft: buildcraft-A-1.6.4-4.2.1.jar
and MCPC+ : mcpc-plus-1.6.4-R2.1-forge965-B188.jar

2013-12-31 10:10:48 [SEVERE] "Silently" catching entity tracking error.
2013-12-31 10:10:48 [SEVERE] net.minecraft.util.ReportedException: Adding entity to track
2013-12-31 10:10:48 [SEVERE] at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:226)
2013-12-31 10:10:48 [SEVERE] at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:131)
2013-12-31 10:10:48 [SEVERE] at net.minecraft.world.WorldManager.func_72703_a(WorldManager.java:37)
2013-12-31 10:10:48 [SEVERE] at net.minecraft.world.World.func_72923_a(World.java:2020)
2013-12-31 10:10:48 [SEVERE] at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1293)
2013-12-31 10:10:48 [SEVERE] at net.minecraft.world.World.addEntity(World.java:2010)
2013-12-31 10:10:48 [SEVERE] at net.minecraft.world.World.func_72838_d(World.java:1905)
2013-12-31 10:10:48 [SEVERE] at buildcraft.transport.PipeTransportItems.dropItem(PipeTransportItems.java:429)
2013-12-31 10:10:48 [SEVERE] at buildcraft.transport.PipeTransportItems.moveSolids(PipeTransportItems.java:357)
2013-12-31 10:10:48 [SEVERE] at buildcraft.transport.PipeTransportItems.updateEntity(PipeTransportItems.java:326)
2013-12-31 10:10:48 [SEVERE] at logisticspipes.transport.PipeTransportLogistics.updateEntity(PipeTransportLogistics.java:95)
2013-12-31 10:10:48 [SEVERE] at buildcraft.transport.Pipe.updateEntity(Pipe.java:178)
2013-12-31 10:10:48 [SEVERE] at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:360)
2013-12-31 10:10:48 [SEVERE] at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:178)
2013-12-31 10:10:48 [SEVERE] at net.minecraft.world.World.func_72939_s(World.java:2759)
2013-12-31 10:10:48 [SEVERE] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:887)
2013-12-31 10:10:48 [SEVERE] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
2013-12-31 10:10:48 [SEVERE] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781)
2013-12-31 10:10:48 [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:663)
2013-12-31 10:10:48 [SEVERE] at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
2013-12-31 10:10:48 [SEVERE] Caused by: java.lang.IllegalStateException: Entity is already tracked!
2013-12-31 10:10:48 [SEVERE] at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:206)
2013-12-31 10:10:48 [SEVERE] ... 19 more

**Comment by CowboyJet** [comment]
In https://github.com/RS485/LogisticsPipes/issues/779 PROdotes commented :
i can also confirm that without mcpc, just forge 953 on the server... build 92 atm

**Comment by davboecki** [comment]
fixed.
