### ISSUE TITLE
Crash With Provider Modules

### ISSUE THREAD

**Issue by Nexus35** [RS485/LogisticsPipes#26]
With a Provider Module installed into a Mark III Chassis my FTB MindCrack v8.1.1 Server Crashes upon launch. I will provide the Crash Report if Requested. But here is the simple report:

 Ticking tile entity

java.lang.NoClassDefFoundError: gregtechmod/api/IDigitalChest
    at logisticspipes.proxy.specialinventoryhandler.DigitalChestHandler.isType(DigitalChestHandler.java:38)
    at logisticspipes.utils.InventoryUtilFactory.getUtilForInv(InventoryUtilFactory.java:44)
    at logisticspipes.utils.InventoryUtilFactory.getHidingInventoryUtil(InventoryUtilFactory.java:56)
    at logisticspipes.modules.ModuleProvider.getAdaptedUtil(ModuleProvider.java:299)
    at logisticspipes.modules.ModuleProvider.getSpecificInterests(ModuleProvider.java:410)
    at logisticspipes.modules.ModuleProvider.getSpecificInterests(ModuleProvider.java:55)
    at logisticspipes.pipes.PipeLogisticsChassi.getSpecificInterests(PipeLogisticsChassi.java:645)
    at logisticspipes.routing.ServerRouter.updateInterests(ServerRouter.java:818)
    at logisticspipes.routing.ServerRouter.update(ServerRouter.java:731)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:303)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at yc.h(World.java:2153)
    at in.h(WorldServer.java:516)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:680)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.ClassNotFoundException: gregtechmod.api.IDigitalChest
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:185)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 18 more
Caused by: java.lang.NullPointerException

With TickThreading installed the server does NOT Crash upon loading but instead Crashes upon attempting to access a Supplier Pipe Mk II. Here is the Error Report with TickThreading Installed:

03-02 19:17:25 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c logisticspipes.proxy.cc.LogisticsTileGenericPipe_CC logisticspipes.proxy.cc.LogisticsTileGenericPipe_CC@66e5bc8 x,y,z: -2485, 61, -77 at x,y,z:-2485,61,-77
Tick region: rX: -155, rZ: -4, hashCode: -262299:
java.lang.NoClassDefFoundError: gregtechmod/api/IDigitalChest
at logisticspipes.proxy.specialinventoryhandler.DigitalChestHandler.isType(DigitalChestHandler.java:38)
at logisticspipes.utils.InventoryUtilFactory.getUtilForInv(InventoryUtilFactory.java:44)
at logisticspipes.utils.InventoryUtilFactory.getHidingInventoryUtil(InventoryUtilFactory.java:56)
at logisticspipes.modules.ModuleProvider.getAdaptedUtil(ModuleProvider.java:299)
at logisticspipes.modules.ModuleProvider.getSpecificInterests(ModuleProvider.java:410)
at logisticspipes.modules.ModuleProvider.getSpecificInterests(ModuleProvider.java:55)
at logisticspipes.pipes.PipeLogisticsChassi.getSpecificInterests(PipeLogisticsChassi.java:645)
at logisticspipes.routing.ServerRouter.updateInterests(ServerRouter.java:818)
at logisticspipes.routing.ServerRouter.update(ServerRouter.java:731)
at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:303)
at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by ArtForz** [comment]
Update gregtech to >= 2.80

**Comment by Nexus35** [comment]
That fixed it thank you !! I was suspicious that was the cause. Thanks Again!
