### ISSUE TITLE
betterstorage crate gives proxy error

### ISSUE THREAD

**Issue by mvdhoning** [RS485/LogisticsPipes#281]
On trying to combine the betterstorage mod together with logistics pipes i only get to see the first 4 random choosen items from a crate. In de log file i see error on not finding a TileEntityCrate class.

Looking at your source i see you search for:
 net.mcft.copy.betterstorage.block.crate.TileEntityCrate
 But looking at BetterStorage-1.6.4-0.8.0.44.jar i see that that class file does not exist. However there is a net\mcft\copy\betterstorage\tile\crate\TileEntityCrate.class

Hope this helps you fix this bug.

Mods used:
-BetterStorage-1.6.4-0.8.0.44.jar (first tried with BetterStorage-1.6.4-0.8.0.43.jar)
-LogisticsPipes-MC1.6.4-0.7.4.dev.108.jar (first tried with LogisticsPipes-MC1.6.4-0.7.4.dev.106.jar

LOG:
 2014-03-03 14:21:38 [INFO] [STDERR] java.lang.ClassNotFoundException: net.mcft.copy.betterstorage.block.crate.TileEntityCrate
 2014-03-03 14:21:38 [INFO] [STDERR] at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
 2014-03-03 14:21:38 [INFO] [STDERR] at java.lang.ClassLoader.loadClass(Unknown Source)
 2014-03-03 14:21:38 [INFO] [STDERR] at java.lang.ClassLoader.loadClass(Unknown Source)
 2014-03-03 14:21:38 [INFO] [STDERR] at java.lang.Class.forName0(Native Method)
 2014-03-03 14:21:38 [INFO] [STDERR] at java.lang.Class.forName(Unknown Source)
 2014-03-03 14:21:38 [INFO] [STDERR] at logisticspipes.proxy.bs.BetterStorageProxy.(BetterStorageProxy.java:13)
 2014-03-03 14:21:38 [INFO] [STDERR] at logisticspipes.proxy.ProxyManager.load(ProxyManager.java:154)
 2014-03-03 14:21:38 [INFO] [STDERR] at logisticspipes.LogisticsPipes.postInit(LogisticsPipes.java:337)
 2014-03-03 14:21:38 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by mvdhoning** [comment]
additional info:
seems like sorting on better storage is also broken.
now tried the 1.6.4.BetterStorage_0.7.3.38.zip of better storage that came with ftb horizons.
And with that older version of better storage things do seem to work.
So i am not longer sure if this is a bug report for you or for better storage on not being backwards compatible with older versions.

**Comment by davboecki** [comment]
Could you please test if build 112 fixes this.

**Comment by mvdhoning** [comment]
seems to fix it :-)

but the better storage guys/girls seem to do wierd things as they also seem to break inventory tweaks in their latest releases.
