### ISSUE TITLE
Crash with thaumcraft

### ISSUE THREAD

**Issue by selriam** [RS485/LogisticsPipes#292]
2014-03-23 00:20:20 [SERVER] [SEVERE] Encountered an unexpected exception ReportedException
net.minecraft.util.ReportedException: Ticking entity
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:674)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:175)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: java.lang.NullPointerException
at logisticspipes.proxy.cc.CCProxy.getTaget(CCProxy.java:109)
at logisticspipes.proxy.cc.CCProxy.isLuaThread(CCProxy.java:122)
at logisticspipes.proxy.MainProxy.getEffectiveSide(MainProxy.java:51)
at logisticspipes.proxy.MainProxy.getEffectiveSide(MainProxy.java:42)
at logisticspipes.proxy.MainProxy.isClient(MainProxy.java:77)
at logisticspipes.recipes.LPShapedOreRecipe.func_77571_b(LPShapedOreRecipe.java:47)
at thaumcraft.common.lib.ThaumcraftCraftingManager.generateTagsFromCraftingRecipes(ThaumcraftCraftingManager.java:753)
at thaumcraft.common.lib.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:971)
at thaumcraft.common.lib.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:546)
at thaumcraft.common.lib.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:518)
at thaumcraft.common.lib.ThaumcraftCraftingManager.getObjectTags(ThaumcraftCraftingManager.java:304)
at thaumcraft.common.entities.monster.EntityPech.isValued(EntityPech.java:758)
at thaumcraft.common.entities.monster.EntityPech.pickupItem(EntityPech.java:693)
at thaumcraft.common.entities.ai.pech.AIPechItemEntityGoto.func_75246_d(AIPechItemEntityGoto.java:132)
at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:100)
at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:613)
at thaumcraft.common.entities.monster.EntityPech.func_70619_bc(EntityPech.java:667)
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1993)
at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:441)
at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:24)
at thaumcraft.common.entities.monster.EntityPech.func_70636_d(EntityPech.java:221)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1826)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:257)
at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:29)
at thaumcraft.common.entities.monster.EntityPech.func_70071_h_(EntityPech.java:656)
at net.minecraft.world.World.func_72866_a(World.java:2350)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:719)
at net.minecraft.world.World.func_72870_g(World.java:2311)
at net.minecraft.world.World.func_72939_s(World.java:2157)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
... 4 more

pS:sry for that it is not in the correct version posted in fals see need the complete log me know they say to each I hope they can fix the error

it is the version 1.6.4 mc LP v0.7.4.dev.118

**Comment by davboecki** [comment]
like I already sayed in your other issue. LP is not compatible with CC 1.6 Betas.
