### ISSUE TITLE
[Crash] Ordering GUI crash.  Unsure of cause.

### ISSUE THREAD

**Issue by Sakata-MC** [RS485/LogisticsPipes#296]
Access any request pipe/crafter/remote orderer, and this happens.  Not sure what the cause is.
On LP build 117 at the moment.

-- Further testing seemed to show that the "Dynamism Tablet" from Thaumic Tinkerer being stored/provided will cause this.  (maybe not?)
While it temporarily resolved the issue, the crashes have returned.  I'm not at all certain what is causing the issue now.

---- Minecraft Crash Report ----
// Sorry :(

Time: 3/25/14 8:35 AM
Description: Exception in world tick

java.lang.NullPointerException
        at java.io.ByteArrayInputStream.<init>(Unknown Source)
        at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:71)
        at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
        at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
        at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:85)
        at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1651)
        at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
        at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
        at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)
        at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:99)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1930)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
        at net.minecraft.client.main.Main.main(SourceFile:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:214)
        at org.multimc.EntryPoint.listen(EntryPoint.java:139)
        at org.multimc.EntryPoint.main(EntryPoint.java:53)

 -- Head --
Stacktrace:
        at java.io.ByteArrayInputStream.<init>(Unknown Source)
        at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:71)
        at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
        at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
        at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:85)
        at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1651)
        at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
        at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
        at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)

**Comment by Sakata-MC** [comment]
Was working fine with NEI off, then I re-enabled NEI and this happened:
2014-03-25 09:47:40 [INFO] [ForgeModLoader] InvTweaks: cpw.mods.ironchest.ContainerIronChestBase
2014-03-25 09:49:11 [INFO] [STDERR] java.io.IOException: Bad packet id 83
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.network.packet.Packet.func_73272_a(Packet.java:149)
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.network.TcpConnection.func_74447_i(TcpConnection.java:325)
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.network.TcpConnection.func_74450_c(TcpConnection.java:549)
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.network.TcpReaderThread.run(SourceFile:94)
2014-03-25 09:49:11 [INFO] [STDERR] java.lang.Exception: Packet content has been null
2014-03-25 09:49:11 [INFO] [STDERR] at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:69)
2014-03-25 09:49:11 [INFO] [STDERR] at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
2014-03-25 09:49:11 [INFO] [STDERR] at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
2014-03-25 09:49:11 [INFO] [STDERR] at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:85)
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1651)
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:99)
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1930)
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.client.main.Main.main(SourceFile:101)
2014-03-25 09:49:11 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-03-25 09:49:11 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-03-25 09:49:11 [INFO] [STDERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-03-25 09:49:11 [INFO] [STDERR] at java.lang.reflect.Method.invoke(Unknown Source)
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
2014-03-25 09:49:11 [INFO] [STDERR] at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2014-03-25 09:49:11 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-03-25 09:49:11 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-03-25 09:49:11 [INFO] [STDERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-03-25 09:49:11 [INFO] [STDERR] at java.lang.reflect.Method.invoke(Unknown Source)
2014-03-25 09:49:11 [INFO] [STDERR] at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:214)
2014-03-25 09:49:11 [INFO] [STDERR] at org.multimc.EntryPoint.listen(EntryPoint.java:139)
2014-03-25 09:49:11 [INFO] [STDERR] at org.multimc.EntryPoint.main(EntryPoint.java:53)
2014-03-25 09:49:22 [INFO] [STDERR] net.minecraft.util.ReportedException: Exception in world tick
2014-03-25 09:49:22 [INFO] [STDERR] at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1946)
2014-03-25 09:49:22 [INFO] [STDERR] at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
2014-03-25 09:49:22 [INFO] [STDERR] at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
2014-03-25 09:49:22 [INFO] [STDERR] at net.minecraft.client.main.Main.main(SourceFile:101)
2014-03-25 09:49:22 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-03-25 09:49:22 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDERR] at java.lang.reflect.Method.invoke(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDERR] at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
2014-03-25 09:49:22 [INFO] [STDERR] at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2014-03-25 09:49:22 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-03-25 09:49:22 [INFO] [STDERR] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDERR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDERR] at java.lang.reflect.Method.invoke(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDERR] at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:214)
2014-03-25 09:49:22 [INFO] [STDERR] at org.multimc.EntryPoint.listen(EntryPoint.java:139)
2014-03-25 09:49:22 [INFO] [STDERR] at org.multimc.EntryPoint.main(EntryPoint.java:53)
2014-03-25 09:49:22 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2014-03-25 09:49:22 [INFO] [STDERR] at java.io.ByteArrayInputStream.<init>(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDERR] at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:71)
2014-03-25 09:49:22 [INFO] [STDERR] at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
2014-03-25 09:49:22 [INFO] [STDERR] at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
2014-03-25 09:49:22 [INFO] [STDERR] at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:85)
2014-03-25 09:49:22 [INFO] [STDERR] at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1651)
2014-03-25 09:49:22 [INFO] [STDERR] at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
2014-03-25 09:49:22 [INFO] [STDERR] at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
2014-03-25 09:49:22 [INFO] [STDERR] at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)
2014-03-25 09:49:22 [INFO] [STDERR] at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:99)
2014-03-25 09:49:22 [INFO] [STDERR] at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1930)
2014-03-25 09:49:22 [INFO] [STDERR] ... 16 more
2014-03-25 09:49:22 [INFO] [STDOUT] ---- Minecraft Crash Report ----
2014-03-25 09:49:22 [INFO] [STDOUT] // This doesn't make any sense!
2014-03-25 09:49:22 [INFO] [STDOUT]
2014-03-25 09:49:22 [INFO] [STDOUT] Time: 3/25/14 9:49 AM
2014-03-25 09:49:22 [INFO] [STDOUT] Description: Exception in world tick
2014-03-25 09:49:22 [INFO] [STDOUT]
2014-03-25 09:49:22 [INFO] [STDOUT] java.lang.NullPointerException
2014-03-25 09:49:22 [INFO] [STDOUT] at java.io.ByteArrayInputStream.<init>(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDOUT] at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:71)
2014-03-25 09:49:22 [INFO] [STDOUT] at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
2014-03-25 09:49:22 [INFO] [STDOUT] at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
2014-03-25 09:49:22 [INFO] [STDOUT] at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:85)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1651)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:99)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1930)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.client.main.Main.main(SourceFile:101)
2014-03-25 09:49:22 [INFO] [STDOUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-03-25 09:49:22 [INFO] [STDOUT] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDOUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDOUT] at java.lang.reflect.Method.invoke(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2014-03-25 09:49:22 [INFO] [STDOUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-03-25 09:49:22 [INFO] [STDOUT] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDOUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDOUT] at java.lang.reflect.Method.invoke(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDOUT] at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:214)
2014-03-25 09:49:22 [INFO] [STDOUT] at org.multimc.EntryPoint.listen(EntryPoint.java:139)
2014-03-25 09:49:22 [INFO] [STDOUT] at org.multimc.EntryPoint.main(EntryPoint.java:53)
2014-03-25 09:49:22 [INFO] [STDOUT]
2014-03-25 09:49:22 [INFO] [STDOUT]
2014-03-25 09:49:22 [INFO] [STDOUT] A detailed walkthrough of the error, its code path and all known details is as follows:
2014-03-25 09:49:22 [INFO] [STDOUT] ---------------------------------------------------------------------------------------
2014-03-25 09:49:22 [INFO] [STDOUT]
2014-03-25 09:49:22 [INFO] [STDOUT] -- Head --
2014-03-25 09:49:22 [INFO] [STDOUT] Stacktrace:
2014-03-25 09:49:22 [INFO] [STDOUT] at java.io.ByteArrayInputStream.<init>(Unknown Source)
2014-03-25 09:49:22 [INFO] [STDOUT] at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:71)
2014-03-25 09:49:22 [INFO] [STDOUT] at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
2014-03-25 09:49:22 [INFO] [STDOUT] at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
2014-03-25 09:49:22 [INFO] [STDOUT] at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:85)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1651)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
2014-03-25 09:49:22 [INFO] [STDOUT] at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)
2014-03-25 09:49:22 [INFO] [STDOUT]
