### ISSUE TITLE
[BUILD#165] "Ticking Memory connection" Exception

### ISSUE THREAD

**Issue by SonOfTheStars** [RS485/LogisticsPipes#318]
This happens when you have a Crafting LP [MK.I], transfering TE Power into a furnace, holding a recipe for Sand->Glass and you issue a request for Glass. After a restart of Minecraft, the recipe in the Crafting LP is deleted. (The Pipe was not currently transfering power)

2014-04-25 18:56:22 [Information] [STDERR] net.minecraft.util.ReportedException: Ticking memory connection 
2014-04-25 18:56:22 [Information] [STDERR] at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:63) 
2014-04-25 18:56:22 [Information] [STDERR] at net.minecraft.server.integrated.IntegratedServerListenThread.func_71747_b(IntegratedServerListenThread.java:109) 
2014-04-25 18:56:22 [Information] [STDERR] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691) 
2014-04-25 18:56:22 [Information] [STDERR] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587) 
2014-04-25 18:56:22 [Information] [STDERR] at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129) 
2014-04-25 18:56:22 [Information] [STDERR] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) 
2014-04-25 18:56:22 [Information] [STDERR] at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583) 
2014-04-25 18:56:22 [Information] [STDERR] Caused by: java.lang.RuntimeException: java.lang.ArithmeticException: / by zero 
2014-04-25 18:56:22 [Information] [STDERR] at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:82) 
2014-04-25 18:56:22 [Information] [STDERR] at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:70) 
2014-04-25 18:56:22 [Information] [STDERR] at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255) 
2014-04-25 18:56:22 [Information] [STDERR] at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245) 
2014-04-25 18:56:22 [Information] [STDERR] at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:85) 
2014-04-25 18:56:22 [Information] [STDERR] at net.minecraft.network.NetServerHandler.func_72501_a(NetServerHandler.java:1130) 
2014-04-25 18:56:22 [Information] [STDERR] at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61) 
2014-04-25 18:56:22 [Information] [STDERR] at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89) 
2014-04-25 18:56:22 [Information] [STDERR] at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:141) 
2014-04-25 18:56:22 [Information] [STDERR] at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54) 
2014-04-25 18:56:22 [Information] [STDERR] ... 6 more 
2014-04-25 18:56:22 [Information] [STDERR] Caused by: java.lang.ArithmeticException: / by zero 
2014-04-25 18:56:22 [Information] [STDERR] at logisticspipes.request.RequestTreeNode$CraftingSorterNode.<init>(RequestTreeNode.java:503) 
2014-04-25 18:56:22 [Information] [STDERR] at logisticspipes.request.RequestTreeNode.checkCrafting(RequestTreeNode.java:410) 
2014-04-25 18:56:22 [Information] [STDERR] at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:66) 
2014-04-25 18:56:22 [Information] [STDERR] at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:41) 
2014-04-25 18:56:22 [Information] [STDERR] at logisticspipes.request.RequestTree.<init>(RequestTree.java:40) 
2014-04-25 18:56:22 [Information] [STDERR] at logisticspipes.request.RequestTree.request(RequestTree.java:202) 
2014-04-25 18:56:22 [Information] [STDERR] at logisticspipes.request.RequestTree.request(RequestTree.java:224) 
2014-04-25 18:56:22 [Information] [STDERR] at logisticspipes.request.RequestHandler.request(RequestHandler.java:45) 
2014-04-25 18:56:22 [Information] [STDERR] at logisticspipes.network.packets.orderer.RequestSubmitPacket.processPacket(RequestSubmitPacket.java:31) 
2014-04-25 18:56:22 [Information] [STDERR] at logisticspipes.network.PacketHandler.onPacketData(PacketHandler.java:78) 
2014-04-25 18:56:22 [Information] [STDERR] ... 15 more

**Comment by davboecki** [comment]
This is the same problem as your other issue. Please wait for a fix on that one.
