### ISSUE TITLE
Logistic HUD Glasses crash

### ISSUE THREAD

**Issue by SinusoidalC** [RS485/LogisticsPipes#334]
Crash when I wear the Logistic HUD Glasses up.Here's the crash report.My LP version is 0.7.4.dev.185.

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 14-5-5 下午7:05
Description: Unexpected error

java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.EntityRenderer.func_78479_a(FI)V from class logisticspipes.ticks.RenderTickHandler
    at logisticspipes.ticks.RenderTickHandler.tickEnd(RenderTickHandler.java:88)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
    at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:377)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:948)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at logisticspipes.ticks.RenderTickHandler.tickEnd(RenderTickHandler.java:88)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['MarcoV'/64, l='MpServer', x=-674.01, y=5.62, z=48.90]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-672,4,129), Chunk: (at 0,0,1 in -42,8; contains blocks -672,0,128 to -657,255,143), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
    Level time: 5844 game time, 32674 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 33 total; [EntityClientPlayerMP['MarcoV'/64, l='MpServer', x=-674.01, y=5.62, z=48.90], EntityVillager['村民'/20, l='MpServer', x=-731.69, y=1.61, z=37.56], EntityVillager['村民'/21, l='MpServer', x=-749.31, y=5.00, z=56.75], EntityVillager['村民'/22, l='MpServer', x=-748.22, y=4.00, z=50.84], EntityVillager['村民'/23, l='MpServer', x=-732.59, y=6.00, z=37.91], EntityVillager['村民'/24, l='MpServer', x=-744.28, y=4.00, z=52.00], EntityVillager['村民'/25, l='MpServer', x=-732.59, y=6.00, z=36.84], EntityVillager['村民'/26, l='MpServer', x=-753.75, y=5.00, z=53.44], EntityVillager['村民'/27, l='MpServer', x=-739.25, y=4.00, z=35.50], EntityVillager['村民'/28, l='MpServer', x=-752.50, y=4.00, z=51.31], EntityVillager['村民'/30, l='MpServer', x=-752.28, y=4.00, z=37.50], EntityVillager['村民'/32, l='MpServer', x=-733.88, y=4.00, z=40.53], EntityVillager['村民'/33, l='MpServer', x=-732.84, y=4.00, z=52.38], EntityVillager['村民'/34, l='MpServer', x=-749.75, y=5.00, z=55.44], EntityVillager['村民'/36, l='MpServer', x=-749.72, y=5.00, z=57.59], EntityVillager['村民'/37, l='MpServer', x=-735.91, y=4.00, z=37.09], EntityVillager['村民'/38, l='MpServer', x=-739.47, y=6.00, z=32.88], EntityVillager['村民'/39, l='MpServer', x=-725.63, y=4.00, z=34.38], EntityVillager['村民'/40, l='MpServer', x=-736.16, y=4.00, z=38.44], EntityVillager['村民'/41, l='MpServer', x=-729.28, y=5.00, z=39.31], EntityVillager['村民'/42, l='MpServer', x=-724.88, y=4.00, z=37.41], EntityVillager['村民'/43, l='MpServer', x=-723.44, y=5.00, z=58.13], EntityVillager['村民'/44, l='MpServer', x=-727.69, y=5.00, z=56.69], EntityVillager['村民'/45, l='MpServer', x=-729.41, y=4.00, z=63.88], EntityVillager['村民'/46, l='MpServer', x=-721.25, y=5.00, z=74.59], EntityVillager['村民'/47, l='MpServer', x=-715.50, y=4.00, z=62.66], EntityVillager['村民'/48, l='MpServer', x=-717.50, y=4.00, z=72.78], EntityVillager['村民'/49, l='MpServer', x=-725.34, y=4.00, z=77.50], EntityVillager['村民'/50, l='MpServer', x=-714.09, y=4.00, z=63.16], EntitySheep['羊'/16057, l='MpServer', x=-674.50, y=4.00, z=10.50], EntitySheep['羊'/16058, l='MpServer', x=-674.09, y=4.00, z=5.78], EntitySheep['羊'/16059, l='MpServer', x=-671.88, y=4.00, z=3.38], EntitySheep['羊'/16060, l='MpServer', x=-673.41, y=4.00, z=2.28]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:863)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0-ea, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 225067312 bytes (214 MB) / 778502144 bytes (742 MB) up to 778502144 bytes (742 MB)
    JVM Flags: 1 total; -Xmx768m
    AABB Pool Size: 1024 (57344 bytes; 0 MB) allocated, 774 (43344 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 Optifine OptiFine_1.6.4_HD_U_C6(由Mcbbs论坛jamesskl汉化) 43 mods loaded, 43 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.4.49.965} [Forge Mod Loader](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.11.1.965} [Minecraft Forge](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    InputFix{1.6.x-v3} [InputFix](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics-Core{rv14.finale3} [AppliedEnergistics Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.9.0.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.6.1.9} [Not Enough Items](NotEnoughItems 1.6.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerCrystalsCore{1.1.8} [PowerCrystals Core](PowerCrystalsCore-1.1.8-20.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_bspkrsCore{v3.05(1.6.4)} [bspkrsCore]([1.6.4]bspkrsCorev3.05.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DamageIndicatorsMod{2.9.1.1} [Damage Indicators](1.6.4 DamageIndicatorsv2.9.1.1CN.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_ArmorStatusHUD{v1.13(1.6.4)} [ArmorStatusHUD]([1.6.4]ArmorStatusHUDv1.13.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_ReiMinimap{v3.4_01 [1.6.2]} [mod_ReiMinimap]([1.6.4]ReiMinimapCrack_v3.4_01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics{rv14.finale3} [Applied Energistics](appeng-rv14-finale3-mc16x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{4.2.2} [BuildCraft](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{4.2.2} [BC Builders](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{4.2.2} [BC Energy](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{4.2.2} [BC Factory](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{4.2.2} [BC Transport](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{4.2.2} [BC Silicon](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Additional-Buildcraft-Objects{1.0.6.182} [Additional Buildcraft Objects](buildcraft-Z-additional-buildcraft-objects-1.0.6.182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{2.0.0.2} [CoFH Core](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHLoot{2.0.0.2} [CoFH Loot](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHMasquerade{2.0.0.2} [CoFH Masquerade](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHSocial{2.0.0.2} [CoFH Social](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHWorld{2.0.0.2} [CoFH World](CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{2.0.354-experimental} [IndustrialCraft 2](industrialcraft-2_2.0.354-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{2.3.1.1} [Forestry for Minecraft](forestry-A-2.3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2NuclearControl{1.6.2e} [Nuclear Control](IC2NuclearControl-1.6.2e-ic2-experimental.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{@VERSION@} [Inventory Tweaks](InventoryTweaks-1.57-dev-95.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{5.4.1.649} [Iron Chest](ironchest-universal-1.6.4-5.4.1.649.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LogisticsPipes|Main{0.7.4.dev.185} [Logistics Pipes](LogisticsPipes-MC1.6.4-0.7.4.dev.185.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons{1.10.4.64} [NEI Addons](neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|AE{1.10.4.64} [NEI Addons: Applied Energistics](neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|MiscPeripherals{1.10.4.64} [NEI Addons: Misc Peripherals](neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|ExtraBees{1.10.4.64} [NEI Addons: Extra Bees](neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|Forestry{1.10.4.64} [NEI Addons: Forestry](neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|CraftingTables{1.10.4.64} [NEI Addons: Crafting Tables](neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIPlugins{1.1.0.6} [NEI Plugins](NEIPlugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerConverters{1.6.4R2.3.2B1} [Power Converters](PowerConverters-1.6.4-39.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.4.1} [Waila](Waila_1.4.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.0.0.244} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.0.0.244} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.0.0.244} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry : [Forestry] Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
    Launched Version: 1.6.4-Forge9.11.1.965
    LWJGL: 2.9.0
    OpenGL: AMD Radeon HD 7700 Series GL version 4.2.12002 Compatibility Profile Context 9.12.0.0, ATI Technologies Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: 简体中文 (中国)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 192 (10752 bytes; 0 MB) allocated, 192 (10752 bytes; 0 MB) used

**Comment by SinusoidalC** [comment]
ok ,my optifine version is too low==
