### ISSUE TITLE
Dartcraft Issue

### ISSUE THREAD

**Issue by RikuSS4** [RS485/LogisticsPipes#385]
Not sure why this happens, but there is a problem with this mod and logistic pipes. Not sure which mod is causing the problem. I have a logistic pipe attached to storage crates from better storage as a default route. Whenever I put mob core into my logisitc network, using a request table, the server crashes and I have to goto single player and remove the item from the crate. I was using a logistic request table at the time.

I am using Darcraft Beta 0.2.20v2 and Logistic Pipes 0.7.4.dev.247 on minecraft 1.6.4.

```
---- Minecraft Crash Report ----
// This doesn't make any sense!
Time: 6/18/14 1:38 AM
Description: Ticking tile entity
java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
at bluedart.proxy.ProxyCommon.getClientInstance(ProxyCommon.java:96)
at bluedart.item.ItemUpgradeCore.func_77628_j(ItemUpgradeCore.java:46)
at logisticspipes.utils.item.ItemIdentifier.getName(ItemIdentifier.java:258)
at logisticspipes.utils.item.ItemIdentifier.getFriendlyName(ItemIdentifier.java:284)
at logisticspipes.utils.item.ItemIdentifier.toString(ItemIdentifier.java:489)
at logisticspipes.utils.item.ItemIdentifierStack.toString(ItemIdentifierStack.java:122)
at java.lang.String.valueOf(Unknown Source)
at java.lang.StringBuilder.append(Unknown Source)
at logisticspipes.routing.ItemRoutingInformation.toString(ItemRoutingInformation.java:87)
at java.lang.String.valueOf(Unknown Source)
at java.lang.StringBuilder.append(Unknown Source)
at logisticspipes.transport.PipeTransportLogistics.injectItem(PipeTransportLogistics.java:168)
at logisticspipes.transport.PipeTransportLogistics.injectItem(PipeTransportLogistics.java:181)
at logisticspipes.pipes.basic.CoreRoutedPipe.sendRoutedItem(CoreRoutedPipe.java:233)
at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:397)
at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:178)
at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_70316_g(LogisticsTileGenericPipe.java:89)
at net.minecraft.world.World.func_72939_s(World.java:2784)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:883)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 23 more
Caused by: java.lang.RuntimeException: Attempted to load class awe for invalid side SERVER
at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:51)
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:274)
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:172)
... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Stacktrace:
at bluedart.proxy.ProxyCommon.getClientInstance(ProxyCommon.java:96)
at bluedart.item.ItemUpgradeCore.func_77628_j(ItemUpgradeCore.java:46)
at logisticspipes.utils.item.ItemIdentifier.getName(ItemIdentifier.java:258)
at logisticspipes.utils.item.ItemIdentifier.getFriendlyName(ItemIdentifier.java:284)
at logisticspipes.utils.item.ItemIdentifier.toString(ItemIdentifier.java:489)
at logisticspipes.utils.item.ItemIdentifierStack.toString(ItemIdentifierStack.java:122)
at java.lang.String.valueOf(Unknown Source)
at java.lang.StringBuilder.append(Unknown Source)
at logisticspipes.routing.ItemRoutingInformation.toString(ItemRoutingInformation.java:87)
at java.lang.String.valueOf(Unknown Source)
at java.lang.StringBuilder.append(Unknown Source)
at logisticspipes.transport.PipeTransportLogistics.injectItem(PipeTransportLogistics.java:168)
at logisticspipes.transport.PipeTransportLogistics.injectItem(PipeTransportLogistics.java:181)
at logisticspipes.pipes.basic.CoreRoutedPipe.sendRoutedItem(CoreRoutedPipe.java:233)
at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:397)
at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:178)
at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_70316_g(LogisticsTileGenericPipe.java:89)
-- Tile entity being ticked --
Details:
Name: logisticspipes.pipes.basic.LogisticsTileGenericPipe // logisticspipes.pipes.basic.LogisticsTileGenericPipe
Block type: ID #1443 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
Block data value: 0 / 0x0 / 0b0000
Block location: World: (548,59,551), Chunk: (at 4,3,7 in 34,34; contains blocks 544,0,544 to 559,255,559), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
Actual block type: ID #1443 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
Actual block data value: 0 / 0x0 / 0b0000
LP-Version: 0.7.4.dev.247:false
Pipe: logisticspipes.pipes.PipeBlockRequestTable
Transport: logisticspipes.transport.PipeTransportLogistics
Router: ServerRouter: {ID: 490, UUID: 041310b1-1f3e-4b0f-af25-14aeb7117473, AT: (0, 548, 59, 551), Version: 1), Destroied: false}
stillNeedReplace: false
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:2784)
-- Affected level --
Details:
Level name: world
All players: 0 total; []
Chunk stats: ServerChunkCache: 650 Drop: 0
Level seed: 880822240606527648
Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
Level generator options:
Level spawn location: World: (0,74,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 32797131 game time, 33267826 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 41476 (now: false), thunder time: 15705 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:883)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
-- System Details --
Details:
Minecraft Version: 1.6.4
Operating System: Linux (amd64) version 2.6.32-431.11.2.el6.x86_64
Java Version: 1.7.0_45, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 2196470608 bytes (2094 MB) / 4073193472 bytes (3884 MB) up to 4073193472 bytes (3884 MB)
JVM Flags: 4 total; -Xmx4096M -Xms4096M -XX:PermSize=256m -XX:MaxPermSize=512m
AABB Pool Size: 4039 (226184 bytes; 0 MB) allocated, 4039 (226184 bytes; 0 MB) used
Suspicious classes: FML and Forge are installed
IntCache: cache: 0, tcache: 17973, allocated: 1, tallocated: 5479
CraftBukkit Information:
   Running: MCPC+ version git-MCPC-Plus-jenkins-Cauldron-164-271 (MC: 1.6.4) (Implementing API version 1.6.4-R2.1-SNAPSHOT) false
   Plugins: { BioMan v1.5.2.0 fr.richie.BioMan.BMPlugin [richie3366], WorldBorder v1.7.9 com.wimbli.WorldBorder.WorldBorder [Brettflan], ClearLag v2.6.0 me.minebuilders.clearlag.Clearlag [bob7l], PermissionsEx v1.20.4 ru.tehkode.permissions.bukkit.PermissionsEx [[t3hk0d3, zml]], WorldEdit v5.5.8 com.sk89q.worldedit.bukkit.WorldEditPlugin [], AuthMe v3.3.6 fr.xephi.authme.AuthMe [Xephi59], WorldGuard v5.8 com.sk89q.worldguard.bukkit.WorldGuardPlugin [], TwitchIRC v0.3.0-mc1.7.2 uk.co.reosh.TwitchIRC.Twitch [], HomeSpawnPlus v1.7.8 org.morganm.homespawnplus.HomeSpawnPlus [morganm], Buycraft v6.7 net.buycraft.Plugin [Tebex Limited], BlockOwn v1.2.1 de.pheasn.blockown.BlockOwn [Pheasn],}
   Warnings: DEFAULT
   Threads: { RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_6_R3.CraftCrashReport.call(CraftCrashReport.java:27), net.minecraft.crash.CrashReportCategory.func_71500_a(CrashReportCategory.java:106), net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:58), net.minecraft.crash.CrashReport.<init>(CrashReport.java:40), net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:312), net.minecraft.world.World.func_72939_s(World.java:2792), net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:883), net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330), net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777), net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659), net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)], WAITING LogisticsPipes Packet Decompressor Server: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), logisticspipes.ticks.ServerPacketBufferHandlerThread$ServerDecompressorThread.run(ServerPacketBufferHandlerThread.java:262)], WAITING pool-3-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), cpw.mods.fml.relauncher.FMLRelaunchLog$ConsoleLogThread.run(FMLRelaunchLog.java:83), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Thread-5: [java.lang.Thread.sleep(Native Method), net.minecraft.server.dedicated.DedicatedServerSleepThread.run(DedicatedServerSleepThread.java:23)], WAITING pool-3-thread-2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Thread-37: [java.net.PlainDatagramSocketImpl.receive0(Native Method), java.net.AbstractPlainDatagramSocketImpl.receive(Unknown Source), java.net.DatagramSocket.receive(Unknown Source), net.minecraft.network.rcon.RConThreadQuery.run(RConThreadQuery.java:318), java.lang.Thread.run(Unknown Source)], WAITING LogisticsPipes Packet Compressor Server: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), logisticspipes.ticks.ServerPacketBufferHandlerThread$ServerCompressorThread.run(ServerPacketBufferHandlerThread.java:90)], TIMED_WAITING Thread-31: [java.lang.Thread.sleep(Native Method), de.pheasn.pluginupdater.Updater.run(Updater.java:230)], RUNNABLE LogisticsPipes RoutingTableUpdateThread #2: [logisticspipes.routing.ServerRouter.CreateRouteTable(ServerRouter.java:585), logisticspipes.routing.ServerRouter.CreateRouteTable(ServerRouter.java:511), logisticspipes.routing.ServerRouter$UpdateRouterRunnable.run(ServerRouter.java:105), logisticspipes.ticks.RoutingTableUpdateThread.run(RoutingTableUpdateThread.java:45)], WAITING PR RoutingThread #0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.PriorityBlockingQueue.take(Unknown Source), mrtjp.projectred.transportation.TableUpdateThread.run(routingthreads.scala:37)], TIMED_WAITING EbeanCacheWarmer: [java.lang.Thread.sleep(Native Method), com.avaje.ebeaninternal.server.core.DefaultServerFactory$CacheWarmer.run(DefaultServerFactory.java:509), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING Timer-1: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING PR RoutingThread #3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.PriorityBlockingQueue.take(Unknown Source), mrtjp.projectred.transportation.TableUpdateThread.run(routingthreads.scala:37)], WAITING Ebean-HomeSpawnPlus.0: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), com.avaje.ebeaninternal.server.lib.thread.PooledThread.run(PooledThread.java:75), java.lang.Thread.run(Unknown Source)], RUNNABLE Command Reader: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(Unknown Source), java.io.BufferedInputStream.fill(Unknown Source), java.io.BufferedInputStream.read(Unknown Source), java.io.FilterInputStream.read(Unknown Source), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1.read(ConsoleReader.java:167), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLineSimple(ConsoleReader.java:1506), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1153), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1117), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1105), net.minecraft.server.dedicated.DedicatedServerCommandThread.run(DedicatedServerCommandThread.java:42)], WAITING PR RoutingThread #2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.PriorityBlockingQueue.take(Unknown Source), mrtjp.projectred.transportation.TableUpdateThread.run(routingthreads.scala:37)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:174)], WAITING PermissionsEx-Cleaner: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Spigot Metrics Thread: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], RUNNABLE DestroyJavaVM: [], WAITING Keep-Alive-SocketCleaner: [java.lang.Object.wait(Native Method), sun.net.www.http.KeepAliveStreamCleaner.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING PR RoutingThread #1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.PriorityBlockingQueue.take(Unknown Source), mrtjp.projectred.transportation.TableUpdateThread.run(routingthreads.scala:37)], TIMED_WAITING Timer-2: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING Immibis Core background task: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], RUNNABLE LogisticsPipes RoutingTableUpdateThread #0: [logisticspipes.routing.ServerRouter.CreateRouteTable(ServerRouter.java:585), logisticspipes.routing.ServerRouter.CreateRouteTable(ServerRouter.java:511), logisticspipes.routing.ServerRouter$UpdateRouterRunnable.run(ServerRouter.java:105), logisticspipes.ticks.RoutingTableUpdateThread.run(RoutingTableUpdateThread.java:45)], TIMED_WAITING Universal Electricity: [java.lang.Thread.sleep(Native Method), resonant.lib.grid.UpdateTicker.run(UpdateTicker.java:126)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], TIMED_WAITING EbeanBackgroundThread: [java.lang.Thread.sleep(Native Method), com.avaje.ebeaninternal.server.lib.BackgroundThread$Runner.run(BackgroundThread.java:168), java.lang.Thread.run(Unknown Source)], RUNNABLE LogisticsPipes RoutingTableUpdateThread #3: [logisticspipes.routing.ServerRouter.CreateRouteTable(ServerRouter.java:593), logisticspipes.routing.ServerRouter.CreateRouteTable(ServerRouter.java:511), logisticspipes.routing.ServerRouter$UpdateRouterRunnable.run(ServerRouter.java:105), logisticspipes.ticks.RoutingTableUpdateThread.run(RoutingTableUpdateThread.java:45)], WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], RUNNABLE Signal Dispatcher: [], RUNNABLE Listen thread: [java.net.PlainSocketImpl.socketAccept(Native Method), java.net.AbstractPlainSocketImpl.accept(Unknown Source), java.net.ServerSocket.implAccept(Unknown Source), java.net.ServerSocket.accept(Unknown Source), net.minecraft.server.ServerListenThread.run(ServerListenThread.java:82)], RUNNABLE LogisticsPipes RoutingTableUpdateThread #1: [logisticspipes.routing.ServerRouter.CreateRouteTable(ServerRouter.java:585), logisticspipes.routing.ServerRouter.CreateRouteTable(ServerRouter.java:511), logisticspipes.routing.ServerRouter$UpdateRouterRunnable.run(ServerRouter.java:105), logisticspipes.ticks.RoutingTableUpdateThread.run(RoutingTableUpdateThread.java:45)], TIMED_WAITING Keep-Alive-Timer: [java.lang.Thread.sleep(Native Method), sun.net.www.http.KeepAliveCache.run(Unknown Source), java.lang.Thread.run(Unknown Source)],}
   Recent tasks from -28-2{BioMan:org.mcstats.BukkitMetrics$1@31,BlockOwn:org.mcstats.Metrics$1@31,HomeSpawnPlus:org.morganm.homespawnplus.Metrics$8@31,}
FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 185 mods loaded, 185 mods active
TConstruct Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
Forestry : [Forestry] Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client:
Bukkit, MCPC+, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
Ender-Quarry Relfection Code:: No problems here
Profiler Position: N/A (disabled)
Vec3 Pool Size: 55 (3080 bytes; 0 MB) allocated, 2 (112 bytes; 0 MB) used
Player Count: 0 / 120; []
Is Modded: Definitely; Server brand changed to 'mcpc,craftbukkit,fml,forge'
Type: Dedicated Server (map_server.txt)
```

**Comment by AartBluestoke** [comment]
You read this list from the bottom up: logistics pipes asks the
bluedart.item.ItemUpgradeCore what it's name is, server side.

Below the first set of detail : Caused by: java.lang.RuntimeException:
Attempted to load class awe for invalid side SERVER at
cpw.mods.fml.common.asm.transformers.SideTransformer.transform

This explains why that class was not found, because FML refused to load the
client side only GUI class. The issue is, why does creating an
itemUpgradeCore server side, and asking its name attempts to instantiate a
GUI. This is a dartcraft issue, possibly caused by static variable
initialisation, or a missed isServerSide check.

---

I think we need a 'contains corrupted data that caused an exception' state
on a pipe so that these don't take down a sever. Report a message to the

## player, and place the pipe into a preeminently emitting black sparks state.

java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen at
bluedart.proxy.ProxyCommon.getClientInstance(ProxyCommon.java:96) at
bluedart.item.ItemUpgradeCore.func_77628_j(ItemUpgradeCore.java:46) at
logisticspipes.utils.item.ItemIdentifier.getName(ItemIdentifier.java:258)
at
logisticspipes.utils.item.ItemIdentifier.getFriendlyName(ItemIdentifier.java:284)

**Comment by davboecki** [comment]
DartCraft issue. Like AartBluestoke said.
