### ISSUE TITLE
Crash sorting again -- main 93.

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#39]
tile entity in question was a supplier pipe, nothing was being done to it at the time.

java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeLo(TimSort.java:747)
    at java.util.TimSort.mergeAt(TimSort.java:483)
    at java.util.TimSort.mergeCollapse(TimSort.java:410)
    at java.util.TimSort.sort(TimSort.java:214)
    at java.util.TimSort.sort(TimSort.java:173)
    at java.util.Arrays.sort(Arrays.java:659)
    at java.util.Collections.sort(Collections.java:217)
    at logisticspipes.request.RequestManager.checkCrafting(RequestManager.java:436)
    at logisticspipes.request.RequestManager.generateRequestTree(RequestManager.java:230)
    at logisticspipes.request.RequestManager.requestPartial(RequestManager.java:132)
    at logisticspipes.logic.LogicSupplier.throttledUpdateEntity(LogicSupplier.java:174)
    at logisticspipes.logic.BaseRoutingLogic.updateEntity(BaseRoutingLogic.java:51)
    at buildcraft.transport.Pipe.updateEntity(Pipe.java:167)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:305)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at yc.h(World.java:2597)
    at in.h(WorldServer.java:701)

**Comment by AartBluestoke** [comment]
fixed in main. simple commit to get it done here -- not pushed yet.

**Comment by AartBluestoke** [comment]
merged with main, should be fixed.
