### ISSUE TITLE
npe when using worldEdit to move stuff

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#40]
java.lang.NullPointerException
    at logisticspipes.pipes.basic.CoreRoutedPipe.checkTileEntity(CoreRoutedPipe.java:223)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:286)
    at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
    at yc.h(World.java:2597)
    at in.h(WorldServer.java:701)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:956)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:857)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:744)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by davboecki** [comment]
Probably caused by the coodinates not being updated.

**Comment by AartBluestoke** [comment]
should be a bit better in 16, but i don't expect this ticket to be closed any time soon. (probably needs a callback from forge to notify things that they are being moved)

**Comment by bziemons** [comment]
Closed, as it is not relevant nor recent anymore.
