### ISSUE TITLE
problems 

### ISSUE THREAD

**Issue by miembrodes** [RS485/LogisticsPipes#400]
i had crash when i installed additional pipes please help
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: redstoneChipset
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:156)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:523)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.NoSuchFieldError: redstoneChipset
    at buildcraft.additionalpipes.AdditionalPipes.loadPipes(AdditionalPipes.java:327)
    at buildcraft.additionalpipes.AdditionalPipes.preInit(AdditionalPipes.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:522)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
    Memory: 48834264 bytes (46 MB) / 232595456 bytes (221 MB) up to 518979584 bytes (494 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 Optifine OptiFine_1.6.4_HD_U_C8 17 mods loaded, 17 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{6.4.49.965} [Forge Mod Loader](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized
    Forge{9.11.1.965} [Minecraft Forge](minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized
    mod_CutAllSMP{2.4.7} [mod_CutAllSMP](%5B1.6.4%5Dmod_CutAllSMP_v2.4.7_forge9.11.0.884.zip) Unloaded->Constructed->Pre-initialized
    mod_MineAllSMP{2.5.6} [mod_MineAllSMP](%5B1.6.4%5Dmod_MineAllSMP_v2.5.6_forge9.11.0.884.zip) Unloaded->Constructed->Pre-initialized
    mod_ReiMinimap{v3.4_01 [1.6.2]} [mod_ReiMinimap]([1.6.4]ReiMinimap_v3.4_01.zip) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{4.2.2} [BuildCraft](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{4.2.2} [BC Factory](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{4.2.2} [BC Transport](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{4.2.2} [BC Silicon](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized
    APUnofficial{2.4.5b} [Additional Pipes](AdditionalPipes2.4.5b-BC4.1.0.jar) Unloaded->Constructed->Errored
    Backpack{1.28.37} [Backpack](backpack-1.28.37-1.6.x.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{4.2.2} [BC Builders](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{4.2.2} [BC Energy](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized
    craftguide{1.5.2} [CraftGuide](CraftGuide-1.6.7.4.zip) Unloaded->Constructed->Pre-initialized
    IC2{1.118.401-lf} [IndustrialCraft 2](industrialcraft-2_1.118.401-lf.jar) Unloaded->Constructed->Pre-initialized
    LogisticsPipes|Main{${lp.version.full}} [Logistics Pipes](LogisticsPipes-MC1.6.4-0.7.4.dev.279.jar) Unloaded->Constructed->Pre-initialized

**Comment by davboecki** [comment]
AdditionalPipes is not LogisticsPipes.
(Your BC version isn't compatible with your AdditionalPipes version)

**Comment by miembrodes** [comment]
thanks very much
