### ISSUE TITLE
ic2 and logistics provider crash

### ISSUE THREAD

**Issue by freakyd** [RS485/LogisticsPipes#456]
If you put a fluid provider on an ic2 machine that has fluid it crashes.
if(((IFluidHandler)pair.getValue1()).canDrain(pair.getValue2().getOpposite(), liquid.getFluid())) { on line 265 in PipeFluidProvider.java

**Comment by freakyd** [comment]
java.lang.NullPointerException: Ticking block entity
    at ic2.core.block.machine.tileentity.TileEntityCondenser.canDrain(TileEntityCondenser.java:237)
    at logisticspipes.pipes.PipeFluidProvider.getSpecificInterests(PipeFluidProvider.java:265)
    at logisticspipes.routing.ServerRouter.updateInterests(ServerRouter.java:996)
    at logisticspipes.routing.ServerRouter.update(ServerRouter.java:871)

**Comment by davboecki** [comment]
This is definitly an IC2 bug. Did you report it to them?

**Comment by freakyd** [comment]
I've reported it now, we'll see what happens.

**Comment by freakyd** [comment]
This bug has been fixed over on the ic2 side. Now instead of null it returns false if there is a null detected. version ic2-exp 648
