### ISSUE TITLE
client side error when right clicking request bench - unsure of cause

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#466]
i had a pick in my hand, and i right-clicked a request bench. it had no outstanding requests. (hadn't been used in > 10 mins)

java.lang.IndexOutOfBoundsException: Index: 45, Size: 45
at java.util.ArrayList.rangeCheck(ArrayList.java:635)
at java.util.ArrayList.get(ArrayList.java:411)
at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
at net.minecraft.inventory.Container.func_75131_a(SourceFile:390)
at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1056)
at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:49)
at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:11)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
at net.minecraft.client.main.Main.main(SourceFile:148)

**Comment by AartBluestoke** [comment]
the request table, and everything in it was gone by the time i got back into the game.
i don't thing i clicked wrong and broke it.

**Comment by bziemons** [comment]
Can you try to reproduce that?

**Comment by davboecki** [comment]
This is a server client out of sync error. Nothing we can do about it as long as it is not reproducable.
