### ISSUE TITLE
Crash when adding QuickSort module to Chassis Pipe on AE Interface

### ISSUE THREAD

**Issue by pansx** [RS485/LogisticsPipes#481]
http://pastebin.com/W6E6pwih

**Comment by bziemons** [comment]
@davboecki ForgeDirection.UNKNOWN

**Comment by mezoty** [comment]
Same crash with ItemSink module (default route = yes), after adding to MK2 chassis connected to AE2 interface. 

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2.11.14 22:51
Description: Ticking block entity

java.lang.IllegalArgumentException: The direction must not be unknown
    at logisticspipes.proxy.specialinventoryhandler.AEInterfaceInventoryHandler.<init>(AEInterfaceInventoryHandler.java:42)
    at logisticspipes.proxy.specialinventoryhandler.AEInterfaceInventoryHandler.getUtilForTile(AEInterfaceInventoryHandler.java:70)
    at logisticspipes.utils.InventoryUtilFactory.getUtilForInv(InventoryUtilFactory.java:48)
    at logisticspipes.utils.InventoryUtilFactory.getHidingInventoryUtil(InventoryUtilFactory.java:59)
    at logisticspipes.utils.InventoryUtilFactory.getInventoryUtil(InventoryUtilFactory.java:55)
    at logisticspipes.pipes.basic.CoreRoutedPipe.getSneakyInventory(CoreRoutedPipe.java:1473)
    at logisticspipes.pipes.basic.CoreRoutedPipe.getSneakyInventory(CoreRoutedPipe.java:1465)
    at logisticspipes.modules.ChassiModule.sinksItem(ChassiModule.java:68)
    at logisticspipes.logistics.LogisticsManager.canSink(LogisticsManager.java:167)
    at logisticspipes.logistics.LogisticsManager.getBestReply(LogisticsManager.java:119)
    at logisticspipes.logistics.LogisticsManager.hasDestination(LogisticsManager.java:73)
    at logisticspipes.pipes.basic.CoreRoutedPipe.hasDestination(CoreRoutedPipe.java:1509)
    at logisticspipes.pipes.basic.CoreRoutedPipe.hasDestination(CoreRoutedPipe.java:124)
    at logisticspipes.modules.ModuleExtractor.tick(ModuleExtractor.java:153)
    at logisticspipes.modules.ChassiModule.tick(ChassiModule.java:118)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:423)
    at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145845_h(LogisticsTileGenericPipe.java:179)
    at net.minecraft.world.World.func_72939_s(World.java:1912)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
