### ISSUE TITLE
new provider module gui crashes

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#490]
not sure how _sneaky becomes null after toggling the gui ...
java.lang.NullPointerException: Updating screen events
at logisticspipes.modules.ModuleProvider.writeToNBT(ModuleProvider.java:133)
at logisticspipes.logisticspipes.ItemModuleInformationManager.saveInfotmation(ItemModuleInformationManager.java:28)
at logisticspipes.utils.gui.ModuleSlot.func_82870_a(ModuleSlot.java:23)
at logisticspipes.utils.gui.DummyContainer.superSlotClick(DummyContainer.java:346)
at logisticspipes.utils.gui.DummyContainer.func_75144_a(DummyContainer.java:492)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:537)
at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:636)
at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHand

**Comment by SonOfTheStars** [comment]
Additionally, the Proider Module immideatley spams out every item it has towards ANY valid Sink destinaton, and doing so, it even goes on after the InverntorySizeMax has been reached

**Comment by bziemons** [comment]
For now reverted in 8a1d31d918a49101bca4c2afc7d51e34964cc094
I suggest making an extra branch for the new behavior and bugged code.
