### ISSUE TITLE
Error with provider module and AE2 interface.

### ISSUE THREAD

**Issue by ruifung** [RS485/LogisticsPipes#503]
As soon as I place a provider module in a chassis pipe next to a AE2 interface, this error occurs:

```
Description: Ticking block entity

java.lang.IllegalArgumentException: The direction must not be unknown
at logisticspipes.proxy.specialinventoryhandler.AEInterfaceInventoryHandler.<init>(AEInterfaceInventoryHandler.java:42)
at logisticspipes.proxy.specialinventoryhandler.AEInterfaceInventoryHandler.getUtilForTile(AEInterfaceInventoryHandler.java:70)
at logisticspipes.utils.InventoryUtilFactory.getUtilForInv(InventoryUtilFactory.java:48)
at logisticspipes.utils.InventoryUtilFactory.getHidingInventoryUtil(InventoryUtilFactory.java:59)
at logisticspipes.utils.InventoryUtilFactory.getInventoryUtil(InventoryUtilFactory.java:55)
at logisticspipes.pipes.PipeLogisticsChassi.getSpecificInterests(PipeLogisticsChassi.java:594)
at logisticspipes.routing.ServerRouter.updateInterests(ServerRouter.java:996)
at logisticspipes.routing.ServerRouter.update(ServerRouter.java:871)
at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:378)
at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145845_h(LogisticsTileGenericPipe.java:180)
at net.minecraft.world.World.func_72939_s(World.java:1939)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at logisticspipes.proxy.specialinventoryhandler.AEInterfaceInventoryHandler.<init>(AEInterfaceInventoryHandler.java:42)
at logisticspipes.proxy.specialinventoryhandler.AEInterfaceInventoryHandler.getUtilForTile(AEInterfaceInventoryHandler.java:70)
at logisticspipes.utils.InventoryUtilFactory.getUtilForInv(InventoryUtilFactory.java:48)
at logisticspipes.utils.InventoryUtilFactory.getHidingInventoryUtil(InventoryUtilFactory.java:59)
at logisticspipes.utils.InventoryUtilFactory.getInventoryUtil(InventoryUtilFactory.java:55)
at logisticspipes.pipes.PipeLogisticsChassi.getSpecificInterests(PipeLogisticsChassi.java:594)
at logisticspipes.routing.ServerRouter.updateInterests(ServerRouter.java:996)
at logisticspipes.routing.ServerRouter.update(ServerRouter.java:871)
at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:378)
at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145845_h(LogisticsTileGenericPipe.java:180)

-- Block entity being ticked --
Details:
Name: logisticspipes.pipes.basic.LogisticsTileGenericPipe // logisticspipes.pipes.basic.LogisticsTileGenericPipe
Block type: ID #857 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
Block data value: 0 / 0x0 / 0b0000
Block location: World: (-272,55,525), Chunk: (at 0,3,13 in -17,32; contains blocks -272,0,512 to -257,255,527), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
Actual block type: ID #857 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
Actual block data value: 0 / 0x0 / 0b0000
LP-Version: 0.8.2.77:false
Pipe: logisticspipes.pipes.PipeLogisticsChassiMk2
Transport: logisticspipes.transport.PipeTransportLogistics
Router: ServerRouter: {ID: 1, UUID: af233832-e86e-49f4-acf0-7d63403a888c, AT: (0, -272, 55, 525), Version: 1), Destroied: false}
stillNeedReplace: false
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1939)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by ruifung** [comment]
Oops. duplicate of #500.
