### ISSUE TITLE
Exception spam: java.lang.NoSuchFieldException: tagMap

### ISSUE THREAD

**Issue by Cisien** [RS485/LogisticsPipes#52]
I am working on migrating my 1.4.7 world to 1.5.1. In the process I updated Logistics Pipes from LogisticsPipes-MC1.4.7-0.7.0.90 to the latest jenkins build (LogisticsPipes-MC1.5.1-0.7.2.dev.398)

After I started the server, i started getting spammed with the following exception/stack trace approx. once per second. I am getting 50+ of these every second (i can only speculate that this is every logistics pipe on the server.

java.lang.NoSuchFieldException: tagMap
    at java.lang.Class.getDeclaredField(Unknown Source)
    at logisticspipes.utils.FinalNBTTagCompound.<init>(FinalNBTTagCompound.java:18)
    at logisticspipes.utils.ItemIdentifier.get(ItemIdentifier.java:125)
    at logisticspipes.utils.ItemIdentifier.get(ItemIdentifier.java:148)
    at logisticspipes.proxy.specialinventoryhandler.AEInterfaceInventoryHandler.getItems(AEInterfaceInventoryHandler.java:68)
    at logisticspipes.pipes.PipeItemsProviderLogistics.getSpecificInterests(PipeItemsProviderLogistics.java:441)
    at logisticspipes.routing.ServerRouter.updateInterests(ServerRouter.java:821)
    at logisticspipes.routing.ServerRouter.update(ServerRouter.java:734)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:308)
    at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:189)
    at net.minecraft.world.World.func_72939_s(World.java:2196)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:546)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:651)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:274)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:570)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:468)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

**Comment by rmm99** [comment]
For what it's worth, I have the same error on a world that was started in 1.5.1.  LogPipes was working fine until I requested a complex crafting.  Down revving the previous few versions did not resolve the issue.  I had previously updated to resolve the crafting sign issue. 

EDIT:  P.S. I didn't want to create a new issue for an identical error; if that is not ideal, let me know.

java.lang.NoSuchFieldException: tagMap
at java.lang.Class.getDeclaredField(Unknown Source)
at logisticspipes.utils.FinalNBTTagCompound.<init>(FinalNBTTagCompound.java:18)
at logisticspipes.utils.ItemIdentifier.get(ItemIdentifier.java:125)
at logisticspipes.utils.ItemIdentifier.get(ItemIdentifier.java:148)
at logisticspipes.utils.InventoryUtil.getItems(InventoryUtil.java:76)
at logisticspipes.pipes.PipeLogisticsChassi.getSpecificInterests(PipeLogisticsChassi.java:626)
at logisticspipes.routing.ServerRouter.updateInterests(ServerRouter.java:821)
at logisticspipes.routing.ServerRouter.update(ServerRouter.java:734)
at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:308)
at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:189)
at net.minecraft.world.World.func_72939_s(World.java:2196)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:546)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:651)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:274)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:570)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:468)
at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

**Comment by AartBluestoke** [comment]
lp for 1.5.1 is still dev; known bugs include some rendering issues, and failed requests reporting wrong (specifically causing the "missing ingredients" list on a remote request, and the partial requests on suppliers to be wrong).

you are probably getting one of those errors for each damageable item type on the network.

**Comment by rmm99** [comment]
Thanks for the reply, Aart.  Do you need anything further from the logs or such; or just want this to ride out as you progress in 1.5.1 dev?

**Comment by davboecki** [comment]
That sounds more like a problem with reflection and srg_names inside the mod. LP only looks for the obfuscated name and for the mcp name but not for the srg name. Shouldn't be hard to fix.

**Comment by davboecki** [comment]
Should be fixed now.

**Comment by rmm99** [comment]
Just a heads-up:  restored from backup the world at the point where LP was causing the errors.  This fixed the specific error on world load.  Additionally, I was able to request some items, including autocrafted items, successfully.  Well done!  Thanks for looking at this issue.
