### ISSUE TITLE
sendToPlayerList called clientside

### ISSUE THREAD

**Issue by MyEternity** [RS485/LogisticsPipes#535]
[00:16:11] [Client thread/INFO] [STDERR/]: [logisticspipes.proxy.MainProxy:sendToPlayerList:176]: sendToPlayerList called clientside !
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.Exception
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.proxy.MainProxy.sendToPlayerList(MainProxy.java:177)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.modules.ModuleActiveSupplier.InventoryChanged(ModuleActiveSupplier.java:120)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.utils.item.ItemIdentifierInventory.func_70296_d(ItemIdentifierInventory.java:157)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.utils.gui.DummyContainer.func_75141_a(DummyContainer.java:720)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1021)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.main.Main.main(SourceFile:148)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.reflect.Method.invoke(Unknown Source)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.reflect.Method.invoke(Unknown Source)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at org.multimc.EntryPoint.listen(EntryPoint.java:165)
[00:16:11] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at org.multimc.EntryPoint.main(EntryPoint.java:54)

Occures with GraviWrench when clicking on Active Supplier Pipe.

**Comment by bziemons** [comment]
Can you put the whole crash on https://gist.github.com/ with all version information and such?

**Comment by MyEternity** [comment]
I can upload you logfile. It's not a crash. It's client console log with spam messages.
Here full logfile for analyse: http://paste.ee/p/6K0ew
My actions:
1. Started game.
2. Logged into server.
3. Clicked RMB (Right mouse button) on Active Supplier with GraviKey.

**Comment by bziemons** [comment]
Could you still tell us your versions of BC and LP then?

**Comment by MyEternity** [comment]
Here they are: 
buildcraft-6.2.6
logisticspipes-0.8.2.84

**Comment by MyEternity** [comment]
This bug affected to other "Suppliers", for example: Passive Supplier module.
