### ISSUE TITLE
logisticspipes_dummy

### ISSUE THREAD

**Issue by bigfish218** [RS485/LogisticsPipes#545]
here is what my crashlog says (note) I am very new to this would greatly appreciate the help:
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 12/30/14 10:36 AM
Description: Initializing game

java.lang.RuntimeException: LogisticsPipes could not find its class transformer. If you are running MC from an IDE make sure to copy the 'LogisticsPipes_dummy.jar' to your mods folder. If you are running MC normal please report this as a bug at 'https://github.com/RS485/LogisticsPipes/issues'.
    at logisticspipes.LogisticsPipes.<init>(LogisticsPipes.java:177)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at java.lang.Class.newInstance(Class.java:438)
    at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:173)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:486)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at logisticspipes.LogisticsPipes.<init>(LogisticsPipes.java:177)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at java.lang.Class.newInstance(Class.java:438)
    at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:173)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:486)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 137363784 bytes (131 MB) / 342761472 bytes (326 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 43 mods loaded, 43 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{7.10.85.1277} [Forge Mod Loader](forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed
    Forge{10.13.2.1277} [Minecraft Forge](forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed
    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed
    DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed
    BiblioCraft{1.8.2} [BiblioCraft](BiblioCraft-Mod-1.7.10.jar) Unloaded->Constructed
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1034-universal.jar) Unloaded->Constructed
    CoFHCore{1.7.10R3.0.0B9} [CoFH Core](CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed
    BuildCraft|Core{6.2.6} [BuildCraft](buildcraft-6.2.6.jar) Unloaded->Constructed
    BuildCraft|Transport{6.2.6} [BC Transport](buildcraft-6.2.6.jar) Unloaded->Constructed
    BuildCraft|Silicon{6.2.6} [BC Silicon](buildcraft-6.2.6.jar) Unloaded->Constructed
    BuildCraft|Builders{6.2.6} [BC Builders](buildcraft-6.2.6.jar) Unloaded->Constructed
    BuildCraft|Energy{6.2.6} [BC Energy](buildcraft-6.2.6.jar) Unloaded->Constructed
    BuildCraft|Factory{6.2.6} [BC Factory](buildcraft-6.2.6.jar) Unloaded->Constructed
    ChickenChunks{1.3.4.16} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.16-universal.jar) Unloaded->Constructed
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed
    IC2{2.2.657-experimental} [IndustrialCraft 2](Industrial-Craft-2-Mod-Experimental-1.7.10.jar) Unloaded->Constructed
    CompactSolars{4.4.39.315} [Compact Solar Arrays](CompactSolars-1.7.10-4.4.39.315-universal.jar) Unloaded->Constructed
    ComputerCraft{1.65} [ComputerCraft](ComputerCraft1.65.jar) Unloaded->Constructed
    eplus{1.7.10-3.0.1} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.1.jar) Unloaded->Constructed
    EnderIO{1.7.10-2.2.6.313_beta} [Ender IO](EnderIO-1.7.10-2.2.6.313_beta.jar) Unloaded->Constructed
    EnderStorage{1.4.5.27} [EnderStorage](EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded->Constructed
    exnihilo{1.37} [Ex Nihilo](Ex-Nihilo-1.37.jar) Unloaded->Constructed
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed
    ForgeMultipart{1.1.0.309} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed
    ExtraUtilities{1.2.1} [Extra Utilities](extrautilities-1.2.1.jar) Unloaded->Constructed
    FlatSigns{2.0.0.17} [Flat Signs](FlatSigns-1.7.10-universal-2.0.0.17.jar) Unloaded->Constructed
    Forestry{3.3.0.6} [Forestry for Minecraft](forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed
    IC2BackpackHUD{3.0} [IC2 Backpack HUD](IC2 Backpack HUD v3.0 - MC 1.7.10.zip) Unloaded->Constructed
    iChunUtil{4.0.0} [iChunUtil](iChun-Util-Mod-1.7.10.jar) Unloaded->Constructed
    ImmibisCore{59.0.1} [Immibis Core](Immibis-Core-1.7.10.jar) Unloaded->Constructed
    ImmibisPeripherals{59.0.2} [Immibis's Peripherals](immibis-peripherals-59.0.2.jar) Unloaded->Constructed
    InfernalMobs{1.5.4} [Infernal Mobs](InfernalMobs-1.7.10.jar) Unloaded->Constructed
    IronChest{6.0.62.742} [Iron Chest](Iron-Chests-Mod-1.7.10.jar) Unloaded->Constructed
    LiquidXP{58.1.1} [Liquid XP](liquid-xp-58.1.1.jar) Unloaded->Constructed
    LogisticsPipes{0.8.2.89} [Logistics Pipes](logisticspipes-0.8.2.89-dev.jar) Unloaded->Errored
    Mantle{1.7.10-0.3.1.jenkins180} [Mantle](Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed
    McMultipart{1.1.0.309} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed
    ForgeMicroblock{1.1.0.309} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed
    AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
    Mantle Environment: Environment healthy.
    Launched Version: 1.7.10-Forge10.13.2.1277
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.3621, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by bziemons** [comment]
Please redownload the mod from our Jenkins and check back.
