### ISSUE TITLE
No idea

### ISSUE THREAD

**Issue by TheSlimeMan** [RS485/LogisticsPipes#548]
## So... This happened while I was loading my custom modpack....

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 1/10/15 1:48 PM
Description: Initializing game

java.lang.RuntimeException: LogisticsPipes could not find its class transformer. If you are running MC from an IDE make sure to copy the 'LogisticsPipes_dummy.jar' to your mods folder. If you are running MC normal please report this as a bug at 'https://github.com/RS485/LogisticsPipes/issues'.
    at logisticspipes.LogisticsPipes.<init>(LogisticsPipes.java:177)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:173)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:486)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at logisticspipes.LogisticsPipes.<init>(LogisticsPipes.java:177)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:173)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:486)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 183602808 bytes (175 MB) / 458326016 bytes (437 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:MaxPermSize=2048m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 135 mods loaded, 135 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{7.10.85.1277} [Forge Mod Loader](forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed
    Forge{10.13.2.1277} [Minecraft Forge](forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed
    appliedenergistics2-core{rv2-beta-7} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed
    NotEnoughItems{1.0.3.62} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.62-universal.jar) Unloaded->Constructed
    OpenModsCore{0.6} [OpenModsCore](minecraft.jar) Unloaded->Constructed
    battlegear2{1.0.6.1} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.6.1.jar) Unloaded->Constructed
    hearts{1.0} [Hearts]([1.7.10][1.7.2] Heart Crystal 1.0 %281%29.zip) Unloaded->Constructed
    DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed
    AetherCraft{1.4.5.68} [AetherCraft](AetherCraft-1.7.10-1.4.5.68.jar) Unloaded->Constructed
    appliedenergistics2{rv2-beta-7} [Applied Energistics 2](appliedenergistics2-rv2-beta-7.jar) Unloaded->Constructed
    Artifacts{1.0.5} [Artifacts](Artifacts-1.0.5.jar) Unloaded->Constructed
    Backpack{2.0.0} [Backpack](backpack-2.0.0-1.7.x.jar) Unloaded->Constructed
    BiblioCraft{1.9.2} [BiblioCraft](BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1004-universal.jar) Unloaded->Constructed
    IC2{2.2.660-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.660-experimental.jar) Unloaded->Constructed
    CoFHCore{1.7.10R3.0.0B6} [CoFH Core](CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded->Constructed
    BuildCraft|Core{6.3.1} [BuildCraft](buildcraft-6.3.1.jar) Unloaded->Constructed
    Forestry{3.3.0.6} [Forestry for Minecraft](forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed
    BinnieCore{2.0-pre3} [Binnie Core](binnie-mods-2.0-pre3.jar) Unloaded->Constructed
    Botany{2.0-pre3} [Botany](binnie-mods-2.0-pre3.jar) Unloaded->Constructed
    ExtraBees{2.0-pre3} [Extra Bees](binnie-mods-2.0-pre3.jar) Unloaded->Constructed
    ExtraTrees{2.0-pre3} [Extra Trees](binnie-mods-2.0-pre3.jar) Unloaded->Constructed
    Genetics{2.0-pre3} [Genetics](binnie-mods-2.0-pre3.jar) Unloaded->Constructed
    qmunitylib{1.0} [QmunityLib](QmunityLib-1.7.10-0.1.69-universal.jar) Unloaded->Constructed
    bluepower{0.2.835} [Blue Power](BluePower-1.7.10-0.2.835-universal.jar) Unloaded->Constructed
    Botania{r1.2-124} [Botania](Botania r1.2-124.jar) Unloaded->Constructed
    redgear_core{2.1.5} [Red Gear Core](RedGearCore-1.7.10-2.1.5.jar) Unloaded->Constructed
    redgear_brewcraft{1.2.2} [Brewcraft](Brewcraft-1.7.10-1.2.2.jar) Unloaded->Constructed
    cslib{1.7.10-2.7.2} [Clashsoft Lib](ClashsoftLib-1.7.10-2.7.2.jar) Unloaded->Constructed
    brewingapi{1.7.10-3.0.2} [Brewing API](BrewingAPI-1.7.10-3.0.2.jar) Unloaded->Constructed
    BuildCraft|Transport{6.3.1} [BC Transport](buildcraft-6.3.1.jar) Unloaded->Constructed
    BuildCraft|Silicon{6.3.1} [BC Silicon](buildcraft-6.3.1.jar) Unloaded->Constructed
    BuildCraft|Builders{6.3.1} [BC Builders](buildcraft-6.3.1.jar) Unloaded->Constructed
    BuildCraft|Energy{6.3.1} [BC Energy](buildcraft-6.3.1.jar) Unloaded->Constructed
    BuildCraft|Factory{6.3.1} [BC Factory](buildcraft-6.3.1.jar) Unloaded->Constructed
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed
    CompactSolars{4.4.39.315} [Compact Solar Arrays](CompactSolars-1.7.10-4.4.39.315-universal.jar) Unloaded->Constructed
    ComputerCraft{1.64} [ComputerCraft](ComputerCraft1.64.jar) Unloaded->Constructed
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed
    craftingpillars{1.6} [CraftingPillars Mod](CraftingPillars-1.7.2-1.6 %281%29.jar) Unloaded->Constructed
    DeadlyWorld{1.0.2} [Deadly World](Deadly-World-Mod-1.7.10 %281%29.jar) Unloaded->Constructed
    dualhotbar{1.5.1} [Dual Hotbar](dualhotbar-1.7.10-1.5.1.jar) Unloaded->Constructed
    DynamicLights{1.3.7} [Dynamic Lights](DynamicLights-1.7.10.jar) Unloaded->Constructed
    DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module](DynamicLights-1.7.10.jar) Unloaded->Constructed
    DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](DynamicLights-1.7.10.jar) Unloaded->Constructed
    DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module](DynamicLights-1.7.10.jar) Unloaded->Constructed
    DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed
    DynamicLights_mobEquipment{1.0.7} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed
    DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed
    DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light](DynamicLights-1.7.10.jar) Unloaded->Constructed
    DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed
    DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed
    Eln{43} [Electrical Age](ElectricalAge_BETA-1.9_r43.jar) Unloaded->Constructed
    eplus{1.7.10-3.0.1} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.1.jar) Unloaded->Constructed
    tlhpoeCore{1.7} [TLHPoE Core](TLHPoE-Core-1.7.10 %281%29.jar) Unloaded->Constructed
    enderrepositories{1.4} [Ender Repositories](Ender-Repositories-Mod-1.7.10 %281%29.jar) Unloaded->Constructed
    EnderIO{1.7.10-2.1.4.247} [Ender IO](EnderIO-1.7.10-2.1.4.247.jar) Unloaded->Constructed
    EnderStorage{1.4.5.24} [EnderStorage](EnderStorage-1.7.10-1.4.5.24-universal.jar) Unloaded->Constructed
    EnderZoo{1.7.10-1.0.7.16} [Ender Zoo](EnderZoo-1.7.10-1.0.7.16.jar) Unloaded->Constructed
    EnhancedInventories{1.7.10-1.0.2} [Enhanced Inventories](EnhancedInventories-1.7.10-1.0.2.jar) Unloaded->Constructed
    exnihilo{1.37} [Ex Nihilo](Ex-Nihilo-1.37.jar) Unloaded->Constructed
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed
    ThermalExpansion{1.7.10R4.0.0B5} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B5-13.jar) Unloaded->Constructed
    exastris{For 1.7.10} [Ex Astris](Ex-Astris-1.12.jar) Unloaded->Constructed
    ForgeMultipart{1.1.0.307} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.307-universal.jar) Unloaded->Constructed
    ExtraUtilities{1.2.1} [Extra Utilities](extrautilities-1.2.1.jar) Unloaded->Constructed
    farlanders{1.2b} [The Farlanders](farlanders-1.7.10-v1.2b.jar) Unloaded->Constructed
    Steamcraft{0.27.3} [Flaxbeard's Steam Power](Flaxbeard'sSteamPower-1.7.10-0.27.3.jar) Unloaded->Constructed
    flora{1.0} [Fluids and Liquids on Ridiculous Armor](FLORA-1.0.5.jar) Unloaded->Constructed
    fossil{1.7.10 Build 7.0.1} [Fossils and Archeology Revival](Fossils_Archeology_Revival-1.7.10_Build-7.0.1.jar) Unloaded->Constructed
    ganysend{1.8.7} [Gany's End](Ganys End-1.8.7 %281%29.jar) Unloaded->Constructed
    ganysnether{1.7.7} [Gany's Nether](Ganys Nether-1.7.7.jar) Unloaded->Constructed
    tnb_gildedarmor{1.1} [TNB Gilded Armor](Gilded-Armor-Mod-1.7.10 %281%29.jar) Unloaded->Constructed
    tnbcraftingrecipes{1.0} [TNB Useful Crafting Recipes](Gilded-Armor-Mod-1.7.10 %281%29.jar) Unloaded->Constructed
    Growthcraft{2.1.0a} [Growthcraft](growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed
    Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar](growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed
    Growthcraft|Apples{2.1.0} [Growthcraft Apples](growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed
    Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo](growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed
    Growthcraft|Bees{2.1.0} [Growthcraft Bees](growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed
    Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap](growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed
    Growthcraft|Grapes{2.1.0} [Growthcraft Grapes](growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed
    Growthcraft|Hops{2.1.0} [Growthcraft Hops](growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed
    Growthcraft|Rice{2.1.0a} [Growthcraft Rice](growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed
    IC2NuclearControl{2.0.8c} [Nuclear Control 2](IC2NuclearControl-2.0.8c.jar) Unloaded->Constructed
    infiniteinvo{1.0.19} [InfiniteInvo](InfiniteInvo-1.0.19.jar) Unloaded->Constructed
    LunatriusCore{1.1.2.14} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.14-universal.jar) Unloaded->Constructed
    InGameInfoXML{2.8.1.61} [InGame Info XML](InGameInfoXML-1.7.10-2.8.1.61-universal.jar) Unloaded->Constructed
    Waila{1.5.5} [Waila](Waila-1.5.5_1.7.10.jar) Unloaded->Constructed
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed
    LogisticsPipes{0.8.2.89} [Logistics Pipes](logisticspipes-0.8.2.89-dev.jar) Unloaded->Errored
    lootbags{1.3.3} [Loot Bags](LootBags-1.7.10-1.3.3.jar) Unloaded->Constructed
    lycanitesmobs{1.10.4.4 - MC 1.7.10} [Lycanites Mobs](LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed
    arcticmobs{1.10.4.4 - MC 1.7.10} [Lycanites Arctic Mobs](LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed
    demonmobs{1.10.4.4 - MC 1.7.10} [Lycanites Demon Mobs](LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed
    desertmobs{1.10.4.4 - MC 1.7.10} [Lycanites Desert Mobs](LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed
    forestmobs{1.10.4.4 - MC 1.7.10} [Lycanites Forest Mobs](LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed
    freshwatermobs{1.10.4.4 - MC 1.7.10} [Lycanites Freshwater Mobs](LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed
    infernomobs{1.10.4.4 - MC 1.7.10} [Lycanites Inferno Mobs](LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed
    junglemobs{1.10.4.4 - MC 1.7.10} [Lycanites Jungle Mobs](LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed
    mountainmobs{1.10.4.4 - MC 1.7.10} [Lycanites Mountain Mobs](LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed
    plainsmobs{1.10.4.4 - MC 1.7.10} [Lycanites Plains Mobs](LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed
    saltwatermobs{1.10.4.4 - MC 1.7.10} [Lycanites Saltwater Mobs](LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed
    shadowmobs{1.10.4.4 - MC 1.7.10} [Lycanites Shadow Mobs](LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed
    swampmobs{1.10.4.4 - MC 1.7.10} [Lycanites Swamp Mobs](LycanitesMobsComplete 1.10.4.4 [1.7.10].jar) Unloaded->Constructed
    magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops](magicalcrops-1.7.2-0.11.jar) Unloaded->Constructed
    minestrappolation{1.7.10-3.3.4} [Minestrappolation](Minestrappolation-1.7.10-3.3.4.jar) Unloaded->Constructed
    cfm{3.4.7} [§9MrCrayfish's Furniture Mod](MrCrayfishs-Furniture-Mod-1.7.10.jar) Unloaded->Constructed
    MutantCreatures{1.4.8} [Mutant Creatures](MutantCreatures-1.7.10-1.4.8.jar) Unloaded->Constructed
    mwaw{1.7.10-0.0.4} [Elemental Witch Mod](mwaw-1.7.10-0.0.4.jar) Unloaded->Constructed
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-285.jar) Unloaded->Constructed
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-532.jar) Unloaded->Constructed
    harvestcraft{1.7.10b} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10b.jar) Unloaded->Constructed
    ProjectE{1.7.10-0.2d-dev13} [ProjectE](ProjectE-1.7.10-0.2d-dev13.jar) Unloaded->Constructed
    ProjRed|Core{4.5.1.51} [ProjectRed](ProjectRed-Base-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    ProjRed|Transmission{4.5.1.51} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    ProjRed|Transportation{4.5.1.51} [ProjectRed-Transportation](ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    ProjRed|Exploration{4.5.1.51} [ProjectRed-Exploration](ProjectRed-World-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    ProjRed|Compatibility{4.5.1.51} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    ProjRed|Integration{4.5.1.51} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    ProjRed|Illumination{4.5.1.51} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    ProjRed|Expansion{4.5.1.51} [ProjectRed-Expansion](ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar) Unloaded->Constructed
    RandomThings{2.1.7} [Random Things](RandomThings-2.1.7.jar) Unloaded->Constructed
    simplyjetpacks{1.2.0} [Simply Jetpacks](SimplyJetpacks-MC1.7.10-1.2.0.jar) Unloaded->Constructed
    SolarFlux{1.7.10-0.5a} [Solar Flux](SolarFlux-1.7.10-0.5a.jar) Unloaded->Constructed
    SpecialMobs{3.0.3} [Special Mobs](SpecialMobs-1.7.10-3.0.3.jar) Unloaded->Constructed
    telepads{1.6.4 v5} [Teleportation Pads](Telepads-1.7.2_1.7.jar) Unloaded->Constructed
    elysium{1.0} [The Elysium](TheElysium-1.7.X-1.0 %281%29.jar) Unloaded->Constructed
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed
    WailaHarvestability{1.1.1} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.1.jar) Unloaded->Constructed
    McMultipart{1.1.0.307} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.307-universal.jar) Unloaded->Constructed
    denseores{1.0} [Dense Ores](denseores-1.4.2.jar) Unloaded->Constructed
    ForgeMicroblock{1.1.0.307} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.307-universal.jar) Unloaded->Constructed
    OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:ENABLED],[map_gen_fix:ENABLED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
    AE2 Version: beta rv2-beta-7 for Forge 10.13.2.1230
    Launched Version: 1.7.10-Forge10.13.2.1277
    LWJGL: 2.9.1
    OpenGL: GeForce 8800 GTX/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Sphax PureBDcraft 128x MC18.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by TheSlimeMan** [comment]
I even took out the texture pack...

**Comment by Tsunayoshi** [comment]
LP#89 is not BC6.3 compatible right now. We have to wait for an update, but davboecki has less time at the moment. May take a litte bit.

**Comment by bziemons** [comment]
Firstly that and secondly: redownload the LP build.
