### ISSUE TITLE
Game crashes after attaching a supplier pipe to a kinetic wind generator - possible fix #408 not implemented yet?

### ISSUE THREAD

**Issue by IXArcanumXI** [RS485/LogisticsPipes#550]
Our game (build 0.8.2.89) crashes every time we try to attach a supplier pipe to a kinetic wind generator with a rotor under 99%. I know there was a similiar issue here: https://github.com/RS485/LogisticsPipes/issues/408
Since it should be fixed by https://github.com/RS485/LogisticsPipes/commit/14a53c5354c621807cecaa33d44c5b6e8388db77 I wanted to ask whether this fix is implemented or not?

If not - is there any schedule for it or can you explain how to implement this fix on our own?

Thanks!

Here's our error log:

Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.IllegalArgumentException: Item Damage out of range
    at logisticspipes.utils.item.ItemIdentifier.get(ItemIdentifier.java:237) ~[ItemIdentifier.class:0.8.2.89]
    at logisticspipes.utils.item.ItemIdentifier.get(ItemIdentifier.java:255) ~[ItemIdentifier.class:0.8.2.89]
    at logisticspipes.utils.InventoryUtil.getItemsAndCount(InventoryUtil.java:61) ~[InventoryUtil.class:0.8.2.89]
    at logisticspipes.modules.ModuleActiveSupplier.createSupplyRequest(ModuleActiveSupplier.java:312) ~[ModuleActiveSupplier.class:0.8.2.89]
    at logisticspipes.modules.ModuleActiveSupplier.tick(ModuleActiveSupplier.java:222) ~[ModuleActiveSupplier.class:0.8.2.89]
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:423) ~[CoreRoutedPipe.class:0.8.2.89]
    at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145845_h(LogisticsTileGenericPipe.java:180) ~[LogisticsTileGenericPipe.class:0.8.2.89]
    at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
    ... 4 more
[21:41:38] [Server thread/ERROR]: This crash report has been saved to: D:\Server 1.7.10 Forge 1235.\crash-reports\crash-2015-01-12_21.41.38-server.txt

**Comment by davboecki** [comment]
This problem got fixed in the current 0.9 versions of LP: https://github.com/RS485/LogisticsPipes/commit/14a53c5354c621807cecaa33d44c5b6e8388db77. Problem was that the fix needed some experimental coding so it wasn't something that could go into 0.8 as a bug fix.

**Comment by IXArcanumXI** [comment]
Thanks for your answer :) As I can't see any 0.9 versions on your jenkins-page, am I right the 0.9 versions are not released yet and will probably need Buildcraft 6.3.0? Thanks a lot!

**Comment by hron84** [comment]
@davboecki and couldn't we blacklist temporary the problematic block to avoid accidental crashes?

**Comment by bziemons** [comment]
Anything that has damage values over 65 000 may cause problems

**Comment by dimensionsintime** [comment]
Might be seeing same issue (damage value out of range) when placing an IC2 Iron Turning Blank into a chest with an attached chassis containing a poly module. Crashes the moment I place blank in chest or insert poly module into attached chassis.

**Comment by davboecki** [comment]
The IC2 turbine stuff is the probelm causing the crash in LP.

**Comment by ghost** [comment]
Same with connecting provider to AE interface (Infinity pack LP 0.8.3.108), is there a way to get the version 0.9 and change it to let the server think it's 0.8.3.108, so players could log in without have to add the mod ?

**Comment by davboecki** [comment]
implemented in 0.8 as well now.
