### ISSUE TITLE
Build #91 crashes on startup with NoClassDefFoundError: net/minecraft/client/renderer/RenderBlocks

### ISSUE THREAD

**Issue by tyjen** [RS485/LogisticsPipes#555]
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/RenderBlocks
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_25]
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_25]
        at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:1.8.0_25]
        at java.lang.Class.getMethods(Unknown Source) ~[?:1.8.0_25]
        at jogisticspipes.asm.wrapper.LogisticsWrapperHandler.getWrappedProxy(LogisticsWrapperHandler.java:208) ~[LogisticsWrapperHandler.class:0.8.3.90]
        at logisticspipes.proxy.ProxyManager.getWrappedProxy(ProxyManager.java:74) ~ ProxyManager.class:0.8.3.90]
        at logisticspipes.proxy.ProxyManager.load(ProxyManager.java:84) ~[ProxyManager.class:0.8.3.90]
        at logisticspipes.LogisticsPipes.postInit(LogisticsPipes.java:357) ~[LogisticsPipes.class:0.8.3.90]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
Caused by: java.lang.RuntimeException: Attempted to load class blm for invalid side SERVER
        at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50) ~[forge-1.7.10-10.13.2.1240-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
        ... 39 more

**Comment by Hazado** [comment]
Got the same crash - http://pastebin.com/w38LfWyS

**Comment by Shadowhunter82** [comment]
Got the same crash,  Serverside ONLY  
- http://pastebin.com/B6R6R71G
