### ISSUE TITLE
 crash - Ticking block entity with bc6.3.3 and lp.93

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#559]
using  lp.93 with bc6.3.3 I get the following exception on loading my world...

.92 worked but had very low fps

---

java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
    at logisticspipes.proxy.buildcraft.subproxies.LPBCPluggableState.isDirty(LPBCPluggableState.java:38)
    at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145845_h(LogisticsTileGenericPipe.java:224)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 9 more
Caused by: java.lang.NullPointerException

**Comment by Ioandar** [comment]
#560 has full pastebin... I am closing this
