### ISSUE TITLE
NPE when placing adjacent logistics pipes

### ISSUE THREAD

**Issue by Cisien** [RS485/LogisticsPipes#56]
Minecraft 1.5.1
Forge 674
Buildcraft Jenkins 126
LogisticsPipes 406

This specific exception his hit when starting the server after placing two builder pipes next to each other

2013-04-26 21:45:30 [SEVERE] [Minecraft-Server] Encountered an unexpected exception ReportedException
net.minecraft.util.ReportedException: Ticking tile entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:657)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:274)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:570)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:468)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
Caused by: java.lang.NoSuchMethodError: buildcraft.transport.Pipe.isPipeConnected(Lnet/minecraft/tileentity/TileEntity;Lnet/minecraftforge/common/Forg
eDirection;)Z
        at logisticspipes.pipes.basic.CoreRoutedPipe.isPipeConnected(CoreRoutedPipe.java:723)
        at logisticspipes.proxy.buildcraft.BuildCraftProxy.checkPipesConnections(BuildCraftProxy.java:102)
        at logisticspipes.routing.PathFinder.getConnectedRoutingPipes(PathFinder.java:192)
        at logisticspipes.routing.PathFinder.getConnectedRoutingPipes(PathFinder.java:50)
        at logisticspipes.routing.ServerRouter.recheckAdjacent(ServerRouter.java:303)
        at logisticspipes.routing.ServerRouter.checkAdjacentUpdate(ServerRouter.java:672)
        at logisticspipes.routing.ServerRouter.update(ServerRouter.java:736)
        at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:320)
        at buildcraft.transport.TileGenericPipe.func_70316_g(TileGenericPipe.java:188)
        at net.minecraft.world.World.func_72939_s(World.java:2196)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:546)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:651)

**Comment by davboecki** [comment]
You need to use build craft 3.5.0. The newest Jenkins version doesn't work.
