### ISSUE TITLE
ClassCastException when building a Galacticraft compressor in a request table.

### ISSUE THREAD

**Issue by StarkRG** [RS485/LogisticsPipes#566]
Don't know whether this is a problem with LP (0.8.3.94) or Galacticraft (3.0.8.257), but I received this while trying to build a Galacticraft compressor in an LP request table.

```
java.lang.ClassCastException: logisticspipes.blocks.crafting.FakePlayer cannot be cast to net.minecraft.client.entity.EntityPlayerSP
    at micdoodle8.mods.galacticraft.core.items.ItemBlockMachine.func_77622_d(ItemBlockMachine.java:101)
    at net.minecraft.item.ItemStack.func_77980_a(ItemStack.java:387)
    at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:53)
    at net.minecraft.inventory.SlotCrafting.func_82870_a(SlotCrafting.java:110)
    at logisticspipes.pipes.PipeBlockRequestTable.getOutput(PipeBlockRequestTable.java:275)
    at logisticspipes.pipes.PipeBlockRequestTable.getResultForClick(PipeBlockRequestTable.java:300)
    at logisticspipes.gui.orderer.GuiRequestTable$1.getResultForClick(GuiRequestTable.java:108)
    at logisticspipes.utils.gui.HandelableSlot.getProvidedStack(HandelableSlot.java:23)
    at logisticspipes.utils.gui.DummyContainer.func_75144_a(DummyContainer.java:509)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
    at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:503)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
    at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452)
    at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
    at logisticspipes.utils.gui.LogisticsBaseGuiScreen.func_73864_a(LogisticsBaseGuiScreen.java:303)
    at logisticspipes.gui.orderer.GuiRequestTable.func_73864_a(GuiRequestTable.java:551)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at logisticspipes.utils.gui.LogisticsBaseGuiScreen.handleMouseInputSub(LogisticsBaseGuiScreen.java:241)
    at logisticspipes.gui.orderer.GuiRequestTable.handleMouseInputSub(GuiRequestTable.java:557)
    at logisticspipes.utils.gui.LogisticsBaseGuiScreen.func_146274_d(LogisticsBaseGuiScreen.java:236)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by davboecki** [comment]
Please report this to Galacticraft. There is nothing I can do to fix this.

**Comment by hron84** [comment]
@davboecki A galacticraft guy says there can be a problem on your side too. Could you please respond to it?

**Comment by davboecki** [comment]
Cilent Player also have network connections and other stuff a FakePlayer doesn't have so I decided to use the EntityPlayer class as a base and not the client side Player.
