### ISSUE TITLE
0.8.3.100 errors with Buildcraft 6.3.6

### ISSUE THREAD

**Issue by Hakker** [RS485/LogisticsPipes#577]
cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: buildcraft.api.transport.PipeManager.registerPipePluggable(Ljava/lang/Class;Ljava/lang/String;)V
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoSuchMethodError: buildcraft.api.transport.PipeManager.registerPipePluggable(Ljava/lang/Class;Ljava/lang/String;)V
    at buildcraft.BuildCraftTransport.init(BuildCraftTransport.java:461)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    ... 5 more

**Comment by SonOfTheStars** [comment]
I´m Sorry to say, Logistics Pipes is not jet Complatible with 6.3.6.
The Latest compatible version is 6.3.2...
But it will be Compatible with 6.3.6 soon ;)

**Comment by Hakker** [comment]
I figured as such I only mentioned it so it might help you out :)

**Comment by davboecki** [comment]
This shouldn't be caused by LP at all. Looks more like a mod is shipping parts of the BC api and hasn't updated jet. LP doesn't ship any part of BC.
