### ISSUE TITLE
Game Crash when using logistic pipe straight out of BC quarry

### ISSUE THREAD

**Issue by Zauo** [RS485/LogisticsPipes#579]
the quarry builds its self fine but when the drill comes out to mine blocks the game crashes and when you try get back into the world it crashes again so the world becomes un-usable.

---- Minecraft Crash Report ----
// You're mean.

Time: 16/02/15 16:01
Description: Ticking block entity

java.lang.AbstractMethodError: logisticspipes.pipes.basic.LogisticsTileGenericPipe.injectItem(Lnet/minecraft/item/ItemStack;ZLnet/minecraftforge/common/util/ForgeDirection;Lbuildcraft/api/core/EnumColor;)I
    at buildcraft.core.utils.Utils.addToRandomInjectableAround(Utils.java:188)
    at buildcraft.factory.BlockMiner.mineStack(BlockMiner.java:53)
    at buildcraft.factory.BlockMiner.acceptEnergy(BlockMiner.java:103)
    at buildcraft.factory.TileQuarry.dig(TileQuarry.java:231)
    at buildcraft.factory.TileQuarry.func_145845_h(TileQuarry.java:189)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Hope this helps!

**Comment by hron84** [comment]
Could you please paste the version infos from your crashlog? It is about the end of the file (right after this exception)

**Comment by davboecki** [comment]
IIRC thiy only happens if you don't use the newest LP version.

**Comment by Zauo** [comment]
Im using FTB Infinty. 
and the version infos

-- Head --
Stacktrace:
	at buildcraft.core.utils.Utils.addToRandomInjectableAround(Utils.java:188)
	at buildcraft.factory.BlockMiner.mineStack(BlockMiner.java:53)
	at buildcraft.factory.BlockMiner.acceptEnergy(BlockMiner.java:103)
	at buildcraft.factory.TileQuarry.dig(TileQuarry.java:231)
	at buildcraft.factory.TileQuarry.func_145845_h(TileQuarry.java:189)

-- Block entity being ticked --
Details:
	Name: Machine // buildcraft.factory.TileQuarry
	Block type: ID #1170 (tile.machineBlock // buildcraft.factory.BlockQuarry)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (55,71,677), Chunk: (at 7,4,5 in 3,42; contains blocks 48,0,672 to 63,255,687), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Actual block type: ID #1170 (tile.machineBlock // buildcraft.factory.BlockQuarry)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: PERM
	All players: 1 total; [EntityPlayerMP['leadmagnet69'/579, l='PERM', x=56.56, y=72.00, z=675.24]]
	Chunk stats: ServerChunkCache: 1074 Drop: 0
	Level seed: 8577929072706765190
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (320,64,196), Chunk: (at 0,4,4 in 20,12; contains blocks 320,0,192 to 335,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4385288 game time, 4385288 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 156838 (now: false), thunder time: 4240 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Zauo** [comment]
FTB infinity didn't update the mod but when i did it manually it is now working, thanks!
