### ISSUE TITLE
RF Provider issue

### ISSUE THREAD

**Issue by RikuSS4** [RS485/LogisticsPipes#595]
I updated thermal expansion mod and now the RF provider no longer works properly. EnderIO conduits spam a null pointer error when connected and Mekanism universal cable placed next to it crashes the server with:
[FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$ServerTickEvent@49554545:
java.lang.NullPointerException
    at logisticspipes.blocks.powertile.LogisticsRFPowerProviderTileEntity.receiveEnergy(LogisticsRFPowerProviderTileEntity.java:69) ~[LogisticsRFPowerProviderTileEntity.class:0.8.3.103]
    at mekanism.common.EnergyNetwork.getAcceptors(EnergyNetwork.java:261) ~[EnergyNetwork.class:?]
    at mekanism.common.EnergyNetwork.doEmit(EnergyNetwork.java:176) ~[EnergyNetwork.class:?]
    at mekanism.common.EnergyNetwork.tickEmit(EnergyNetwork.java:148) ~[EnergyNetwork.class:?]
    at mekanism.common.EnergyNetwork.onUpdate(EnergyNetwork.java:359) ~[EnergyNetwork.class:?]
    at mekanism.api.transmitters.DynamicNetwork.tick(DynamicNetwork.java:305) ~[DynamicNetwork.class:?]
    at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:85) ~[TransmitterNetworkRegistry.class:?]
    at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:73) ~[TransmitterNetworkRegistry.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_409_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) [FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

I am using forge version 1291. LP 0.8.3.103.

**Comment by Ioandar** [comment]
I have an LogisticsRFPowerProvider related issue too

with old TE all works fine  (forge1291, LP103, bc6.4, forestry471)

after update to new TE release I get this on entering world
-> crash -> http://pastebin.com/E2BhsJTF

I have an RF Power Provider in that world. It provides RF-Power to various machines in my LP network.

I started a new world again and could not find the RF Power Provider in NEI... Only the recipe for the EU Power Provider is shown. The recipes for the RF modules (that go on the LP Pipe that is connected to the machine) are still shown in NEI. Only the RF Provider Block is missing...

**Comment by Ioandar** [comment]
tried again with a new world and only exception LP related I could find is this

http://pastebin.com/fRJV922y

(forge1291, LP103, bc6.4, forestry471,TE RC2-129)

**Comment by crunkazcanbe** [comment]
It's like people refuse to acknowledge that the new cofh mods broke with lp . I had to drop lp out of my pack considering its a rf only based pack .

**Comment by davboecki** [comment]
fixed
