### ISSUE TITLE
Disabled BCProxy for Mod: BuildCraft|Transport. Cause was an Exception

### ISSUE THREAD

**Issue by AT611** [RS485/LogisticsPipes#611]
java.lang.ClassCastException: logisticspipes.pipes.basic.LogisticsTileGenericPipe cannot be cast to buildcraft.transport.TileGenericPipe
        at buildcraft.robots.DockingStation.getPipe(DockingStation.java:54)
        at buildcraft.robots.DockingStation.takeAsMain(DockingStation.java:111)
        at buildcraft.transport.BlockGenericPipe.func_149727_a(BlockGenericPipe.java:678)
        at logisticspipes.proxy.buildcraft.BuildCraftProxy.handleBCClickOnPipe(BuildCraftProxy.java:391)
        at logisticspipes.asm.wrapper.BCProxyWrapper.handleBCClickOnPipe(.LP|ASM.dynamic:182)
        at logisticspipes.pipes.basic.LogisticsBlockGenericPipe.func_149727_a(LogisticsBlockGenericPipe.java:721)
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[09:05:56] [Server thread/FATAL] [LogisticsPipes]: Disabled BCProxy for Mod: BuildCraft|Transport. Cause was an Exception

Happens only at the server, when trying to place a robot on a docking station, which is placed onto a logistics pipe. Robot remains in my hands, chat message pops up, all LP pipes' connections shown red. Could not reproduce it in my singleplayer.
Forge 1291, LP 108, BC 6.4.3. Modified FTB's direwolf20 pack (only added Logistics Pipes and updated BC), if it is anyhow related.

**Comment by SonOfTheStars** [comment]
Probably has to do something with the Interaction of LP and BC-Gates. Since Robot Stations are Quite Unique.
For now, if you want a robot Inserting into your LP-Network, you can put the station on a regular BC Pipe and connect that to a Basic Pipe. That will do the Job for you Until we Investigated the Issue.

**Comment by davboecki** [comment]
Currently it looks like we can't fix this. Only by disabling support for Robot stations on LP pipes.

**Comment by hron84** [comment]
@davboecki it would be a good workaround as it would prevent at least crashes.
