### ISSUE TITLE
IC2 specific items + Chest + Provider pipe -> Crash

### ISSUE THREAD

**Issue by SyDr** [RS485/LogisticsPipes#612]
1) Chest with "Iron Turning Blank" (or "Wooden Turning Blank")
2) Attach provider pipe
3) Crash (or pipe removed if "error tiles remove" enabled in forge).

``` java
java.lang.IllegalArgumentException: Item Damage out of range
    at logisticspipes.utils.item.ItemIdentifier.get(ItemIdentifier.java:237)
    at logisticspipes.utils.item.ItemIdentifier.get(ItemIdentifier.java:255)
    at logisticspipes.utils.InventoryUtil.getItems(InventoryUtil.java:79)
    at logisticspipes.pipes.PipeItemsProviderLogistics.getSpecificInterests(PipeItemsProviderLogistics.java:429)
    at logisticspipes.routing.ServerRouter.updateInterests(ServerRouter.java:996)
    at logisticspipes.routing.ServerRouter.update(ServerRouter.java:871)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:378)
    at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145845_h(LogisticsTileGenericPipe.java:188)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/issues/600
