### ISSUE TITLE
Itemsink on Barrel crash

### ISSUE THREAD

**Issue by Buchsbaumi** [RS485/LogisticsPipes#682]
I'm getting the following exception (and a broken world because of it) while placing a 1024x Barrel from Barrels Mod 3.5 above a MK2 Chassi with an item-sink and provider module in it.
The funny thing is: the first 3 Barrels I placed this way didn't crash.

java.lang.NullPointerException: Ticking block entity
    at need4speed402.mods.barrels.TileEntityBarrel.getInventorySize(TileEntityBarrel.java:365)
    at need4speed402.mods.barrels.TileEntityBarrel.getMaxStoredCount(TileEntityBarrel.java:1363)
    at logisticspipes.proxy.specialinventoryhandler.DSUInventoryHandler.roomForItem(DSUInventoryHandler.java:121)
    at logisticspipes.proxy.specialinventoryhandler.DSUInventoryHandler.roomForItem(DSUInventoryHandler.java:111)
    at logisticspipes.modules.ChassiModule.sinksItem(ChassiModule.java:71)
    at logisticspipes.logistics.LogisticsManager.canSink(LogisticsManager.java:167)
    at logisticspipes.logistics.LogisticsManager.getBestReply(LogisticsManager.java:119)
    at logisticspipes.logistics.LogisticsManager.hasDestination(LogisticsManager.java:73)
    at logisticspipes.pipes.basic.CoreRoutedPipe.hasDestination(CoreRoutedPipe.java:1542)
    at logisticspipes.pipes.basic.CoreRoutedPipe.hasDestination(CoreRoutedPipe.java:132)
    at logisticspipes.modules.ModuleAdvancedExtractor.checkExtract(ModuleAdvancedExtractor.java:178)
    at logisticspipes.modules.ModuleAdvancedExtractor.tick(ModuleAdvancedExtractor.java:169)
    at logisticspipes.modules.ChassiModule.tick(ChassiModule.java:119)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:450)
    at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145845_h(LogisticsTileGenericPipe.java:196)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Buchsbaumi** [comment]
forgot to mention: 
MC 1.7.10 
forge 10.13.3.1401-1710ls
used 0.8.3.119 originally, tried 0.8.3.121 and 0.9.0.104

and tile.null looks interesting:
Details:
    Name: logisticspipes.pipes.basic.LogisticsTileGenericPipe // logisticspipes.pipes.basic.LogisticsTileGenericPipe
    Block type: ID #974 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (486,62,898), Chunk: (at 6,3,2 in 30,56; contains blocks 480,0,896 to 495,255,911), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
    Actual block type: ID #974 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
    Actual block data value: 0 / 0x0 / 0b0000
    LP-Version: 0.9.0.104:false
    Pipe: logisticspipes.pipes.PipeLogisticsChassiMk2
    Transport: logisticspipes.transport.PipeTransportLogistics
    Router: ServerRouter: {ID: 52, UUID: 1bb8d3f5-3184-4d35-9854-8d0c724f7e7f, AT: (0, 486, 62, 898), Version: 40), Destroied: false}
    stillNeedReplace: false
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

**Comment by bziemons** [comment]
Sorry, but this is not our fault. We use the DSU api the right way. 
You should report this to the mod author of your Barrels mod.

**Comment by hron84** [comment]
Guys, a little tip for the future: please add ``` before and after pasted code, so it can be formatted differently.
