### ISSUE TITLE
Crashing with BC 7.0.5 RC

### ISSUE THREAD

**Issue by magik6k** [RS485/LogisticsPipes#685]
Logistics pipes built from mc17-0.9-bc7 branch(which seems to be sort of outdated) started to crach clients after entering the world:

```
java.lang.NoSuchMethodError: buildcraft.transport.render.FacadeRenderHelper.pipeFacadeRenderer(Lnet/minecraft/client/renderer/RenderBlocks;Lbuildcraft/api/core/render/ITextureStates;Lbuildcraft/transport/TileGenericPipe;Lbuildcraft/transport/PipeRenderState;III)V
    at logisticspipes.proxy.buildcraft.BuildCraftProxy.pipeFacadeRenderer(BuildCraftProxy.java:455)
    at logisticspipes.asm.wrapper.BCProxyWrapper.pipeFacadeRenderer(.LP|ASM.dynamic:202)
    at logisticspipes.renderer.LogisticsPipeWorldRenderer.renderPipe(LogisticsPipeWorldRenderer.java:138)
    at logisticspipes.renderer.LogisticsPipeWorldRenderer.renderWorldBlock(LogisticsPipeWorldRenderer.java:193)
    at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
    at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
    at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
    at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
    at fastcraft.a.m.a(F:82)
    at fastcraft.Hooks.t(F:157)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

This is most likely due to [this](https://github.com/BuildCraft/BuildCraft/commit/580886a8cc0ab5fe367733a0d9ce00b2eba6e90b#diff-cd4dea9e9b6ad81a573054d510dea0b0L99) change in BC

**Comment by SonOfTheStars** [comment]
Logistics Pipes is not Yet compatible with Buildcraft 7.0.x Beta. A compatible Version is in the workings, but first, there needs to be Stuff sorted out, new Content created and old functionality improved within the 0.9 Branch.

Please be Patient.

**Comment by bziemons** [comment]
The branch does not even build in it's current state. There cannot be any compatible LP build with BC7 right now. As of that, I do not see a reason for an issue. Of course there will be compatibility in the near future.

**Comment by hron84** [comment]
"Of course there will be compatibility in the near future."

I am very happy to read this. :smile:
