### ISSUE TITLE
LP 0.10 needs CodeChickenLib

### ISSUE THREAD

**Issue by maqwek** [RS485/LogisticsPipes#695]
When I try to run LP 0.10 with stable BC 7.0.5 I have "cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/lib/vec/Transformation". Installing CodeChickenLib fixes this error.

Full error log:
--- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 07.06.15 11:14
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/lib/vec/Transformation
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: codechicken/lib/vec/Transformation
    at logisticspipes.renderer.LogisticsRenderPipe.<clinit>(LogisticsRenderPipe.java:81)
    at logisticspipes.proxy.side.ClientProxy.registerTileEntities(ClientProxy.java:101)
    at logisticspipes.LogisticsPipes.postInit(LogisticsPipes.java:495)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: codechicken.lib.vec.Transformation
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 39 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 4.0.4-303.fc22.x86_64
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 179400696 bytes (171 MB) / 338300928 bytes (322 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 12 mods loaded, 12 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    FML{7.10.85.1291} [Forge Mod Loader](forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Forge{10.13.2.1291} [Minecraft Forge](forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Core{7.0.6} [BuildCraft](buildcraft-7.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Builders{7.0.6} [BC Builders](buildcraft-7.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Energy{7.0.6} [BC Energy](buildcraft-7.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Factory{7.0.6} [BC Factory](buildcraft-7.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Silicon{7.0.6} [BC Silicon](buildcraft-7.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Transport{7.0.6} [BC Transport](buildcraft-7.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Robotics{7.0.6} [BC Robotics](buildcraft-7.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Compat{7.0.3} [BuildCraft Compat](buildcraft-compat-7.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    LogisticsPipes{0.10.0.1} [Logistics Pipes](logisticspipes-0.10.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored

**Comment by loordgek** [comment]
not a bug lp needs ccc for rendering stuff

**Comment by loordgek** [comment]
@theZorro266 can you add to jenkins that lp needs ccc?

**Comment by bziemons** [comment]
I would say it still is a bug, because there are ways to declare a dependency. We might just have forgotten to do that.

**Comment by davboecki** [comment]
I think the best way to handle this would be to revert to the old renderer if the CodeChickenLib wasn't found. That way we don't force people to use it.

**Comment by SonOfTheStars** [comment]
@davboecki thats probably the best Way!

**Comment by davboecki** [comment]
OK, hard-dependency is gone. And it now also trys to use the one packed with CoFH.
