### ISSUE TITLE
Right clicking a pipe empty handed causes BuildCraft|Transport to be disabled

### ISSUE THREAD

**Issue by trienow** [RS485/LogisticsPipes#704]
### How:

I right clicked a Logistics Pipe empty handed. It does not happen every time though.
### Versions:
- LogisticsPipes: v.0.9.1.15
- Buildcraft: v.7.0.9
- Forge: v.10.13.3.1407
### Forge Log:

Note: The logs only seem to differ in line  `4`
##### Trying to find cause No. 1 & 4

``` javascript
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at buildcraft.transport.BlockGenericPipe.func_149727_a(BlockGenericPipe.java:674)
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.proxy.buildcraft.BuildCraftProxy.handleBCClickOnPipe(BuildCraftProxy.java:398)
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.asm.wrapper.BCProxyWrapper.handleBCClickOnPipe(.LP|ASM.dynamic:172)
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.pipes.basic.LogisticsBlockGenericPipe.func_149727_a(LogisticsBlockGenericPipe.java:856)
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[09:06:34] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[09:06:34] [Server thread/FATAL] [LogisticsPipes/]: Disabled BCProxy for Mod: BuildCraft|Transport. Cause was an Exception
```
##### Trying to find cause No. 2

``` javascript
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at buildcraft.transport.BlockGenericPipe.func_149727_a(BlockGenericPipe.java:674)
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.proxy.buildcraft.BuildCraftProxy.handleBCClickOnPipe(BuildCraftProxy.java:398)
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.asm.wrapper.BCProxyWrapper.handleBCClickOnPipe(.LP|ASM.dynamic:232)
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.pipes.basic.LogisticsBlockGenericPipe.func_149727_a(LogisticsBlockGenericPipe.java:856)
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[10:12:23] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[10:12:23] [Server thread/FATAL] [LogisticsPipes/]: Disabled BCProxy for Mod: BuildCraft|Transport. Cause was an Exception
```
##### Trying to find cause No. 3

``` javascript
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at buildcraft.transport.BlockGenericPipe.func_149727_a(BlockGenericPipe.java:674)
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.proxy.buildcraft.BuildCraftProxy.handleBCClickOnPipe(BuildCraftProxy.java:398)
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.asm.wrapper.BCProxyWrapper.handleBCClickOnPipe(.LP|ASM.dynamic:242)
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at logisticspipes.pipes.basic.LogisticsBlockGenericPipe.func_149727_a(LogisticsBlockGenericPipe.java:856)
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[10:23:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[10:23:36] [Server thread/FATAL] [LogisticsPipes/]: Disabled BCProxy for Mod: BuildCraft|Transport. Cause was an Exception
```

**Comment by davboecki** [comment]
This is a buildcraft bug.
https://github.com/BuildCraft/BuildCraft/issues/2798
