### ISSUE TITLE
Windows can't create files like COM8.info / COM7.info ...

### ISSUE THREAD

**Issue by COM8** [RS485/LogisticsPipes#775]
Problem:
you can't create a file on a Windows pc like COM8/COM7/...info and LogisticPipes try's to because my ingame name is COM8 to save some stuff in it.

Possible solution:
Don't use ingame names for this it would be better to use the UUID or something else :D.
So everybody can play again without crashes.

Crash Report:
cpw.mods.fml.common.LoaderException: java.io.FileNotFoundException: D:\Fabian\Documents\Curse\Minecraft\Instances\COMCRAFT 4.6\saves\Comcraft4Map\logisticspipes\names\COM8.info (Das System kann die angegebene Datei nicht finden)
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.serverStopping(Loader.java:809)
    at cpw.mods.fml.common.FMLCommonHandler.handleServerStopping(FMLCommonHandler.java:289)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.io.FileNotFoundException: D:\Fabian\Documents\Curse\Minecraft\Instances\COMCRAFT 4.6\saves\Comcraft4Map\logisticspipes\names\COM8.info (Das System kann die angegebene Datei nicht finden)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
    at logisticspipes.config.PlayerConfig.writeToFile(PlayerConfig.java:157)
    at logisticspipes.LogisticsEventListener.serverShutdown(LogisticsEventListener.java:303)
    at logisticspipes.LogisticsPipes.cleanup(LogisticsPipes.java:543)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.serverStopping(Loader.java:808)
    ... 3 more

**Comment by bziemons** [comment]
yeah, we already talked about using the UUIDs in the future.
