### ISSUE TITLE
Crash on request of items with wood from fuzzy crafting table

### ISSUE THREAD

**Issue by Casper-O** [RS485/LogisticsPipes#784]
- logisticspipes-0.9.2.22
- forge-1.7.10-10.13.4.1448
- buildcraft-7.0.18
- buildcraft-compat-7.0.10

Yesterday I added 4 new mods to my pack of nice stuff, and when I requested a Piston or chest that is both made with a fuzzy crafting table and crafting pipe upgrade my game shutdown and gives me the following error in console

https://gist.github.com/Casper-O/89678de51db0acdf159d

the mods I installed is the following:
- MrCrayfishFurnitureModv3.4.8(1.7.10)
- GraviSuite-1.7.10-2.0.3
- binnie-mods-2.0-pre14
- adv-repulsion-systems-59.0.3

**Comment by SonOfTheStars** [comment]
Fuzzy Crafting ATM is BEYOND BROKEN...

**Comment by Casper-O** [comment]
Interesting since I'm pretty sure it worked fine until I added the above mentioned mods, since I did not update LP or BC.

I found some other issues with Binnie mod, like fluids not having a "correct name". Will do some testing tonight to maybe validate it.

**Comment by hron84** [comment]
If I were you, I'd blame Binnie's stuff too. It causes a lot of issues around crafting.

**Comment by SonOfTheStars** [comment]
Nope this is Purely LP Fuzzy being BROKEN @hron84

**Comment by tswear** [comment]
i have the EXACT same crash, only with crafting pipes in general, i have binnie mods in common with the OP, same exact crash. i hope its not binnie mods causing this catastrophe

**Comment by hron84** [comment]
@tswear could you check it crafting works w/o binnie mods?

**Comment by tswear** [comment]
it does work without the binnie mods suite for me, with it it crashes with the aformentioned error

**Comment by oninoni** [comment]
This is a real Problem for me cause i cant craft anything with fuzzy in my modpack... (Yes binnies is in) This should really be looked into

**Comment by oninoni** [comment]
23:22:45 CONSOLE: thread/ERROR] [FML]: PacketInboundHandler exception
23:22:45 CONSOLE: count needed, promises not needed.
23:22:45 CONSOLE: thread/ERROR] [FML]: There was a critical exception handling a packet on channel LogisticsPipes
23:22:45 CONSOLE: count needed, promises not needed.

This is the Output of the Server Console. Client says nothing at all...

**Comment by oninoni** [comment]
OK it definitly does not happen always...

**Comment by oninoni** [comment]
Ok? So the Item can be requested by chained crafting but if you request it directly it crashes???

**Comment by Casper-O** [comment]
The biggest issue here, seems to be that many (including me) likes Binnie mods, but for some reason there have not been any life signs from him for a long time, or did I oversee anything?

Since the mod source is not open, nobody can pick it up and continue the good work

**Comment by tswear** [comment]
i heard that the earlier 1.7.10 LP versions don't have this problem, anyone can confirm this? i heard that a FTB pack once upgraded from one version to another caused this to happen, which means one version should still work with or without binniemods. my dedicated server just bricked after adding supplier modules to the smeltery, and its the same darn error every startup now, ill post an error snippet of this particular error
[crash-2015-12-15_11.29.59-server.txt](https://github.com/RS485/LogisticsPipes/files/63048/crash-2015-12-15_11.29.59-server.txt)
It is a hosthorde server and it has not given any trouble until the updates were done DX
Edit: oh no, binniemods isnt in the mods folder when the crash happens, that means it isnt binnie related either :(
Edit 2: sorry if this counts as a new topic, it seems to be the same error as the OP, but if i need a new ticket made for this crash report, i will move it to a new post.

**Comment by taisph** [comment]
I am seeing this crash as well. It was working with several fuzzy tables and crafting pipes initially and it was only when I started moving the pipes and tables to a new location it started to break. As soon as oredict is enabled on planks in a crafting pipe with the fuzzy upgrade, it'll crash on request with the server output as below.

I'm using FTB Infinity Evolved 2.2.2, Minecraft 1.7.10.

```
[21:56:02] [Server thread/ERROR] [FML/]: PacketInboundHandler exception
java.lang.IllegalArgumentException: zero count needed, promises not needed.
    at logisticspipes.request.RequestTreeNode.addPromise(RequestTreeNode.java:119) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.modules.ModuleProvider.canProvide(ModuleProvider.java:250) ~[ModuleProvider.class:0.9.3.70]
    at logisticspipes.pipes.PipeLogisticsChassi.canProvide(PipeLogisticsChassi.java:479) ~[PipeLogisticsChassi.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode.checkProvider(RequestTreeNode.java:288) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:57) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode.getSubRequests(RequestTreeNode.java:609) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode.access$100(RequestTreeNode.java:37) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode$CraftingSorterNode.calculateMaxWork(RequestTreeNode.java:536) ~[RequestTreeNode$CraftingSorterNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode$CraftingSorterNode.addWorkPromisesToTree(RequestTreeNode.java:553) ~[RequestTreeNode$CraftingSorterNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode.checkCrafting(RequestTreeNode.java:482) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:65) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:40) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.request.RequestTree.<init>(RequestTree.java:43) ~[RequestTree.class:0.9.3.70]
    at logisticspipes.request.RequestTree.request(RequestTree.java:177) ~[RequestTree.class:0.9.3.70]
    at logisticspipes.request.RequestTree.request(RequestTree.java:202) ~[RequestTree.class:0.9.3.70]
    at logisticspipes.request.RequestHandler.request(RequestHandler.java:48) ~[RequestHandler.class:0.9.3.70]
    at logisticspipes.network.packets.orderer.RequestSubmitPacket.processPacket(RequestSubmitPacket.java:29) ~[RequestSubmitPacket.class:0.9.3.70]
    at logisticspipes.network.PacketInboundHandler.channelRead0(PacketInboundHandler.java:21) ~[PacketInboundHandler.class:0.9.3.70]
    at logisticspipes.network.PacketInboundHandler.channelRead0(PacketInboundHandler.java:16) ~[PacketInboundHandler.class:0.9.3.70]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[21:56:02] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel LogisticsPipes
java.lang.IllegalArgumentException: zero count needed, promises not needed.
    at logisticspipes.request.RequestTreeNode.addPromise(RequestTreeNode.java:119) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.modules.ModuleProvider.canProvide(ModuleProvider.java:250) ~[ModuleProvider.class:0.9.3.70]
    at logisticspipes.pipes.PipeLogisticsChassi.canProvide(PipeLogisticsChassi.java:479) ~[PipeLogisticsChassi.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode.checkProvider(RequestTreeNode.java:288) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:57) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode.getSubRequests(RequestTreeNode.java:609) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode.access$100(RequestTreeNode.java:37) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode$CraftingSorterNode.calculateMaxWork(RequestTreeNode.java:536) ~[RequestTreeNode$CraftingSorterNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode$CraftingSorterNode.addWorkPromisesToTree(RequestTreeNode.java:553) ~[RequestTreeNode$CraftingSorterNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode.checkCrafting(RequestTreeNode.java:482) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:65) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:40) ~[RequestTreeNode.class:0.9.3.70]
    at logisticspipes.request.RequestTree.<init>(RequestTree.java:43) ~[RequestTree.class:0.9.3.70]
    at logisticspipes.request.RequestTree.request(RequestTree.java:177) ~[RequestTree.class:0.9.3.70]
    at logisticspipes.request.RequestTree.request(RequestTree.java:202) ~[RequestTree.class:0.9.3.70]
    at logisticspipes.request.RequestHandler.request(RequestHandler.java:48) ~[RequestHandler.class:0.9.3.70]
    at logisticspipes.network.packets.orderer.RequestSubmitPacket.processPacket(RequestSubmitPacket.java:29) ~[RequestSubmitPacket.class:0.9.3.70]
    at logisticspipes.network.PacketInboundHandler.channelRead0(PacketInboundHandler.java:21) ~[PacketInboundHandler.class:0.9.3.70]
    at logisticspipes.network.PacketInboundHandler.channelRead0(PacketInboundHandler.java:16) ~[PacketInboundHandler.class:0.9.3.70]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by jeckhart** [comment]
I can reproduce this consistently using a fuzzy crafting table with a recipe for a chest using oak planks where each plank is set to OreDict and a crafting pipe with the fuzzy crafting card installed. As soon as I try to craft a chest it disconnects me.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/ce7e4d7e0a03e03f9a527371f70d2d55764df339

**Comment by Casper-O** [comment]
I cant wait to test this! It has been a pain in the butt for so long!
