### ISSUE TITLE
HUD Goggles Crash

### ISSUE THREAD

**Issue by Flow86** [RS485/LogisticsPipes#79]
```
java.lang.NullPointerException
    at logisticspipes.gui.hud.HUDSatellite.cursorOnWindow(HUDSatellite.java:153)
    at logisticspipes.renderer.LogisticsHUDRenderer.handleCursor(LogisticsHUDRenderer.java:298)
    at logisticspipes.renderer.LogisticsHUDRenderer.renderWorldRelative(LogisticsHUDRenderer.java:173)
    at logisticspipes.ticks.RenderTickHandler.tickEnd(RenderTickHandler.java:78)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
    at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:377)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:872)
    at net.minecraft.client.Minecraft.run(Minecraft.java:759)
    at java.lang.Thread.run(Unknown Source)
```

(latest build 445)

**Comment by Flow86** [comment]
perhaps some "upgrade" bug? (since I hade some nullpointerexceptions in the initial serverstart too, but they went away)

**Comment by davboecki** [comment]
Fixed.
