### ISSUE TITLE
There was a critical exception handling a packet on channel LogisticsPipes java.lang.IllegalArgumentException: zero count needed, promises not needed.

### ISSUE THREAD

**Issue by wormzjl** [RS485/LogisticsPipes#881]
This happens when I tries to craft some stuff on the server, then the client was kicked and I got the following error in the console

Full log:
https://gist.github.com/wormzjl/368f1c985a834479672b

[05:00:57] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel LogisticsPipes
java.lang.IllegalArgumentException: zero count needed, promises not needed.
    at logisticspipes.request.RequestTreeNode.addPromise(RequestTreeNode.java:119) ~[RequestTreeNode.class:0.9.3.69]
    at logisticspipes.modules.ModuleProvider.canProvide(ModuleProvider.java:250) ~[ModuleProvider.class:0.9.3.69]
    at logisticspipes.pipes.PipeLogisticsChassi.canProvide(PipeLogisticsChassi.java:479) ~[PipeLogisticsChassi.class:0.9.3.69]
    at logisticspipes.request.RequestTreeNode.checkProvider(RequestTreeNode.java:288) ~[RequestTreeNode.class:0.9.3.69]
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:57) ~[RequestTreeNode.class:0.9.3.69]
    at logisticspipes.request.RequestTreeNode.getSubRequests(RequestTreeNode.java:609) ~[RequestTreeNode.class:0.9.3.69]
    at logisticspipes.request.RequestTreeNode.access$100(RequestTreeNode.java:37) ~[RequestTreeNode.class:0.9.3.69]
    at logisticspipes.request.RequestTreeNode$CraftingSorterNode.calculateMaxWork(RequestTreeNode.java:536) ~[RequestTreeNode$CraftingSorterNode.class:0.9.3.69]
    at logisticspipes.request.RequestTreeNode$CraftingSorterNode.addWorkPromisesToTree(RequestTreeNode.java:553) ~[RequestTreeNode$CraftingSorterNode.class:0.9.3.69]
    at logisticspipes.request.RequestTreeNode.checkCrafting(RequestTreeNode.java:482) ~[RequestTreeNode.class:0.9.3.69]
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:65) ~[RequestTreeNode.class:0.9.3.69]
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:40) ~[RequestTreeNode.class:0.9.3.69]
    at logisticspipes.request.RequestTree.<init>(RequestTree.java:43) ~[RequestTree.class:0.9.3.69]
    at logisticspipes.request.RequestTree.request(RequestTree.java:177) ~[RequestTree.class:0.9.3.69]
    at logisticspipes.request.RequestTree.request(RequestTree.java:202) ~[RequestTree.class:0.9.3.69]
    at logisticspipes.request.RequestHandler.request(RequestHandler.java:48) ~[RequestHandler.class:0.9.3.69]
    at logisticspipes.network.packets.orderer.RequestSubmitPacket.processPacket(RequestSubmitPacket.java:29) ~[RequestSubmitPacket.class:0.9.3.69]
    at logisticspipes.network.PacketInboundHandler.channelRead0(PacketInboundHandler.java:21) ~[PacketInboundHandler.class:0.9.3.69]
    at logisticspipes.network.PacketInboundHandler.channelRead0(PacketInboundHandler.java:16) ~[PacketInboundHandler.class:0.9.3.69]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1492.152]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by hron84** [comment]
Could you tell us a bit more? E.g. it happens at every crafting, or only with specific recipes? It is a consistent, reproducible crash? Did you tried to craft the problematic recipe with a vanilla crafting table? It happens with autocrafting or with Request Table?

**Comment by wormzjl** [comment]
I've used a fuzzy crafting table+mk3 crafting pipe with fuzzy upgrade to craft a chest using oredict recipe
Seem that it happens to all items with this setup, and happens when I presse the request button

**Comment by hron84** [comment]
Ohh, I see. Thanks for your answer, it will help to find the point of failure

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/ce7e4d7e0a03e03f9a527371f70d2d55764df339
