### ISSUE TITLE
Server and Client Crash with newest version.

### ISSUE THREAD

**Issue by Aeper** [RS485/LogisticsPipes#901]
two players on my world crash the server with this issue. Ive been unable to figure it out. we are using the newest version of the FTB Infinity Evolved pack on expert mode.

Caused by: java.io.EOFException
    at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
    at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
    at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
    at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
    at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
    at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:29)
    at logisticspipes.config.PlayerConfig.readFromFile(PlayerConfig.java:124)
    at logisticspipes.LogisticsEventListener.getPlayerConfig(LogisticsEventListener.java:312)
    at logisticspipes.LogisticsEventListener.onPlayerLogout(LogisticsEventListener.java:201)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_718_LogisticsEventListener_onPlayerLogout_PlayerLoggedOutEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    ... 9 more 

Full Log below
http://pastebin.com/k4ZFwn1m

**Comment by hron84** [comment]
Could you please add bit more details? What did you do when this crash happened?

**Comment by SonOfTheStars** [comment]
Both client and Server Crashed at the same time?

What did you do to producte this Crash?
Is it reproducable? Is it a one-time Error?

**Comment by Aeper** [comment]
Cause of crash was when either one of two certain players joined. I'm still unsure of how this happened.

Yes, Crash was preventing two of my players from playing. It would crash clients and the server. we managed to get them playing again when we removed the mod. just so you know the crash did repeat regardless. With the same crash log.

The only clients that would not crash are other players online. they would get the error of server disconnected basically.

I'm going to look into re adding the mod tonight possibly so i can we can get the same issue again.

**Comment by Aeper** [comment]
Incase this helps. Both users were using the logiistics pipes system with the storage drawers system.

**Comment by davboecki** [comment]
For what ever reason the game couldn't load the config file. I can't tell you how they got corrupted. Not much I can do about it because this is using minecrafts way of saving NBT Data to a file. Remove the LP config file for the players. Then they shoudl eb able to join again with LP installed.
