### ISSUE TITLE
NPE with Crating Module GUI

### ISSUE THREAD

**Issue by Turmfalke2** [RS485/LogisticsPipes#917]
hi,
When ever I try to change to satellite pipe id in a crafting module I get kicked from the server/thrown back to the main menu.

http://pastebin.com/2qFgpVrc

buildcraft-7.1.14.jar
logisticspipes-0.9.3.70.jar

**Comment by davboecki** [comment]
```
[17/2/2016 18:32:31 PM] java.lang.NullPointerException
[17/2/2016 18:32:31 PM]     at logisticspipes.modules.ModuleCrafter.getRouter(ModuleCrafter.java:368) ~[ModuleCrafter.class:0.9.3.70]
[17/2/2016 18:32:31 PM]     at logisticspipes.modules.ModuleCrafter.getNextConnectSatelliteId(ModuleCrafter.java:608) 
```

This is an NPE

**Comment by Turmfalke2** [comment]
minimal test setup:
![lp_bug](https://cloud.githubusercontent.com/assets/5174562/13154983/d5e78dee-d67b-11e5-9c6e-3bdc480ab875.png)
The pipe on the left side is set to id 1 and the one on the right to id 2.

**Comment by loordgek** [comment]
you can do it but dont hold the module in your hand, put it in a chassie pipe and then give it a sat pipe

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/f7619011bd4c9ed54395db48566839344685a16f
