### ISSUE TITLE
Hey, don't get routers for pipes that aren't ready - Log Spam

### ISSUE THREAD

**Issue by Sir-Will** [RS485/LogisticsPipes#926]
Getting spammed with this errors:

```
[07:05:41] [Server thread/INFO]: Hey, don't get routers for pipes that aren't ready
[07:05:41] [Server thread/WARN]: java.lang.Throwable
[07:05:41] [Server thread/WARN]:    at logisticspipes.pipes.basic.CoreRoutedPipe.getRouter(CoreRoutedPipe.java:825)
[07:05:41] [Server thread/WARN]:    at logisticspipes.pipes.basic.CoreRoutedPipe.getRouterId(CoreRoutedPipe.java:1389)
[07:05:41] [Server thread/WARN]:    at logisticspipes.proxy.td.LPItemDuct.canRouteItem(LPItemDuct.java:41)
[07:05:41] [Server thread/WARN]:    at cofh.thermaldynamics.duct.attachments.servo.ServoItem.findRouteForItem(ServoItem.java:347)
[07:05:41] [Server thread/WARN]:    at cofh.thermaldynamics.duct.attachments.servo.ServoItem.getRouteForItem(ServoItem.java:441)
[07:05:41] [Server thread/WARN]:    at cofh.thermaldynamics.duct.attachments.servo.ServoItem.handleItemSending(ServoItem.java:273)
[07:05:41] [Server thread/WARN]:    at cofh.thermaldynamics.duct.attachments.servo.ServoItem.tick(ServoItem.java:189)
[07:05:41] [Server thread/WARN]:    at cofh.thermaldynamics.duct.item.ItemGrid.tickGrid(ItemGrid.java:58)
[07:05:41] [Server thread/WARN]:    at cofh.thermaldynamics.core.WorldGridList.tickEnd(WorldGridList.java:63)
[07:05:41] [Server thread/WARN]:    at cofh.thermaldynamics.core.TickHandler.tick(TickHandler.java:95)
[07:05:41] [Server thread/WARN]:    at cpw.mods.fml.common.eventhandler.ASMEventHandler_798_TickHandler_tick_WorldTickEvent.invoke(.dynamic)
[07:05:41] [Server thread/WARN]:    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[07:05:41] [Server thread/WARN]:    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[07:05:41] [Server thread/WARN]:    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:259)
[07:05:41] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:974)
[07:05:41] [Server thread/WARN]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[07:05:41] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[07:05:41] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[07:05:41] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
```

**Comment by bziemons** [comment]
Did you chunkload every part of your LP network?

**Comment by Sir-Will** [comment]
It's on a server with 300+ players, so I have no idea where and how it is setup.

**Comment by bziemons** [comment]
We will do something about the log spam, but we cannot guarantee that a Logistics Pipes System functions perfectly without chunkloading it.

**Comment by Sir-Will** [comment]
Thanks, better one pipe doesn't work then the complete server.

**Comment by davboecki** [comment]
It's just a message nothing to worry about. No real exception inside the game.

**Comment by hron84** [comment]
If the log fills the underlying disk (quota), the server can stop working. Spamming a log can cause problems where the disk (quota) is low.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/93f57ea87050594e37f1536d9fa8e6ac225d793e
