### ISSUE TITLE
Disabled BC proxy with BC 7.1.15+

### ISSUE THREAD

**Issue by FuuNoKamiOka** [RS485/LogisticsPipes#938]
I just added this to a custom modpack I made through the Curse Launcher and I can't see recipes through NEI and any and all recipes I've found on the net don't work. I saw videos showing recipes for 1.7.10 that work and show up in NEI. Do I need to add a core mod or is something bugged? FYI, I have the latest version of both according to the Launcher.

**Comment by davboecki** [comment]
You need buildcraft for recipes to work.

**Comment by FuuNoKamiOka** [comment]
I have buildcraft. I even added some addons hoping that would help. it did not. I don't know how to fix it. :/

**Comment by davboecki** [comment]
Please list your mod versions.

**Comment by FuuNoKamiOka** [comment]
Buildcraft: 7.1.15
Buildcraft Additions: 2.2.5
Buildcraft Compat: 7.1.3
Logistics Pipes: 0.9.3.99

All are updated as per the Curse Launcher.

**Comment by davboecki** [comment]
Could you also post your log as https://gist.github.com/
I suspect that LP currently doesn't work with Buildcraft: 7.1.15. Only Buildcraft: 7.1.14

**Comment by Revemohl** [comment]
That seems to be the case indeed, I was running into the same problem but as soon as I went back to BC 7.1.14 the recipes started working properly again.

**Comment by FuuNoKamiOka** [comment]
Here is the gist for the log: https://gist.github.com/FuuNoKamiOka/9af8b8e3e5337cc4ae50

If it helps, I am watching Direwolf20 play on an Infinity Skyblock map and he has it working and it looks different from the items in the version I downloaded.

**Comment by bziemons** [comment]
You do not have BuildCraft robotics installed?

**Comment by FuuNoKamiOka** [comment]
I do not. Is that needed for the pipes? There are so many addons and sitch I wasn't sure if anything was needed.

**Comment by bziemons** [comment]
> BuildCraft|Core, BuildCraft|Transport, BuildCraft|Silicon, BuildCraft|Robotics

Those are the required BuildCraft submods. Right now we still have BuildCraft as a dependency and we did not consider writing specific proxies for each of the BuildCraft submods.

**Comment by FuuNoKamiOka** [comment]
Good to know. Maybe that should be a thing to put in with the mod that they are all required. It's not made clear.

**Comment by Revemohl** [comment]
I don't think that's issue here, as I'm running the entire buildcraft-7.1.15.jar file (which contains all modules, as far as I know) and I still get no recipes. As I mentioned previously, going back to buildcraft-7.1.14.jar makes recipes work again.
Here's my fml-client-latest.log gist as well in case you need it: https://gist.github.com/Revemohl/00b8b56acc93b2301e0a (I tried it on a quick test instance, but reverting BC's version fixed the problem in my main instance too).

**Comment by davboecki** [comment]
The robot placement event was moved inside the api. No idea why 7.1.14 even works correctly. Just need to compile against the new version and fix that event access.

**Comment by FuuNoKamiOka** [comment]
Yeah. I meant to post something last night that said adding all those other mods did nothing. Still having problems. I will admit, though, that the TE upgrades from LPs works fine. It's just all the other ones that don't work.

**Comment by asiekierka** [comment]
Oh, yeah! We did that because a server admin requested it, admittedly.

**Comment by davboecki** [comment]
https://github.com/RS485/LogisticsPipes/commit/9840006c11b4e520f00349242a4dd623b5496c3e

**Comment by HadesDurin** [comment]
updated today to latest 1.7.10 aviable logistic pipes version 0.9.0.3.124
and during gameplay got this:
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.transport.TravelingItem.writeToNBT(TravelingItem.java:188)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.transport.PipeTransportItems.writeToNBT(PipeTransportItems.java:452)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at buildcraft.transport.Pipe.writeToNBT(Pipe.java:164)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.proxy.buildcraft.subproxies.LPBCTileGenericPipe.writeToNBT_LP(LPBCTileGenericPipe.java:73)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.asm.wrapper.generated.BCTilePartProxyWrapper.writeToNBT_LP(.LP|ASM.dynamic:152)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145841_b(LogisticsTileGenericPipe.java:337)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mcp.mobius.waila.api.impl.DataAccessorCommon.getNBTData(DataAccessorCommon.java:113)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at tterrag.wailaplugins.plugins.PluginIFluidHandler.getBody(PluginIFluidHandler.java:37)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at tterrag.wailaplugins.plugins.PluginBase.getWailaBody(PluginBase.java:148)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mcp.mobius.waila.api.impl.MetaDataProvider.handleBlockTextData(MetaDataProvider.java:158)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:87)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_953_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:52:05] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:52:05] [Client thread/FATAL] [LogisticsPipes/]: Disabled BCProxy for Mod: BuildCraft|Transport+BuildCraft|Silicon+BuildCraft|Robotics. Cause was an Exception
using latest aviable buildcraft build 7.1.16 and bc compat 7.1.5
