### ISSUE TITLE
Mod Confliction

### ISSUE THREAD

**Issue by ArcticApril** [RS485/LogisticsPipes#950]
2016-03-27 18:18:57,143 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-03-27 18:18:57,147 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[18:18:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:18:57] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:18:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[18:18:57] [main/INFO] [FML]: Forge Mod Loader version 11.15.1.1808 for Minecraft 1.8.9 loading
[18:18:57] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Users\Noah\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25
[18:18:57] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2016-03-27 18:18:57,761 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-03-27 18:18:57,810 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-03-27 18:18:57,815 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[18:18:57] [main/INFO] [ExtraUtils2CoreMod]: Extra Utils 2 Core Mod - Successfully loaded
[18:18:57] [main/WARN] [FML]: The coremod com.olafski.fastleafdecay.FldLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:18:57] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.lang.ClassLoader.defineClass1(Native Method)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.security.AccessController.doPrivileged(Native Method)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.lang.Class.forName0(Native Method)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at java.lang.Class.forName(Class.java:344)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:536)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:416)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:246)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[18:18:58] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:18:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
[18:18:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[18:18:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[18:18:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[18:18:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:     ... 23 more
[18:18:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NullPointerException
[18:18:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[18:18:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:     ... 25 more
[18:18:58] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at C:\Users\Noah\Documents\Curse\Minecraft\Instances\1.8.9 Survival V2 for Forge Mod Loader
java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455) ~[?:1.8.0_25]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_25]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367) ~[?:1.8.0_25]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
    at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
    at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:536) ~[forge-1.8.9-11.15.1.1808.jar:?]
    at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:416) ~[forge-1.8.9-11.15.1.1808.jar:?]
    at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:246) ~[forge-1.8.9-11.15.1.1808.jar:?]
    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95) [forge-1.8.9-11.15.1.1808.jar:?]
    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72) [forge-1.8.9-11.15.1.1808.jar:?]
    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.8.9-11.15.1.1808.jar:?]
    at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119) [forge-1.8.9-11.15.1.1808.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    ... 23 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    ... 23 more
Exception in thread "main" [18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.ClassLoader.defineClass1(Native Method)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.security.AccessController.doPrivileged(Native Method)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.Class.forName0(Native Method)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.Class.forName(Class.java:344)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:536)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:416)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:246)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[18:18:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:    ... 23 more
[18:18:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NullPointerException
[18:18:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[18:18:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]:     ... 25 more

This error occurs when Minecraft is launched with the following mods:
agricraft-2.0.0a
Aroma1997Core-1.8.9-1.0.4.1
Aroma1997s-Dimensional-World-1.8.9-1.1.2.0
AromaBackup-1.8.9-0.0.1.1.b26
BloodMagic-1.8.9-2.0.0-20
Bookshelf-API-1.8.9-2.3.7
buildcraft-7.2.3
buildcraft-compat-7.2.0
chiselsandbits-8.6
ComputerCraft1.79pr1
deepresonance-1.8.9-1.1.4beta19
denseores-1.8-alpha-2.0.3
ElecCore-1.8.9-1.4.247
EnderCompass-1.8.9-1.2.2
extrautils2-1.8.9-alpha-0.0.2
FastLeafDecay-1.8-1.6
FoodDetails-1.8.9-1.0.0
hardcoreWither-1.8.9-1.1.1-16-universal
inventorypets-1.8.9-1.4.0
InventoryTweaks-1.60-40
IronBackpacks-1.8.9-2.0.5
ironchest-1.8.9-6.0.125.770
jei_1.8.9-2.28.9.176
JEIAddons_1.8.9-0.12.0.57
journeymap-1.8.9-5.1.5-unlimited
JustEnoughResources-1.8.9-0.4.0
logisticspipes-0.9.3.104
Mantle-1.8.9-0.9.2
MCA-1.8.9-5.1.2-universal
mcjtylib-1.8.9-1.8.1beta10
MCMultiPart-1.0.8-universal
MmmMmmMmmMmm-1.9b
ModularPowersuits-1.8.9-0.11.0-003
NeoTech-1.8.9-2.4.4
Numina-0.5.0-001
OreDictionaryConverter-1.7.2
OverpoweredInventory-1.8.9-2.1.0
ProjectE-1.8.9-PE1.1.4
Psi-beta-23
PsiProducts-1.0.0
RadixCore-1.8.9-2.1.0-universal
rftools-1.8.9-4.23beta35
RouterReborn-1.8.9-3.0.5.14b_universal
SoulShards-TOW-1.8.9-2.2.8-16
TConstruct-1.8.9-2.2.0b
Thaumcraft-1.8.9-5.2.4
Waila-1.6.0-B3_1.8.8
worldedit-forge-mc1.8.9-6.1.1
Xp-Stacker-1.8.9-1.0

If you can't fix this issue, then at least point me to what other mod is causing this.
Also, this only became a problem when I added Logistics Pipes to the pack, hence why I put this here.

**Comment by ArcticApril** [comment]
Ok, this is odd.
Just started making a personal tech pack and the same thing happened.
Curious, I tried with only LP and BC. Still the same result.
I assume that there might be something wrong with my download or it is conflicting with my version of forge, 11.15.1.1808.
This is also all done through the Curse launcher, if that provides any help at all.

**Comment by Obbi89** [comment]
You are using Minecraft Forge for 1.8.9.
As far as I know Logistics is still for Minecraft 1.7.10.
So no this will not work ever.
Either wait for 1.8 releases of Logisitics Pipe and Buildcraft or downgrade your Modpack.

**Comment by davboecki** [comment]
There is no LP version for MC 1.8.x yet
