### ISSUE TITLE
Crafting progress viewing disappears 

### ISSUE THREAD

**Issue by Dijkstra1-zz** [RS485/LogisticsPipes#973]
I have the upgrade on my crafting table that lets me see what is crafting well when it is working, it will work for so long and then it will not work so up any crafting task until I restart the server.

**Comment by hron84** [comment]
Could you give us some more info about your system? A LP version, what mods are you using along with it, how your setup looks like... you know, help us to drill down to the problem.

**Comment by hron84** [comment]
Also, maybe it is related to #970

**Comment by Dijkstra1-zz** [comment]
@hron84 I do not think it is related to #970, as for other mods mods I am playing FTB infinity evolved, the current version of Logistics Pipes being used is 0.9.3.114, as for how I am using my Logistics Pipes is I my stuff store in stowage drawer connected by the controller, using an mk5 chaise, with an polymorphic itemsink, provider and oredic modules for ingots, nuggets, blocks and other recourse, so that four oredics modules every thing else is stored in 7 or 8 diamond chest each with an mk4 four pipes with an itemsink module set to default route and an provider module. That the storage done all other pipes are routed pipes or basic Logistics Pipes and junctions. Then there crafting part a big wall of LP crafting tables, about 4 or 5 tall spanning at least 2 chunks each with its own crafting pipe, I also have three carpenters with craft pipes and fluid satellite, two rollers from railcraft with crafting pipes, and hand rull of TE and IC2 machines with mk5 pipes with many crafting modules, also have mk1 pipes with extractor module one six industrial apiary (is there an extractor if so i can not find it) and the combs sent to supplier pipe on an centrifuge, ore are also on a supplier pipe to a rock crusher and taken out with an mk1 pipe with an extractor module there is also crafting an crafting pipe on the rock crusher for crushed obsidian, crushed ore are supplied with and active supplier module to an ore washer (would have thought passive would have worked, but does not) in an mk4 pipe with and extractor module, then I have the laser crafting i have three assembly tables each on its own satellite with an mk5 pipe on an chest touching all three with crafting modules to send items to right  satellite also the chest has one crafting pipe one it for a recipe that need more than items to send to the satellite. I think that everything, well that I can remember seems pretty complete, if you like pictures of my set-up, or an video flying around it that will take a bit more time so if you would like pictures pleases ask. 

Edit:
I do not know what triggers it but after while after i request stuff and icons on left hand side of do not show up to show the craft progress. That reminds I have one of the request crafting tables, near my chest.

**Comment by hron84** [comment]
I think developers would appreciate pictures about buggy setups in nearly any time. It helps to drill down to the problem. 

I thought it could be related because the other guy has similar crafting progress problem, and even if the symptoms are different, I strongly feel this is about same issue but with different side effects. 

Also, could you please check your logs if there is any exception in them about this? If you have one (or more), could you please share it with us on https://gist.github.com ?

**Comment by Dijkstra1-zz** [comment]
[Pictures.zip](https://github.com/RS485/LogisticsPipes/files/227726/Pictures.zip)
Here are some pictures of LP network, it has not done it for a while, but I have not been on minecraft as lately, but next it does it you can have log.

**Comment by davboecki** [comment]
Can you find something like https://gist.github.com/davboecki/527a7d14a87f6e63104217bb186a55be in your server logs ?

**Comment by Dijkstra1-zz** [comment]
I looked in both my server console, and my client console as soon as it happen last and the thing about LP is that I open GUI, I then check both the log files and they showed the same, as the console.

**Comment by Dijkstra1-zz** [comment]
Last time it happened I had things crafting and left the dimension the pipes where in and when I came back some of the batch job was done, but not all do not know if that caused it.

**Comment by Darklight-03** [comment]
I am having the same issue on my ftb infinity evolved server, also version 0.9.3.114. I get this in my console, which seems similar to what @davboecki posted earlier. I am unsure as to when this issue started occurring however, so I don't know if that came up at the same time as the request monitor stopped working. Reconnecting to the server does not fix the issue, but restarting the entire server probably does, I haven't tried that yet.

```
[00:45:40] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[00:45:40] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at logisticspipes.routing.order.LogisticsOrder.getTargetType(LogisticsOrder.java:97)
[00:45:40] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at logisticspipes.network.LPDataOutputStream.writeOrderInfo(LPDataOutputStream.java:188)
[00:45:40] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at logisticspipes.network.LPDataOutputStream$3.writeObject(LPDataOutputStream.java:200)
[00:45:40] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at logisticspipes.network.LPDataOutputStream$3.writeObject(LPDataOutputStream.java:196)
[00:45:40] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at logisticspipes.network.LPDataOutputStream.writeList(LPDataOutputStream.java:165)
[00:45:40] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at logisticspipes.network.LPDataOutputStream.writeLinkedLogisticsOrderList(LPDataOutputStream.java:196)
[00:45:40] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at logisticspipes.network.LPDataOutputStream$4.writeObject(LPDataOutputStream.java:207)
[00:45:40] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at logisticspipes.network.LPDataOutputStream$4.writeObject(LPDataOutputStream.java:203)
[00:45:40] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at logisticspipes.network.LPDataOutputStream.writeList(LPDataOutputStream.java:165)
[00:45:40] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at logisticspipes.network.LPDataOutputStream.writeLinkedLogisticsOrderList(LPDataOutputStream.java:203)
[00:45:40] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at logisticspipes.network.packets.orderer.OrdererWatchPacket.writeData(OrdererWatchPacket.java:39)
[00:45:40] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at logisticspipes.ticks.ServerPacketBufferHandlerThread$ServerCompressorThread.run(ServerPacketBufferHandlerThread.java:66)
```

Also I accidentally posted this earlier on the wrong issue, moved here.

**Comment by Dijkstra1-zz** [comment]
I have been the Infinity server for some time, but Infinity skyblocks SP world, I did manage to get it do it, [and this was in the log](https://github.com/RS485/LogisticsPipes/files/333121/LP.bug.txt).
I this happen after i broke a pipe that was meant to crafting but because it was losing items I upgrade to an MK3 crafting pipe, and it not until i do full client restart that fixes the problem, reloading the world has no affect.

**Comment by coehlrich** [comment]
this also happened to me.

**Comment by j2ghz** [comment]
Experiencing the same issue on `The 1.7.10 Pack` version `0.9.4`, using `logisticspipes-0.9.3.127.jar`.
```
[18:32:29] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[18:32:29] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.routing.order.LogisticsOrder.getTargetType(LogisticsOrder.java:100)
[18:32:29] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.network.LPDataOutputStream.writeOrderInfo(LPDataOutputStream.java:190)
[18:32:29] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.network.LPDataOutputStream$3.writeObject(LPDataOutputStream.java:205)
[18:32:29] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.network.LPDataOutputStream$3.writeObject(LPDataOutputStream.java:201)
[18:32:29] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.network.LPDataOutputStream.writeList(LPDataOutputStream.java:165)
[18:32:29] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.network.LPDataOutputStream.writeLinkedLogisticsOrderList(LPDataOutputStream.java:201)
[18:32:29] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.network.LPDataOutputStream$4.writeObject(LPDataOutputStream.java:212)
[18:32:29] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.network.LPDataOutputStream$4.writeObject(LPDataOutputStream.java:208)
[18:32:29] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.network.LPDataOutputStream.writeList(LPDataOutputStream.java:165)
[18:32:29] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.network.LPDataOutputStream.writeLinkedLogisticsOrderList(LPDataOutputStream.java:208)
[18:32:29] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.network.packets.orderer.OrdererWatchPacket.writeData(OrdererWatchPacket.java:39)
[18:32:29] [LogisticsPipes Packet Compressor Server/INFO] [STDERR/LogisticsPipes]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at logisticspipes.ticks.ServerPacketBufferHandlerThread$ServerCompressorThread.run(ServerPacketBufferHandlerThread.java:66)
```
